from fractions import Fraction
from itertools import combinations

import pytest

from e1_gmin_m4_signed_boolean_defect import (
    conformal_superadditivity_certificate,
    graver_voronoi_test,
    integer_lagrange_lower_bound,
    kernel_move_defect_change,
    moore_penrose_source_coordinate,
    parallel_row_functional,
    residual_fractional_backprojection_coordinate,
    signed_boolean_defect,
    signed_coordinate_defect,
    theorem_record,
)
from minmax_quadratic import paley_conference_prime_power


def test_coordinate_defect_is_nonnegative_and_has_exact_signed_boolean_roots():
    for tau in (-1, 1):
        for value in range(-30, 31):
            defect = signed_coordinate_defect(value, tau)
            assert defect >= 0
            assert (defect == 0) == (value in (0, tau))
    with pytest.raises(ValueError, match="sign"):
        signed_coordinate_defect(0, 0)


def test_vector_defect_has_the_exact_two_unit_norm_gap():
    tau = (1, -1, 1, -1)
    in_box = signed_boolean_defect((1, -1, 0, 0), tau)
    assert in_box["defect"] == 0
    assert in_box["squared_norm"] == in_box["tau_dot_z"] == 2
    assert in_box["in_signed_boolean_box"]

    outside = signed_boolean_defect((2, -1, 0, 0), tau)
    assert outside["defect"] == 1
    assert outside["squared_norm"] == outside["tau_dot_z"] + 2
    assert not outside["in_signed_boolean_box"]


def test_tau_is_the_weighted_sum_of_the_parallel_rows():
    # Each edge names its unique parallel direction.  Repetitions audit the
    # actual partition-of-columns argument, not just a permutation matrix.
    row = parallel_row_functional(
        parallel_direction_by_edge=(0, 2, 1, 2, 0, 3, 1),
        direction_signs=(1, -1, -1, 1),
        values=(3, -2, 4, 1, -5, 2, 7),
    )
    assert row["proved"]
    assert row["tau_is_integer_parallel_row_combination"]
    assert row["weighted_parallel_total_H_y"] == row["tau_dot_z"]
    assert row["induced_edge_signs_tau"] == [1, -1, -1, -1, 1, 1, -1]


def test_actual_paley_edge_sign_equals_its_unique_parallel_direction_sign():
    # This audits the precise source-sign convention used in Props 15.759--
    # 15.761.  Field elements are encoded as x+p*y, and the projective
    # functionals are x+lambda*y plus y at infinity.
    for p in (3, 5):
        conference = paley_conference_prime_power(p)
        directions = tuple((1, slope) for slope in range(p)) + ((0, 1),)
        epsilon = []
        for left, right in directions:
            kernel_representative = (
                1 if left == 0 else ((-right) % p) + p
            )
            epsilon.append(int(conference[1, 1 + kernel_representative]))

        parallel_directions = []
        tau = []
        for first, second in combinations(range(p * p), 2):
            x1, y1 = first % p, first // p
            x2, y2 = second % p, second // p
            parallel = [
                index
                for index, (left, right) in enumerate(directions)
                if (left * (x1 - x2) + right * (y1 - y2)) % p == 0
            ]
            assert len(parallel) == 1
            parallel_directions.append(parallel[0])
            tau.append(int(conference[1 + first, 1 + second]))
            assert tau[-1] == epsilon[parallel[0]]

        values = tuple((index % 7) - 3 for index in range(len(tau)))
        row = parallel_row_functional(parallel_directions, epsilon, values)
        assert row["induced_edge_signs_tau"] == tau
        assert row["weighted_parallel_total_H_y"] == row["tau_dot_z"]


def test_kernel_move_formula_drops_tau_term_exactly_when_tau_dot_g_is_zero():
    z = (1, -1, 1)
    tau = (1, 1, 1)
    for move in ((1, -3, 2), (-1, 3, -2)):
        row = kernel_move_defect_change(z, move, tau)
        assert row["proved"]
        assert row["tau_dot_move"] == 0
        expected = (
            2 * sum(a * b for a, b in zip(z, move))
            + sum(value * value for value in move)
        ) // 2
        assert row["defect_change"] == expected


def test_conformal_decomposition_gives_graver_superadditivity():
    row = conformal_superadditivity_certificate(
        values=(2, -1, 0),
        moves=((1, -1, 0), (2, -3, 1), (0, -2, 4)),
        tau=(1, -1, 1),
    )
    assert row["proved"]
    assert row["global_change_at_least_sum_of_piece_changes"]
    assert row["conformal_gram_gap"] >= 0
    with pytest.raises(ValueError, match="conformal"):
        conformal_superadditivity_certificate(
            (0, 0), ((1, -1), (-1, 1)), (1, 1)
        )


def test_nontrivial_complete_rank_one_graver_certificate_has_defect_one():
    # A=[[1,1,1],[0,2,3]], b=(1,1).  Its integer kernel is generated by
    # g=(1,-3,2), hence its Graver basis is exactly +/-g.  The displayed
    # lift solves Az=b.  A Boolean vector with first-row sum one would select
    # a single second-row entry from {0,2,3}, never 1.
    matrix = ((1, 1, 1), (0, 2, 3))
    target = (1, 1)
    z = (1, -1, 1)
    assert tuple(sum(row[j] * z[j] for j in range(3)) for row in matrix) == target
    audit = graver_voronoi_test(z, ((1, -3, 2), (-1, 3, -2)), (1, 1, 1))
    assert audit["defect"] == 1
    assert audit["no_supplied_move_improves"]
    assert [row["defect_change"] for row in audit["move_checks"]] == [13, 1]
    assert not audit["global_minimum_certified"]  # completeness is never guessed


def test_pointwise_pseudoinverse_and_residual_sign_formulas_agree_exactly():
    p = 7
    common_total = -23
    tau = -1
    epsilon_transverse = (1, -1, 1, 1, -1, -1, 1)
    normalized_cells = (2, -3, 5, 0, -4, 1, 6)
    actual_parallel_count = 9

    unsigned = moore_penrose_source_coordinate(
        p=p,
        common_total=common_total,
        parallel_target=tau * actual_parallel_count,
        transverse_target_cells=tuple(
            epsilon * value
            for epsilon, value in zip(epsilon_transverse, normalized_cells)
        ),
    )
    residual = residual_fractional_backprojection_coordinate(
        p=p,
        common_total=common_total,
        actual_parallel_count=actual_parallel_count,
        tau=tau,
        signed_backprojection_terms=tuple(
            tau * epsilon * value
            for epsilon, value in zip(epsilon_transverse, normalized_cells)
        ),
    )
    assert Fraction(residual["physical_fractional_coordinate_h_e"]) == (
        tau * Fraction(unsigned["R_plus_y_coordinate"])
    )
    assert residual["p_cubed_numerator"] == (
        tau * unsigned["p_cubed_numerator"]
    )
    assert residual["all_coordinates_in_interval_suffice_for_fractional_signed_box"]
    assert residual["necessity_not_claimed_because_real_kernel_shifts_are_available"]


def test_periodic_integer_dual_can_give_a_strict_no_boolean_certificate():
    # The equations fix z=(1,1,-1).  The first row is tau, so its target is
    # the fixed Boolean weight one, while the last two equations force two
    # selected coordinates.  Thus no Boolean vector is possible.  Here the
    # periodic integer dual is sharp at the displayed multiplier.
    matrix = ((1, 1, 1), (1, 0, 0), (0, 1, 0))
    target = (1, 1, 1)
    tau = (1, 1, 1)
    row = integer_lagrange_lower_bound(
        matrix, target, tau, (Fraction(-1), Fraction(1), Fraction(1))
    )
    assert Fraction(row["lower_bound"]) == 1
    assert Fraction(row["signed_box_farkas_slack"]) == 1
    assert row["periodic_bound_at_most_farkas_slack"]
    assert row["positive_bound_excludes_signed_boolean_lift"]
    assert row["no_integer_advantage_beyond_zonotope_separation"]


def test_periodic_dual_cannot_detect_an_integer_gap_inside_the_zonotope():
    # This is the rank-one-kernel Graver example above.  It has beta=1 and
    # no Boolean point, but x=(1/2,1/2,0) is a fractional box lift.  Therefore
    # every Farkas slack, and hence every periodic dual value, is <=0.
    matrix = ((1, 1, 1), (0, 2, 3))
    target = (1, 1)
    tau = (1, 1, 1)
    fractional = (Fraction(1, 2), Fraction(1, 2), Fraction(0))
    assert tuple(
        sum(Fraction(row[j]) * fractional[j] for j in range(3))
        for row in matrix
    ) == target
    for a in range(-8, 9):
        for b in range(-8, 9):
            row = integer_lagrange_lower_bound(
                matrix,
                target,
                tau,
                (Fraction(a, 4), Fraction(b, 4)),
            )
            assert Fraction(row["lower_bound"]) <= Fraction(
                row["signed_box_farkas_slack"]
            )
            assert Fraction(row["signed_box_farkas_slack"]) <= 0
            assert not row["positive_bound_excludes_signed_boolean_lift"]


def test_theorem_record_preserves_the_live_target():
    row = theorem_record()
    assert row["proved"]["tau_is_in_integral_parallel_row_span"]
    assert row["proved"]["defect_zero_iff_signed_boolean"]
    assert row["proved"]["positive_defect_has_two_unit_squared_norm_gap"]
    assert row["proved"]["complete_graver_nondecrease_is_global_optimality"]
    assert row["proved"]["pointwise_moore_penrose_formula"]
    assert not row["proved"]["compact_all_equal_target_beta_zero"]
    assert not row["proved"]["residual_ii_closed"]
    assert row["L_status"] == "OPEN"
