#!/usr/bin/env python3
"""Bounded exact torsion-support projections for the four z=7 H0_S0_M7 cases.

The pointed orbit-0/A integer row matrix has a 114-dimensional rational
left kernel generated by 112 primitive Johnson relations and two exact
quadratic-type sum relations.  This script proves that statement exactly,
then derives the characteristic-3 and characteristic-7 quotient dimensions
from the complete modular left kernels.  It never assumes the advertised
dimensions.

For each of the four reconstructed H0_S0_M7 leaves, all seven M catalogs are
kept complete and in one shared row order across both primes.  A bounded
projected-support sieve retains every mod-3 quotient coordinate and selected
mod-7 quotient coordinates.  Minkowski supports are convolved and
deduplicated exactly.  Exceeding ``--state-cap`` is an explicit skip, never
an approximation.  Absence of the projected target is a rigorous rejection;
presence is necessary-only.

This prototype deliberately supports bounded ``--smoke`` runs only.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import sys
import time
from collections import Counter
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "src"))

import p7_infinity7_positive_z7_compact_symmetry_audit as symmetry  # noqa: E402
import p7_infinity7_positive_z7_mod7_projection as parent  # noqa: E402
import p7_infinity7_positive_z7_pointed_affine_hull_multimod as affine  # noqa: E402
import p7_infinity7_positive_z7_pointed_mod7 as pointed  # noqa: E402
import p7_size_four_slack_classify as johnson  # noqa: E402
from p7_unsaturated_modular_catalog_filter import left_dependencies  # noqa: E402


P = 7
EDGE_COUNT = 4 * P + 1
TARGET_PATTERN = (0, 0, 7)
GLOBAL_MITM_STATE_CAP = 6_000_000
PAIR_CHUNK_CAP = 1_000_000
MAX_SMOKE_K = 4
MAX_SMOKE_PROJECTIONS = 8


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def array_sha256(array: np.ndarray) -> str:
    return hashlib.sha256(np.ascontiguousarray(array).tobytes()).hexdigest()


def json_sha256(value: object) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def exact_common_dependency_basis(
    matrix: np.ndarray, kernel_rows: np.ndarray
) -> tuple[np.ndarray, dict]:
    """Build the 112 Johnson plus two exact type-sum dependencies."""
    rows = []
    for direction in range(P + 1):
        for kernel_row in kernel_rows:
            dependency = np.zeros(matrix.shape[0], dtype=np.int64)
            dependency[1 + 35 * direction : 1 + 35 * (direction + 1)] = kernel_row
            rows.append(dependency)
    type_rows = []
    for quadratic_type in (-1, 1):
        dependency = np.zeros(matrix.shape[0], dtype=np.int64)
        dependency[0] = -60
        directions = []
        for direction, observed_type in enumerate(parent.DIRECTION_TYPES):
            if int(observed_type) == quadratic_type:
                dependency[1 + 35 * direction : 1 + 35 * (direction + 1)] = 1
                directions.append(direction)
        require(len(directions) == 4, "quadratic direction types are not four-by-four")
        rows.append(dependency)
        type_rows.append(
            {
                "quadratic_type": quadratic_type,
                "directions": directions,
                "identity": "sum of all 35 rows in these four directions = 60 * edge-count row",
            }
        )
    common = np.ascontiguousarray(np.stack(rows), dtype=np.int64)
    require(common.shape == (114, matrix.shape[0]), "exact common dependency shape changed")
    require(
        not np.any(common @ np.asarray(matrix, dtype=np.int64)),
        "claimed common dependency is not an exact integer left dependency",
    )
    rank_mod11 = affine.modular_rank(common, 11)
    require(rank_mod11 == 114, "exact common dependencies are not rationally independent")
    return common, {
        "primitive_Johnson_dependencies": 8 * 14,
        "quadratic_type_sum_dependencies": 2,
        "exact_common_dependency_dimension": 114,
        "independence_witness_modulus": 11,
        "independence_witness_rank": rank_mod11,
        "type_sum_relations": type_rows,
        "exact_integer_left_null_audit": True,
        "basis_sha256_int64": array_sha256(common),
    }


def extend_common_to_full(
    common: np.ndarray, complete: np.ndarray, modulus: int
) -> tuple[np.ndarray, tuple[int, ...], dict]:
    """Select deterministic complete-kernel rows complementing the common space."""
    reduced, pivots = symmetry.canonical_rref(common, modulus)
    reducer = [np.asarray(row, dtype=np.int64) for row in reduced]
    pivot_columns = list(pivots)
    common_rank = len(reducer)
    require(common_rank == 114, f"common dependency rank changed modulo {modulus}")
    selected = []
    selected_indices = []
    for index, source_row in enumerate(np.asarray(complete, dtype=np.int64)):
        residual = source_row.copy() % modulus
        for basis_row, pivot in zip(reducer, pivot_columns):
            if residual[pivot]:
                residual = (residual - residual[pivot] * basis_row) % modulus
        if not np.any(residual):
            continue
        pivot = int(np.flatnonzero(residual)[0])
        residual = residual * pow(int(residual[pivot]), -1, modulus) % modulus
        insertion = int(np.searchsorted(pivot_columns, pivot))
        pivot_columns.insert(insertion, pivot)
        reducer.insert(insertion, residual)
        selected.append(source_row.copy() % modulus)
        selected_indices.append(index)
        if len(reducer) == len(complete):
            break
    complement = np.ascontiguousarray(np.stack(selected), dtype=np.int64)
    expected = len(complete) - common_rank
    require(complement.shape == (expected, complete.shape[1]), "torsion complement shape changed")
    require(
        affine.modular_rank(np.vstack((common, complement)), modulus) == len(complete),
        f"common plus quotient complement does not span the mod-{modulus} kernel",
    )
    return complement, tuple(selected_indices), {
        "modulus": modulus,
        "complete_dependency_dimension": len(complete),
        "common_rational_reduction_rank": common_rank,
        "derived_quotient_dimension": len(complement),
        "selected_complete_dependency_indices": list(selected_indices),
        "complement_sha256_uint8": array_sha256(complement.astype(np.uint8)),
        "common_plus_complement_spans_complete_left_kernel": True,
    }


def derive_torsion_quotients(matrix: np.ndarray, common: np.ndarray) -> tuple[dict, dict]:
    """Prove rational completeness and derive the mod-3/mod-7 quotients."""
    modular_data = {}
    rank_rows = []
    for modulus in (3, 7, 11):
        matrix_rank, dependencies = left_dependencies(matrix, modulus)
        dependencies = np.ascontiguousarray(dependencies, dtype=np.int64)
        require(
            not np.any(dependencies @ (matrix % modulus) % modulus),
            f"complete mod-{modulus} left kernel failed direct audit",
        )
        require(
            affine.modular_rank(dependencies, modulus) == len(dependencies),
            f"complete mod-{modulus} dependency basis is not full",
        )
        modular_data[modulus] = {
            "matrix_rank": int(matrix_rank),
            "dependencies": dependencies,
        }
        rank_rows.append(
            {
                "modulus": modulus,
                "matrix_rank": int(matrix_rank),
                "left_dependency_dimension": len(dependencies),
                "dependency_sha256_uint8": array_sha256(dependencies.astype(np.uint8)),
                "left_null_and_full_basis_audit": True,
            }
        )

    exact_common_rank = affine.modular_rank(common, 11)
    rational_rank_upper = matrix.shape[0] - exact_common_rank
    rational_rank_lower = modular_data[11]["matrix_rank"]
    require(
        rational_rank_upper == rational_rank_lower == 168,
        "exact rational pointed-matrix rank was not pinned",
    )
    rational_nullity = matrix.shape[0] - rational_rank_upper
    require(rational_nullity == len(common) == 114, "rational dependency completeness failed")

    quotient_data = {}
    quotient_rows = []
    for modulus in (3, 7):
        complete = modular_data[modulus]["dependencies"]
        require(
            affine.modular_rank(np.vstack((complete, common)), modulus) == len(complete),
            f"exact common dependencies escaped the complete mod-{modulus} kernel",
        )
        complement, indices, audit = extend_common_to_full(common, complete, modulus)
        quotient_data[modulus] = {
            "complete": complete,
            "complement": complement,
            "selected_indices": indices,
        }
        quotient_rows.append(audit)
    actual_dimensions = {
        modulus: len(quotient_data[modulus]["complement"]) for modulus in (3, 7)
    }
    return quotient_data, {
        "integer_pointed_matrix_shape": list(matrix.shape),
        "integer_pointed_matrix_sha256_int64": array_sha256(
            np.asarray(matrix, dtype=np.int64)
        ),
        "rational_rank_upper_from_114_exact_independent_dependencies": rational_rank_upper,
        "rational_rank_lower_from_nonzero_mod11_minor": rational_rank_lower,
        "exact_rational_rank": rational_rank_upper,
        "exact_rational_left_dependency_dimension": rational_nullity,
        "complete_modular_rank_audits": rank_rows,
        "quotient_audits": quotient_rows,
        "actual_effective_dimensions": {
            f"F{modulus}": dimension for modulus, dimension in actual_dimensions.items()
        },
        "claimed_dimensions_F3_6_F7_21_reproduced": actual_dimensions == {3: 6, 7: 21},
        "derivation": (
            "quotient the complete characteristic-p left kernel by the reduction of the "
            "complete 114-dimensional exact rational left kernel"
        ),
    }


def encode_rows(rows: np.ndarray, moduli: tuple[int, ...]) -> np.ndarray:
    source = np.ascontiguousarray(rows, dtype=np.uint8)
    require(source.ndim == 2 and source.shape[1] == len(moduli), "state encoding width changed")
    multipliers = np.ones(len(moduli), dtype=np.uint64)
    for index in range(1, len(moduli)):
        multipliers[index] = multipliers[index - 1] * moduli[index - 1]
    return np.ascontiguousarray(
        np.sum(source.astype(np.uint64) * multipliers[None, :], axis=1),
        dtype=np.uint64,
    )


def decode_rows(codes: np.ndarray, moduli: tuple[int, ...]) -> np.ndarray:
    source = np.ascontiguousarray(codes, dtype=np.uint64)
    out = np.empty((len(source), len(moduli)), dtype=np.uint8)
    multiplier = 1
    for index, modulus in enumerate(moduli):
        out[:, index] = (source // multiplier % modulus).astype(np.uint8)
        multiplier *= modulus
    return out


def unique_rows(rows: np.ndarray, moduli: tuple[int, ...]) -> np.ndarray:
    codes = np.unique(encode_rows(rows, moduli))
    return decode_rows(codes, moduli)


def exact_support_convolution(
    supports: list[np.ndarray],
    target: np.ndarray,
    moduli: tuple[int, ...],
    state_cap: int,
) -> dict:
    """Exact capped Minkowski support convolution in a finite product group."""
    require(state_cap > 0, "state cap must be positive")
    require(len(target) == len(moduli), "projected target width changed")
    normalized = [unique_rows(support, moduli) for support in supports]
    require(all(len(support) > 0 for support in normalized), "empty exact catalog support")
    group_size = math.prod(moduli)
    states = np.zeros((1, len(moduli)), dtype=np.uint8)
    state_sizes = []
    pair_blocks = 0
    pair_candidates = 0
    for support_index, support in enumerate(normalized):
        accumulated = np.empty(0, dtype=np.uint64)
        state_chunk = max(1, PAIR_CHUNK_CAP // len(support))
        moduli_array = np.asarray(moduli, dtype=np.uint16)
        for start in range(0, len(states), state_chunk):
            left = states[start : start + state_chunk].astype(np.uint16)
            sums = (
                left[:, None, :] + support[None, :, :].astype(np.uint16)
            ) % moduli_array[None, None, :]
            codes = np.unique(encode_rows(sums.reshape(-1, len(moduli)), moduli))
            accumulated = np.union1d(accumulated, codes)
            pair_blocks += 1
            pair_candidates += len(left) * len(support)
            if len(accumulated) > state_cap:
                return {
                    "completed_exact_convolution": False,
                    "decision_status": "skipped_state_cap",
                    "rigorous_rejection": False,
                    "projected_target_present": None,
                    "necessary_only_projected_survivor": None,
                    "completed_catalog_factors": support_index,
                    "first_capped_factor_index": support_index,
                    "distinct_states_lower_bound_at_skip": len(accumulated),
                    "state_cap": state_cap,
                    "finite_group_size": group_size,
                    "exact_support_sizes": [len(row) for row in normalized],
                    "completed_state_sizes": state_sizes,
                    "pair_blocks": pair_blocks,
                    "pair_candidates_examined": pair_candidates,
                    "skip_is_explicit_not_approximation": True,
                }
        states = decode_rows(accumulated, moduli)
        state_sizes.append(len(states))
        if len(states) == group_size:
            state_sizes.extend([group_size] * (len(normalized) - support_index - 1))
            break

    final_codes = np.unique(encode_rows(states, moduli))
    target_code = int(encode_rows(np.asarray(target, dtype=np.uint8)[None, :], moduli)[0])
    present = bool(np.any(final_codes == target_code))
    return {
        "completed_exact_convolution": True,
        "decision_status": (
            "necessary_only_projected_target_present"
            if present
            else "rigorous_projected_support_rejection"
        ),
        "rigorous_rejection": not present,
        "projected_target_present": present,
        "necessary_only_projected_survivor": present,
        "completed_catalog_factors": len(normalized),
        "state_cap": state_cap,
        "finite_group_size": group_size,
        "exact_support_sizes": [len(row) for row in normalized],
        "completed_state_sizes": state_sizes,
        "final_state_count": len(final_codes),
        "final_support_sha256_uint64": array_sha256(final_codes),
        "target_code": target_code,
        "pair_blocks": pair_blocks,
        "pair_candidates_examined": pair_candidates,
        "full_group_saturation_shortcut_is_exact": bool(len(states) == group_size),
    }


def brute_support(supports: list[np.ndarray], moduli: tuple[int, ...]) -> set[tuple[int, ...]]:
    return {
        tuple(
            int(sum(choice[index] for choice in rows) % moduli[index])
            for index in range(len(moduli))
        )
        for rows in itertools.product(*supports)
        for choice in [rows]
    }


def manufactured_self_audit() -> dict:
    moduli = (3, 7)
    supports = [
        np.asarray([[0, 0], [1, 1], [2, 4]], dtype=np.uint8),
        np.asarray([[0, 0], [1, 2]], dtype=np.uint8),
        np.asarray([[0, 1], [2, 0]], dtype=np.uint8),
    ]
    expected = brute_support(supports, moduli)
    present_target = np.asarray(next(iter(sorted(expected))), dtype=np.uint8)
    absent_target = next(
        np.asarray(value, dtype=np.uint8)
        for value in itertools.product(range(3), range(7))
        if value not in expected
    )
    positive = exact_support_convolution(supports, present_target, moduli, 100)
    negative = exact_support_convolution(supports, absent_target, moduli, 100)
    require(
        positive["completed_exact_convolution"]
        and positive["projected_target_present"] is True
        and negative["completed_exact_convolution"]
        and negative["rigorous_rejection"] is True
        and positive["final_state_count"] == negative["final_state_count"] == len(expected),
        "manufactured support convolution disagrees with brute force",
    )

    trap_support = [np.asarray([[0, 1], [1, 0]], dtype=np.uint8)]
    trap = exact_support_convolution(
        trap_support, np.asarray([0, 0], dtype=np.uint8), moduli, 10
    )
    require(
        trap["rigorous_rejection"] is True
        and any(row[0] == 0 for row in trap_support[0])
        and any(row[1] == 0 for row in trap_support[0]),
        "same-index cross-prime false-positive trap failed",
    )

    cap_supports = [
        np.asarray([[value, 0] for value in range(5)], dtype=np.uint8),
        np.asarray([[0, value] for value in range(5)], dtype=np.uint8),
    ]
    capped = exact_support_convolution(
        cap_supports, np.asarray([0, 0], dtype=np.uint8), (5, 5), 10
    )
    require(
        capped["decision_status"] == "skipped_state_cap"
        and capped["skip_is_explicit_not_approximation"] is True,
        "manufactured state-cap audit failed",
    )
    return {
        "brute_force_group": "F3 x F7",
        "brute_force_support_size": len(expected),
        "present_target_detected": True,
        "absent_target_rigorously_rejected": True,
        "same_index_cross_prime_trap_rejected": True,
        "state_cap_produces_explicit_skip": True,
        "audit_sha256": json_sha256(
            {
                "positive": positive,
                "negative": negative,
                "trap": trap,
                "capped": capped,
            }
        ),
    }


def quotient_case_signatures(
    case_index: int,
    leaf_index: int,
    leaf: dict,
    orbit: dict,
    system: dict,
    common: np.ndarray,
    quotient_data: dict,
    anchors: affine.AnchorFactory,
    cache: dict,
) -> tuple[dict, list[np.ndarray], np.ndarray]:
    anchor_rhs = np.asarray(system["base_rhs"], dtype=np.int64).copy()
    anchor_rows = []
    for direction, (mask, mean) in enumerate(zip(orbit["masks"], leaf["scaled_means"])):
        anchor = anchors.get(int(mask), int(mean))
        anchor_rows.append(anchor)
        anchor_rhs[1 + 35 * direction : 1 + 35 * (direction + 1)] = 13 - anchor
    require(not np.any(common @ anchor_rhs), "exact rational dependencies reject anchor target")

    target_components = []
    for modulus in (3, 7):
        complement = quotient_data[modulus]["complement"]
        target_components.append((-complement @ anchor_rhs % modulus).astype(np.uint8))
    target = np.ascontiguousarray(np.concatenate(target_components), dtype=np.uint8)
    q3 = len(quotient_data[3]["complement"])
    q7 = len(quotient_data[7]["complement"])
    require(target.shape == (q3 + q7,), "torsion target width changed")

    variable_directions = tuple(int(value) for value in leaf["enumerated_directions"])
    unique_direction = tuple(
        direction for direction, value in enumerate(leaf["catalog_classes"]) if value == "U"
    )
    require(
        len(variable_directions) == 7
        and len(unique_direction) == 1
        and not leaf["high_directions"],
        "selected case is not exactly seven M catalogs plus one U",
    )
    fixed_direction = unique_direction[0]
    fixed_catalog = affine.mapped_catalog(
        int(orbit["masks"][fixed_direction]),
        int(leaf["scaled_means"][fixed_direction]),
    ).astype(np.int64)
    require(
        fixed_catalog.shape == (1, 35)
        and np.array_equal(fixed_catalog[0], anchor_rows[fixed_direction]),
        "U direction is not the exact fixed anchor row",
    )

    signatures = []
    direction_audits = []
    for direction in variable_directions:
        mask = int(orbit["masks"][direction])
        mean = int(leaf["scaled_means"][direction])
        key = (direction, mask, mean)
        if key not in cache:
            catalog = affine.mapped_catalog(mask, mean).astype(np.int64)
            anchor = anchors.get(mask, mean)
            delta = np.ascontiguousarray(anchor[None, :] - catalog, dtype=np.int64)
            require(catalog.shape == (1_764, 35), "M catalog is not complete size 1,764")
            require(
                np.all(2 * catalog.sum(axis=1, dtype=np.int64) == 5 * mean),
                "M catalog exact mean changed",
            )
            require(
                not np.any(anchors.kernel_rows @ catalog.T)
                and np.all((catalog % 2) == affine.parity_for_mask(mask)[None, :]),
                "M catalog lost exact degree two or parity",
            )
            block = slice(1 + 35 * direction, 1 + 35 * (direction + 1))
            require(
                not np.any(common[:, block] @ delta.T),
                "catalog variation is visible to an exact rational dependency",
            )
            components = []
            for modulus in (3, 7):
                complement_block = quotient_data[modulus]["complement"][:, block]
                component = complement_block @ (delta.T % modulus) % modulus
                components.append(np.ascontiguousarray(component.T, dtype=np.uint8))
            joint = np.ascontiguousarray(np.concatenate(components, axis=1), dtype=np.uint8)
            require(len(joint) == len(catalog), "joint torsion signature lost row identity")
            cache[key] = (
                joint,
                catalog,
                {
                    "direction": direction,
                    "mask": mask,
                    "scaled_mean": mean,
                    "complete_catalog_rows": len(catalog),
                    "exact_catalog_sha256_int16": array_sha256(catalog.astype(np.int16)),
                    "joint_signature_shape": list(joint.shape),
                    "joint_signature_sha256_uint8": array_sha256(joint),
                    "same_exact_catalog_row_index_used_mod3_and_mod7": True,
                    "all_catalog_variations_annihilated_by_exact_rational_dependencies": True,
                },
            )
        joint, _catalog, audit = cache[key]
        signatures.append(joint)
        direction_audits.append(audit)

    chosen_indices = [int((37 * case_index + 19 * position) % 1_764) for position in range(7)]
    direct_rhs = anchor_rhs.copy()
    for position, direction in enumerate(variable_directions):
        _joint, catalog, _audit = cache[
            (direction, int(orbit["masks"][direction]), int(leaf["scaled_means"][direction]))
        ]
        direct_rhs[1 + 35 * direction : 1 + 35 * (direction + 1)] = (
            13 - catalog[chosen_indices[position]]
        )
    offset = 0
    for modulus in (3, 7):
        complement = quotient_data[modulus]["complement"]
        width = len(complement)
        reconstructed = (-target[offset : offset + width].astype(np.int64)) % modulus
        reconstructed += sum(
            signatures[position][chosen_indices[position], offset : offset + width].astype(
                np.int64
            )
            for position in range(7)
        )
        require(
            np.array_equal(reconstructed % modulus, complement @ direct_rhs % modulus),
            f"manufactured case RHS/signature identity failed modulo {modulus}",
        )
        offset += width

    full_unique_sizes = [len(np.unique(rows, axis=0)) for rows in signatures]
    require(all(size > 0 for size in full_unique_sizes), "torsion catalog support is empty")
    best_side = min(
        max(
            math.prod(full_unique_sizes[index] for index in left),
            math.prod(
                full_unique_sizes[index]
                for index in range(7)
                if index not in set(left)
            ),
        )
        for size in range(1, 8)
        for left in itertools.combinations(range(7), size)
        if 0 in left
    )
    require(
        best_side > GLOBAL_MITM_STATE_CAP,
        "selected H0M7 case would not be skipped by the six-million-state global MITM",
    )
    return {
        "case_key": f"orbit0_leaf{leaf_index}_branchA",
        "branch_orbit_index": 0,
        "orbit_leaf_index": leaf_index,
        "pointed_star_branch": "A",
        "catalog_pattern": "H0_S0_M7",
        "scaled_means": list(leaf["scaled_means"]),
        "catalog_classes": list(leaf["catalog_classes"]),
        "variable_M_directions": list(variable_directions),
        "fixed_U_direction": fixed_direction,
        "torsion_target_sha256_uint8": array_sha256(target),
        "torsion_target": target.tolist(),
        "complete_catalog_rows_per_M_direction": 1_764,
        "full_torsion_unique_support_sizes": full_unique_sizes,
        "derived_best_balanced_full_torsion_side_states": best_side,
        "six_million_global_MITM_skip_reproduced": True,
        "direction_signature_audits": direction_audits,
        "manufactured_direct_rhs_signature_formula_audited_mod3_mod7": True,
    }, signatures, target


def projected_supports(
    signatures: list[np.ndarray],
    target: np.ndarray,
    q3: int,
    mod7_subset: tuple[int, ...],
) -> tuple[list[np.ndarray], np.ndarray, tuple[int, ...]]:
    columns = tuple(range(q3)) + tuple(q3 + value for value in mod7_subset)
    supports = [np.ascontiguousarray(rows[:, columns], dtype=np.uint8) for rows in signatures]
    projected_target = np.ascontiguousarray(target[list(columns)], dtype=np.uint8)
    moduli = (3,) * q3 + (7,) * len(mod7_subset)
    return supports, projected_target, moduli


def projected_size_score(
    signatures: list[np.ndarray], q3: int, subset: tuple[int, ...]
) -> tuple[int, tuple[int, ...]]:
    supports, _target, moduli = projected_supports(
        signatures, np.zeros(signatures[0].shape[1], dtype=np.uint8), q3, subset
    )
    sizes = tuple(len(unique_rows(rows, moduli)) for rows in supports)
    return math.prod(sizes), sizes


def projection_subsets(
    signatures: list[np.ndarray], q3: int, q7: int, k: int, count: int
) -> list[dict]:
    require(0 <= k <= min(MAX_SMOKE_K, q7), "unsafe or unavailable mod-7 projection width")
    require(1 <= count <= MAX_SMOKE_PROJECTIONS, "unsafe smoke projection count")
    if k == 0:
        return [{"strategy": "all_mod3_only", "mod7_coordinates": ()}]
    candidates = []

    def add(strategy: str, subset: tuple[int, ...]) -> None:
        subset = tuple(sorted(int(value) for value in subset))
        if len(subset) == k and subset not in {row["mod7_coordinates"] for row in candidates}:
            candidates.append({"strategy": strategy, "mod7_coordinates": subset})

    add("prefix", tuple(range(k)))
    add("suffix", tuple(range(q7 - k, q7)))
    spread = tuple(sorted({int(index * q7 / k) for index in range(k)}))
    if len(spread) == k:
        add("evenly_spaced", spread)

    for maximize, name in ((False, "greedy_min_support_product"), (True, "greedy_max_support_product")):
        selected: tuple[int, ...] = ()
        while len(selected) < k:
            scored = []
            for coordinate in range(q7):
                if coordinate in selected:
                    continue
                subset = tuple(sorted((*selected, coordinate)))
                score, sizes = projected_size_score(signatures, q3, subset)
                scored.append((score, coordinate, subset, sizes))
            choice = (
                max(scored, key=lambda row: (row[0], -row[1]))
                if maximize
                else min(scored, key=lambda row: (row[0], row[1]))
            )
            selected = choice[2]
        add(name, selected)

    for subset in itertools.combinations(range(q7), k):
        if len(candidates) >= count:
            break
        add("lexicographic_fill", subset)
    rows = candidates[:count]
    for row in rows:
        score, sizes = projected_size_score(signatures, q3, row["mod7_coordinates"])
        row["individual_support_product_score"] = score
        row["individual_projected_support_sizes"] = list(sizes)
    return rows


def run(smoke: bool, state_cap: int, k: int, projection_count: int) -> dict:
    started = time.time()
    require(smoke, "this prototype deliberately supports --smoke only")
    require(0 < state_cap <= 2_000_000, "smoke state cap must lie in 1..2,000,000")
    require(0 <= k <= MAX_SMOKE_K, "smoke k must lie in 0..4")
    context = symmetry.construct_pointed_systems()
    system = context["systems"][0]["A"]
    matrix = np.ascontiguousarray(system["matrix"], dtype=np.int64)
    require(matrix.shape == (282, 1_225), "orbit0/A pointed matrix shape changed")
    kernel_rows = np.asarray(johnson._primitive_left_kernel_rows(), dtype=np.int64)  # noqa: SLF001
    require(kernel_rows.shape == (14, 35), "primitive Johnson kernel shape changed")
    common, common_audit = exact_common_dependency_basis(matrix, kernel_rows)
    quotient_data, quotient_audit = derive_torsion_quotients(matrix, common)
    q3 = len(quotient_data[3]["complement"])
    q7 = len(quotient_data[7]["complement"])
    require(k <= q7, "requested mod-7 coordinates exceed derived quotient")

    leaves_by_orbit, leaf_audit = parent.exact_mean_leaves(context["orbits"])
    selected = [
        (leaf_index, leaf)
        for leaf_index, leaf in enumerate(leaves_by_orbit[0])
        if tuple(int(value) for value in leaf["pattern"]) == TARGET_PATTERN
    ]
    require(len(selected) == 4, "orbit0 H0_S0_M7 representative census changed")
    require(
        all(
            Counter(leaf["catalog_classes"]) == Counter({"M": 7, "U": 1})
            and not leaf["high_directions"]
            for _index, leaf in selected
        ),
        "selected leaf is not seven exact M catalogs plus one U",
    )

    hull_kernel, _hull_bases, hull_audit = affine.build_hull_audit()
    require(np.array_equal(hull_kernel, kernel_rows), "hull and compact kernel rows disagree")
    source_catalog = affine.canonical_catalog(7, 4).astype(np.int64)
    anchors = affine.AnchorFactory(kernel_rows, source_catalog[1:] - source_catalog[0])
    signature_cache = {}
    case_results = []
    projection_totals: Counter[str] = Counter()
    for case_index, (leaf_index, leaf) in enumerate(selected):
        case_audit, signatures, target = quotient_case_signatures(
            case_index,
            leaf_index,
            leaf,
            context["orbits"][0],
            system,
            common,
            quotient_data,
            anchors,
            signature_cache,
        )
        subset_rows = projection_subsets(signatures, q3, q7, k, projection_count)
        projections = []
        for subset_row in subset_rows:
            subset = tuple(subset_row["mod7_coordinates"])
            raw_supports, projected_target, moduli = projected_supports(
                signatures, target, q3, subset
            )
            exact_supports = [unique_rows(rows, moduli) for rows in raw_supports]
            decision = exact_support_convolution(
                exact_supports, projected_target, moduli, state_cap
            )
            projection_totals[decision["decision_status"]] += 1
            projections.append(
                {
                    **subset_row,
                    "retained_all_mod3_quotient_coordinates": list(range(q3)),
                    "retained_mod7_quotient_coordinates": list(subset),
                    "projected_group": f"F3^{q3} x F7^{len(subset)}",
                    "projected_target_sha256_uint8": array_sha256(projected_target),
                    "same_catalog_row_identity_used_across_projected_primes": True,
                    **decision,
                }
            )
        rejected = any(row["rigorous_rejection"] for row in projections)
        skipped = any(row["decision_status"] == "skipped_state_cap" for row in projections)
        case_results.append(
            {
                **case_audit,
                "projection_count": len(projections),
                "projections": projections,
                "rigorously_rejected_by_at_least_one_exact_projection": rejected,
                "any_projection_skipped_state_cap": skipped,
                "case_status": (
                    "rigorously_rejected_by_exact_projected_support"
                    if rejected
                    else "bounded_projected_support_survivor_with_skips"
                    if skipped
                    else "necessary_only_survivor_of_all_tested_exact_projections"
                ),
            }
        )

    rejected_cases = sum(
        row["rigorously_rejected_by_at_least_one_exact_projection"] for row in case_results
    )
    return {
        "experiment": "p7_infinity7_positive_z7_torsion_support_projection",
        "status": "complete_bounded_smoke_torsion_support_projection",
        "p": P,
        "c_H": 1,
        "z": 7,
        "phase": 0,
        "scope": "four orbit0/A H0_S0_M7 affine-hull survivors skipped by six-million-state global MITM",
        "smoke_test": True,
        "solver_invoked": False,
        "heavy_or_full_search_run": False,
        "configuration": {
            "state_cap": state_cap,
            "retained_all_mod3_quotient_coordinates": True,
            "selected_mod7_coordinate_count_k": k,
            "projection_subsets_per_case_bound": projection_count,
            "pair_chunk_cap": PAIR_CHUNK_CAP,
            "maximum_allowed_smoke_k": MAX_SMOKE_K,
        },
        "source_provenance": {
            "orbit_source": context["orbit_source"],
            "mean_leaf_coverage": leaf_audit,
            "pointed_case": "orbit0/A",
            "pointed_fixed_edge_rows": system["fixed_edge_rows"],
            "pointed_base_rhs_sha256_int64": array_sha256(
                np.asarray(system["base_rhs"], dtype=np.int64)
            ),
            "selected_leaf_indices": [index for index, _leaf in selected],
            "selected_case_keys": [f"orbit0_leaf{index}_branchA" for index, _leaf in selected],
        },
        "exact_common_rational_dependency_audit": common_audit,
        "varying_torsion_quotient_audit": quotient_audit,
        "degree_two_zero_mean_hull_audit": hull_audit,
        "manufactured_self_audit": manufactured_self_audit(),
        "processed_cases": len(case_results),
        "rigorously_rejected_cases": rejected_cases,
        "necessary_only_or_skipped_cases": len(case_results) - rejected_cases,
        "projection_decision_census": dict(sorted(projection_totals.items())),
        "case_results": case_results,
        "logical_semantics": {
            "quotient_dimensions_are_derived_not_assumed": True,
            "all_seven_M_catalogs_are_complete_exact_1764_row_sets": True,
            "same_catalog_row_index_supplies_mod3_and_mod7_signatures": True,
            "coordinate_projection_is_an_exact_group_homomorphism": True,
            "projected_target_absence_rigorously_rejects_the_full_global_join_case": True,
            "projected_target_presence_is_necessary_only": True,
            "state_cap_excess_is_an_explicit_skip_not_a_rejection": True,
            "raw_binary_edge_feasibility_claimed": False,
            "full_z7_closure_claimed": False,
        },
        "all_selected_case_and_projection_audits_passed": True,
        "elapsed_seconds": time.time() - started,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--state-cap", type=int, default=200_000)
    parser.add_argument("--k", type=int, default=2)
    parser.add_argument("--projections", type=int, default=4)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    result = run(args.smoke, args.state_cap, args.k, args.projections)
    pointed.atomic_write(args.output, result)
    print(
        json.dumps(
            {
                "status": result["status"],
                "output": str(args.output),
                "actual_effective_dimensions": result[
                    "varying_torsion_quotient_audit"
                ]["actual_effective_dimensions"],
                "processed_cases": result["processed_cases"],
                "rigorously_rejected_cases": result["rigorously_rejected_cases"],
                "projection_decision_census": result["projection_decision_census"],
                "elapsed_seconds": result["elapsed_seconds"],
            },
            indent=2,
            sort_keys=True,
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
