#!/usr/bin/env python3
"""Build and audit the Normaliz input for the p=7 Johnson slack semigroup.

The cone is

    S = {L in Z^35_{≥0} : K L = 0},

where K is the primitive 14-by-35 left kernel of degree-at-most-two
functions on J(7,4).  Its Hilbert basis determines whether the unenumerated
high slack catalogs are generated by the known grade-one/grade-two catalogs.
"""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import os
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from p7_size_four_slack_classify import (  # noqa: E402
    _primitive_left_kernel_rows,
    johnson_space,
)
from p7_infinity7_positive_z2_mod7_join import canonical_catalog  # noqa: E402
import p7_infinity7_positive_z7_mod7_projection as z7  # noqa: E402


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def atomic_write(path: Path, value: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.{time.time_ns()}.tmp")
    try:
        with temporary.open("wb") as stream:
            stream.write(value)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def sorted_rows(rows: np.ndarray) -> np.ndarray:
    """Return a deterministic lexicographic ordering of distinct integer rows."""
    rows = np.ascontiguousarray(rows, dtype=np.int64)
    require(rows.ndim == 2 and rows.shape[1] == 35, "row matrix has bad shape")
    if not len(rows):
        return rows
    order = np.lexsort(tuple(rows[:, column] for column in reversed(range(rows.shape[1]))))
    return np.ascontiguousarray(rows[order], dtype=np.int64)


def unique_rows(rows: np.ndarray) -> np.ndarray:
    rows = sorted_rows(rows)
    if len(rows) <= 1:
        return rows
    keep = np.ones(len(rows), dtype=bool)
    keep[1:] = np.any(rows[1:] != rows[:-1], axis=1)
    return np.ascontiguousarray(rows[keep], dtype=np.int64)


def parse_normaliz_generators(path: Path) -> tuple[np.ndarray, dict[str, object]]:
    raw = path.read_bytes()
    lines = [line.strip() for line in raw.decode("ascii").splitlines() if line.strip()]
    require(len(lines) >= 2, "Normaliz .gen file is truncated")
    row_count = int(lines[0])
    dimension = int(lines[1])
    require(row_count == 896 and dimension == 35, "Normaliz Hilbert-basis header changed")
    require(len(lines) == row_count + 2, "Normaliz .gen row count disagrees with header")
    rows = np.asarray(
        [[int(value) for value in line.split()] for line in lines[2:]],
        dtype=np.int64,
    )
    require(rows.shape == (row_count, dimension), "Normaliz generator matrix shape changed")
    require(np.all(rows >= 0), "Normaliz emitted a negative semigroup generator")
    require(np.all(rows <= 1), "Normaliz Hilbert generator is no longer binary")
    require(len(unique_rows(rows)) == row_count, "Normaliz emitted duplicate generators")
    return rows, {
        "path": str(path.resolve()),
        "file_bytes": len(raw),
        "file_sha256": sha256_bytes(raw),
        "declared_hilbert_basis_elements": row_count,
        "declared_ambient_dimension": dimension,
        "all_rows_parsed_and_distinct_nonnegative": True,
    }


def pair_sum_catalog(rows: np.ndarray) -> np.ndarray:
    rows = np.ascontiguousarray(rows, dtype=np.int64)
    sums = [rows[first] + rows[second] for first in range(len(rows)) for second in range(first, len(rows))]
    return unique_rows(np.asarray(sums, dtype=np.int64))


def triple_sum_catalog(rows: np.ndarray) -> np.ndarray:
    rows = np.ascontiguousarray(rows, dtype=np.int64)
    sums = [
        rows[first] + rows[second] + rows[third]
        for first in range(len(rows))
        for second in range(first, len(rows))
        for third in range(second, len(rows))
    ]
    return unique_rows(np.asarray(sums, dtype=np.int64))


def required_z7_grade_audit() -> dict[str, object]:
    orbits, orbit_source = z7.load_z7_orbits()
    leaves_by_orbit, leaf_audit = z7.exact_mean_leaves(orbits)
    class_grade_counts: Counter[tuple[str, int]] = Counter()
    high_grade_counts: Counter[int] = Counter()
    for orbit, leaves in zip(orbits, leaves_by_orbit):
        for leaf in leaves:
            for mask, mean, catalog_class in zip(
                orbit["masks"], leaf["scaled_means"], leaf["catalog_classes"]
            ):
                b = int(mask).bit_count()
                require(b in (1, 7), "z=7 direction has unexpected odd-fibre count")
                floor_mean = 0 if b == 7 else 8
                require(int(mean) >= floor_mean and (int(mean) - floor_mean) % 4 == 0, "bad excess grade")
                grade = (int(mean) - floor_mean) // 4
                class_grade_counts[(str(catalog_class), grade)] += 1
                if str(catalog_class) == "H":
                    high_grade_counts[grade] += 1
    require(sum(class_grade_counts.values()) == 2_160 * 8, "grade audit lost a direction occurrence")
    require({grade for (kind, grade) in class_grade_counts if kind == "U"} == {0}, "U grade changed")
    require({grade for (kind, grade) in class_grade_counts if kind == "S"} == {1}, "S grade changed")
    require({grade for (kind, grade) in class_grade_counts if kind == "M"} == {2}, "M grade changed")
    require(high_grade_counts and min(high_grade_counts) == 3 and max(high_grade_counts) == 8, "high-grade range changed")
    return {
        "orbit_source": orbit_source,
        "mean_leaf_coverage_sha256": hashlib.sha256(
            json.dumps(leaf_audit, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest(),
        "direction_occurrences": sum(class_grade_counts.values()),
        "class_grade_occurrence_histogram": {
            f"{kind}_grade{grade}": count
            for (kind, grade), count in sorted(class_grade_counts.items())
        },
        "high_grade_occurrence_histogram": {
            str(grade): count for grade, count in sorted(high_grade_counts.items())
        },
        "minimum_required_high_grade": min(high_grade_counts),
        "maximum_required_high_grade": max(high_grade_counts),
        "U_S_M_are_exactly_grades_0_1_2": True,
        "all_high_catalogs_are_grades_3_through_8": True,
    }


def hilbert_layer_counts(text: str, maximum_grade: int) -> dict[str, object] | None:
    marker = "Hilbert series:\n"
    denominator_marker = "denominator with 21 factors:\n"
    if marker not in text or denominator_marker not in text:
        return None
    numerator_line = text.split(marker, 1)[1].splitlines()[0]
    denominator_line = text.split(denominator_marker, 1)[1].splitlines()[0]
    numerator = [int(value) for value in numerator_line.split()]
    denominator_factors = {}
    for token in denominator_line.split():
        degree, multiplicity = token.split(":", 1)
        denominator_factors[int(degree)] = int(multiplicity)
    require(denominator_factors == {1: 15, 2: 5, 6: 1}, "Hilbert-series denominator changed")

    reciprocal = [0] * (maximum_grade + 1)
    reciprocal[0] = 1
    for degree, multiplicity in sorted(denominator_factors.items()):
        for _copy in range(multiplicity):
            for grade in range(degree, maximum_grade + 1):
                reciprocal[grade] += reciprocal[grade - degree]
    layers = [
        sum(numerator[index] * reciprocal[grade - index] for index in range(min(grade, len(numerator) - 1) + 1))
        for grade in range(maximum_grade + 1)
    ]
    require(
        layers == [1, 56, 1_764, 37_856, 575_407, 6_496_938, 57_232_105, 410_200_367, 2_474_264_653],
        "exact Hilbert layer counts through grade eight changed",
    )
    return {
        "numerator": numerator,
        "denominator_factors": {str(key): value for key, value in sorted(denominator_factors.items())},
        "exact_semigroup_layer_counts_through_grade_eight": {
            str(grade): count for grade, count in enumerate(layers)
        },
        "coefficient_expansion_recomputed_exactly": True,
    }


def audit_hilbert_basis(gen_path: Path, out_path: Path | None) -> dict[str, object]:
    rows, provenance = parse_normaliz_generators(gen_path)
    kernel = np.asarray(_primitive_left_kernel_rows(), dtype=np.int64)
    require(not np.any(kernel @ rows.T), "Hilbert generator escaped the exact Johnson kernel")
    masses = rows.sum(axis=1, dtype=np.int64)
    require(np.all(masses % 5 == 0), "Hilbert generator has nonintegral grade")
    grades = masses // 5
    grade_histogram = Counter(int(value) for value in grades)
    require(grade_histogram == Counter({1: 56, 2: 168, 3: 672}), "Hilbert grade census changed")
    by_grade = {grade: unique_rows(rows[grades == grade]) for grade in sorted(grade_histogram)}

    small = canonical_catalog(7, 4).astype(np.int64)
    medium = canonical_catalog(7, 8).astype(np.int64)
    require(not np.any(small % 2) and not np.any(medium % 2), "even canonical catalog changed parity")
    small_lifts = unique_rows(small // 2)
    medium_lifts = unique_rows(medium // 2)
    require(len(small_lifts) == 56 and len(medium_lifts) == 1_764, "known catalog count changed")
    require(np.array_equal(small_lifts, by_grade[1]), "degree-one Hilbert basis is not S56")

    decomposable_degree_two = pair_sum_catalog(by_grade[1])
    require(len(decomposable_degree_two) == 1_596, "degree-two S+S catalog count changed")
    require(
        len(unique_rows(np.vstack((decomposable_degree_two, by_grade[2]))))
        == len(decomposable_degree_two) + len(by_grade[2]),
        "primitive and decomposable degree-two rows overlap",
    )
    reconstructed_medium = unique_rows(np.vstack((decomposable_degree_two, by_grade[2])))
    require(np.array_equal(reconstructed_medium, medium_lifts), "Hilbert degree <=2 does not reconstruct M1764")

    triple_small = triple_sum_catalog(by_grade[1])
    small_plus_primitive_two = unique_rows(
        np.asarray(
            [small_row + primitive_row for small_row in by_grade[1] for primitive_row in by_grade[2]],
            dtype=np.int64,
        )
    )
    decomposable_degree_three = unique_rows(np.vstack((triple_small, small_plus_primitive_two)))
    decomposition_overlap = len(triple_small) + len(small_plus_primitive_two) - len(decomposable_degree_three)
    require(
        (len(triple_small), len(small_plus_primitive_two), decomposition_overlap)
        == (30_436, 8_428, 1_680),
        "degree-three decomposition census changed",
    )
    require(
        len(unique_rows(np.vstack((decomposable_degree_three, by_grade[3]))))
        == len(decomposable_degree_three) + len(by_grade[3])
        == 37_856,
        "primitive and decomposable degree-three rows do not form the complete layer",
    )

    normaliz_output = None
    hilbert_series = None
    if out_path is not None:
        raw_out = out_path.read_bytes()
        text = raw_out.decode("utf-8")
        for phrase in (
            "896 Hilbert basis elements",
            "56 lattice points in polytope (Hilbert basis elements of degree 1)",
            "with denominator = 5",
            "1:56  2:168  3:672",
        ):
            require(phrase in text, f"Normaliz output is missing audit phrase: {phrase}")
        normaliz_output = {
            "path": str(out_path.resolve()),
            "file_bytes": len(raw_out),
            "file_sha256": sha256_bytes(raw_out),
            "required_summary_lines_present": True,
        }
        hilbert_series = hilbert_layer_counts(text, 8)

    required_grades = required_z7_grade_audit()
    return {
        "experiment": "p7_infinity7_positive_z7_johnson_semigroup_hilbert_audit",
        "status": "complete_exact_hilbert_basis_generation_certificate",
        "semigroup": "{L in Z_{≥0}^35 : K L = 0}",
        "normaliz_generator_file": provenance,
        "normaliz_output_file": normaliz_output,
        "normaliz_hilbert_series": hilbert_series,
        "kernel_sha256_int64": sha256_bytes(np.ascontiguousarray(kernel).tobytes()),
        "hilbert_basis_sha256_int64_sorted": sha256_bytes(sorted_rows(rows).tobytes()),
        "hilbert_basis_grade_histogram": {
            str(grade): count for grade, count in sorted(grade_histogram.items())
        },
        "maximum_hilbert_generator_grade": int(grades.max()),
        "maximum_hilbert_generator_coordinate": int(rows.max()),
        "all_generators_nonnegative_exact_Johnson_functions": True,
        "small_catalog_identification": {
            "S56_rows": len(small_lifts),
            "S56_lift_sha256_int64_sorted": sha256_bytes(small_lifts.tobytes()),
            "equals_complete_degree_one_hilbert_basis": True,
        },
        "medium_catalog_identification": {
            "M1764_rows": len(medium_lifts),
            "decomposable_S_plus_S_rows": len(decomposable_degree_two),
            "primitive_degree_two_hilbert_rows": len(by_grade[2]),
            "primitive_and_decomposable_disjoint": True,
            "union_equals_complete_M1764": True,
            "M1764_lift_sha256_int64_sorted": sha256_bytes(medium_lifts.tobytes()),
        },
        "new_primitive_degree_three_family": {
            "rows": len(by_grade[3]),
            "sha256_int64_sorted": sha256_bytes(by_grade[3].tobytes()),
            "all_rows_have_total_lift_mass_15": bool(np.all(by_grade[3].sum(axis=1) == 15)),
            "triple_S_distinct_rows": len(triple_small),
            "S_plus_primitive_degree_two_distinct_rows": len(small_plus_primitive_two),
            "overlap_between_the_two_decomposable_families": decomposition_overlap,
            "decomposable_degree_three_rows": len(decomposable_degree_three),
            "complete_degree_three_rows_after_adding_primitives": 37_856,
        },
        "required_z7_grades": required_grades,
        "generation_consequence": {
            "every_nonnegative_integer_Johnson_excess_is_a_sum_of_the_896_rows": True,
            "no_primitive_generator_above_grade_three": True,
            "all_z7_high_catalog_grades_3_through_8_are_generated": True,
            "coordinate_cap_argument": (
                "For a target L with 0<=L_X<=6, every summand in any nonnegative "
                "Hilbert decomposition is coordinatewise <=L; hence every partial sum "
                "also obeys the cap."
            ),
            "coordinate_cap_preserved_automatically_by_nonnegative_decomposition": True,
            "all_896_generators_are_binary": True,
            "semigroup_layers_equal_capped_catalogs_automatically_through_grade_six": True,
            "grade_eight_requires_explicit_coordinate_cap_tracking_or_filtering": True,
            "uncapped_grade_eight_support_is_only_a_safe_necessary_superset": True,
        },
        "full_positive_z7_excluded": False,
    }


def build_input() -> tuple[bytes, dict[str, object]]:
    points, _monomials, evaluation, _left_kernel = johnson_space()
    kernel = np.asarray(_primitive_left_kernel_rows(), dtype=np.int64)
    require(len(points) == 35, "J(7,4) point count changed")
    require(evaluation.shape == (35, 29) and evaluation.rank() == 21, "Johnson rank changed")
    require(kernel.shape == (14, 35), "primitive Johnson kernel shape changed")
    require(not np.any(kernel @ np.asarray(evaluation.tolist(), dtype=np.int64)), "kernel is not exact")
    row_gcds = [int(np.gcd.reduce(np.abs(row))) for row in kernel]
    require(row_gcds == [1] * 14, "kernel row lost primitivity")

    lines = ["amb_space 35", "equations 14"]
    lines.extend(" ".join(str(int(value)) for value in row) for row in kernel)
    # Normaliz uses the nonnegative orthant by default for an equations-only
    # affine monoid.  The all-one grading records total excess mass.
    lines.extend(("grading", " ".join(["1"] * 35), "HilbertBasis", ""))
    encoded = "\n".join(lines).encode("ascii")
    return encoded, {
        "experiment": "p7_infinity7_positive_z7_johnson_semigroup_normaliz_input",
        "ambient_dimension": 35,
        "equation_count": 14,
        "degree_two_lattice_rank": 21,
        "grading": "total excess mass sum_X L(X)",
        "known_small_catalog_total_masses": {"S56": 5, "M1764": 10},
        "known_small_catalog_normalized_grades": {"S56": 1, "M1764": 2},
        "kernel_sha256_int64": sha256_bytes(np.ascontiguousarray(kernel).tobytes()),
        "normaliz_input_sha256": sha256_bytes(encoded),
        "all_kernel_rows_primitive": True,
        "exact_kernel_product_zero": True,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--metadata", type=Path)
    parser.add_argument("--normaliz-gen", type=Path)
    parser.add_argument("--normaliz-out", type=Path)
    parser.add_argument("--audit-output", type=Path)
    args = parser.parse_args()
    encoded, metadata = build_input()
    atomic_write(args.output, encoded)
    if args.metadata is not None:
        atomic_write(
            args.metadata,
            (json.dumps(metadata, indent=2, sort_keys=True) + "\n").encode("utf-8"),
        )
    if args.normaliz_gen is not None:
        require(args.audit_output is not None, "--normaliz-gen requires --audit-output")
        audit = audit_hilbert_basis(args.normaliz_gen, args.normaliz_out)
        atomic_write(
            args.audit_output,
            (json.dumps(audit, indent=2, sort_keys=True) + "\n").encode("utf-8"),
        )
        print(
            json.dumps(
                {
                    "status": audit["status"],
                    "audit_output": str(args.audit_output),
                    "hilbert_basis_grade_histogram": audit["hilbert_basis_grade_histogram"],
                    "maximum_required_high_grade": audit["required_z7_grades"]["maximum_required_high_grade"],
                },
                indent=2,
                sort_keys=True,
            )
        )
    print(json.dumps({**metadata, "output": str(args.output)}, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
