#!/usr/bin/env python3
"""Necessary mod-3/mod-7 affine-hull sieve for positive p=7, z=7.

This script reconstructs the two exact z=7 line orbits and all 2,160 exact
mean leaves.  It then applies both exhaustive pointed infinity-star branches:

* A: one line-star edge is present, normalized to (infinity, 0) = 1;
* B: all seven line-star edges vanish and one outside-star edge is present.

For every direction, an exact degree-two affine anchor with the prescribed
mean and parity is put into the right-hand side.  Every omitted catalog is
relaxed only to the anchor plus the complete degree-two, exact-zero-mean
space.  That space is generated by exact differences in the 56-row
``b=7, mean=4`` catalog and is independently proved to have the full expected
dimension modulo both 3 and 7.

Small and medium retained catalogs are enumerated once.  Their mod-3 and
mod-7 signatures are computed from the same catalog matrix in the same row
order and concatenated before joining, so a match cannot use one catalog row
modulo 3 and a different row modulo 7.  If there are more than two enumerable
directions, every retained pair is tested while all other variable directions
are relaxed to their affine hulls.

A zero-hit projection is a rigorous exclusion.  Passing is necessary only:
different retained-pair tests need not share a global catalog choice, affine
hulls can contain non-catalog points, and modular right-hand-side consistency
does not assert a binary edge lift.  Smoke mode rebuilds and audits the full
leaf universe but evaluates only a bounded representative subset and never
claims z=7 closure.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import sys
import time
from collections import Counter, OrderedDict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import p7_infinity7_positive_z7_mod7_projection as parent  # noqa: E402
import p7_infinity7_positive_z7_pointed_mod7 as pointed  # noqa: E402
from p7_infinity7_positive_z2_mod7_join import (  # noqa: E402
    DIRECTION_TYPES,
    POINT_INDEX,
    POINTS,
    canonical_catalog,
    mapped_catalog,
    matrix_sha256,
    modular_rank,
    modular_right_nullspace,
)
from p7_size_four_slack_classify import _primitive_left_kernel_rows  # noqa: E402
from p7_unsaturated_modular_catalog_filter import equation_matrix  # noqa: E402
from residual_boundary_four_lift_cpsat import geometry  # noqa: E402


P = 7
Q = P * P
EDGE_COUNT = 29
MODULI = (3, 7)
EXPECTED_LEAVES = 2_160
EXPECTED_POINTED_CASES = 2 * EXPECTED_LEAVES
EXPECTED_TRANSLATION_RANKS = {3: 161, 7: 146}
EXPECTED_FULL_RANKS = {3: 162, 7: 147}
EXPECTED_BRANCH_RANKS = {
    3: {"A": 162, "B": 169},
    7: {"A": 147, "B": 154},
}
EXPECTED_BRANCH_SHAPES = {"A": (282, 1_225), "B": (289, 1_225)}
EXPECTED_HULL_DIMENSION = 20
EXPECTED_HULL_CONDITIONED_DIMENSIONS = {
    3: {
        0: {120},
        1: {119},
        2: {118},
        3: {117},
        4: {116, 117},
        5: {115, 116},
        6: {114, 115},
        7: {114},
    },
    7: {
        0: {135},
        1: {127},
        2: {121},
        3: {117},
        4: {115},
        5: {114},
        6: {114},
        7: {114},
    },
}
CATALOG_SIGNATURE_CACHE_LIMIT = 32


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def json_sha256(value: object) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def independent_exact_rows(matrix: np.ndarray, modulus: int) -> tuple[np.ndarray, tuple[int, ...]]:
    """Select original rows forming a modular row basis, in source order."""
    source = np.asarray(matrix, dtype=np.int64)
    selected: list[np.ndarray] = []
    indices: list[int] = []
    rank = 0
    for index, row in enumerate(source):
        candidate = np.vstack((*selected, row)) if selected else row[None, :]
        candidate_rank = modular_rank(candidate, modulus)
        if candidate_rank > rank:
            selected.append(row.copy())
            indices.append(index)
            rank = candidate_rank
        if rank == EXPECTED_HULL_DIMENSION:
            break
    require(rank == EXPECTED_HULL_DIMENSION, f"mod-{modulus} hull basis lost rank")
    return np.ascontiguousarray(np.stack(selected), dtype=np.int64), tuple(indices)


def parity_for_mask(mask: int) -> np.ndarray:
    fibres = {index for index in range(P) if mask & (1 << index)}
    return np.asarray(
        [sum(value in fibres for value in point) & 1 for point in POINTS],
        dtype=np.int64,
    )


def map_canonical_row(mask: int, row: np.ndarray) -> np.ndarray:
    """Apply exactly the fibre-coordinate map used by ``mapped_catalog``."""
    fibres = {index for index in range(P) if mask & (1 << index)}
    b = len(fibres)
    actual_fibres = sorted(fibres)
    actual_complement = sorted(set(range(P)) - fibres)
    permutation = dict(zip(range(b), actual_fibres)) | dict(
        zip(range(b, P), actual_complement)
    )
    inverse = {target: source for source, target in permutation.items()}
    source_columns = [
        POINT_INDEX[tuple(sorted(inverse[value] for value in point))]
        for point in POINTS
    ]
    mapped = np.ascontiguousarray(np.asarray(row, dtype=np.int64)[source_columns])
    require(mapped.shape == (35,), "mapped affine anchor has wrong shape")
    return mapped


class AnchorFactory:
    """Construct and audit exact degree-two anchors for every leaf coset."""

    def __init__(self, kernel_rows: np.ndarray, hull_differences: np.ndarray):
        self.kernel_rows = np.asarray(kernel_rows, dtype=np.int64)
        self.hull_differences = np.asarray(hull_differences, dtype=np.int64)
        self.even_mean_eight = canonical_catalog(7, 8)[0].astype(np.int64)
        self.even_mean_four = canonical_catalog(7, 4)[0].astype(np.int64)
        self.one_odd_floor = canonical_catalog(1, 8)[0].astype(np.int64)
        self.cache: dict[tuple[int, int], np.ndarray] = {}

        for name, row, mean, b in (
            ("E8", self.even_mean_eight, 8, 7),
            ("E4", self.even_mean_four, 4, 7),
            ("P1", self.one_odd_floor, 8, 1),
        ):
            require(not np.any(self.kernel_rows @ row), f"anchor component {name} is not degree two")
            require(2 * int(row.sum()) == 5 * mean, f"anchor component {name} has wrong mean")
            require(
                np.array_equal(row % 2, parity_for_mask((1 << b) - 1)),
                f"anchor component {name} has wrong parity",
            )

    def canonical(self, b: int, mean: int) -> tuple[np.ndarray, str]:
        require(mean >= 0 and mean % 4 == 0, "scaled mean is outside the z=7 lattice")
        residue = mean % 8
        require(residue in (0, 4), "scaled mean residue is not zero or four")
        if b == 7:
            if residue == 0:
                multiplier = mean // 8
                row = multiplier * self.even_mean_eight
                formula = f"{multiplier}*E8"
            else:
                multiplier = (mean - 4) // 8
                require(multiplier >= 0, "negative b=7 anchor multiplier")
                row = self.even_mean_four + multiplier * self.even_mean_eight
                formula = f"E4+{multiplier}*E8"
        elif b == 1:
            if residue == 0:
                multiplier = (mean - 8) // 8
                require(multiplier >= 0, "b=1 mean lies below its parity floor")
                row = self.one_odd_floor + multiplier * self.even_mean_eight
                formula = f"P1+{multiplier}*E8"
            else:
                multiplier = (mean - 12) // 8
                require(multiplier >= 0, "b=1 residue-four mean lies below its parity floor")
                row = self.one_odd_floor + self.even_mean_four + multiplier * self.even_mean_eight
                formula = f"P1+E4+{multiplier}*E8"
        else:
            raise AssertionError(f"z=7 direction has unsupported b={b}")
        return np.ascontiguousarray(row, dtype=np.int64), formula

    def get(self, mask: int, mean: int) -> np.ndarray:
        key = (int(mask), int(mean))
        if key not in self.cache:
            b = int(mask).bit_count()
            canonical, _formula = self.canonical(b, int(mean))
            anchor = map_canonical_row(int(mask), canonical)
            require(not np.any(self.kernel_rows @ anchor), "mapped anchor is not exactly degree two")
            require(2 * int(anchor.sum()) == 5 * int(mean), "mapped anchor has wrong exact mean")
            require(
                np.array_equal(anchor % 2, parity_for_mask(int(mask))),
                "mapped anchor has wrong exact parity",
            )
            self.cache[key] = anchor
        return self.cache[key]

    def audit_universe(self, orbits: list[dict], leaves_by_orbit: list[list[dict]]) -> dict:
        uses: dict[tuple[int, int], dict] = {}
        for orbit_index, (orbit, leaves) in enumerate(zip(orbits, leaves_by_orbit)):
            for leaf in leaves:
                for direction, (mask, mean, catalog_class) in enumerate(
                    zip(orbit["masks"], leaf["scaled_means"], leaf["catalog_classes"])
                ):
                    key = (int(mask), int(mean))
                    row = uses.setdefault(
                        key,
                        {
                            "mask": int(mask),
                            "b": int(mask).bit_count(),
                            "scaled_mean": int(mean),
                            "catalog_classes": set(),
                            "directions": set(),
                            "orbit_indices": set(),
                            "occurrences": 0,
                        },
                    )
                    row["catalog_classes"].add(str(catalog_class))
                    row["directions"].add(direction)
                    row["orbit_indices"].add(orbit_index)
                    row["occurrences"] += 1

        audit_rows = []
        for key in sorted(uses):
            use = uses[key]
            mask, mean = key
            anchor = self.get(mask, mean)
            _canonical, formula = self.canonical(mask.bit_count(), mean)
            classes = tuple(sorted(use["catalog_classes"]))
            exact_catalog_checked = all(value != "H" for value in classes)
            anchor_catalog_index = None
            catalog_size = None
            if exact_catalog_checked:
                catalog = mapped_catalog(mask, mean).astype(np.int64)
                catalog_size = len(catalog)
                matches = np.flatnonzero(np.all(catalog == anchor[None, :], axis=1))
                require(len(matches) == 1, "small/medium/unique anchor is not an exact catalog row")
                anchor_catalog_index = int(matches[0])
                differences = catalog - anchor[None, :]
                require(not np.any(differences.sum(axis=1)), "catalog-anchor differences changed mean")
                require(not np.any(self.kernel_rows @ differences.T), "catalog-anchor difference left degree two")
                require(not np.any(differences % 2), "catalog-anchor difference changed parity")
                for modulus in MODULI:
                    require(
                        modular_rank(np.vstack((self.hull_differences, differences)), modulus)
                        == EXPECTED_HULL_DIMENSION,
                        f"exact catalog escaped the mod-{modulus} omitted hull",
                    )

            audit_rows.append(
                {
                    "mask": mask,
                    "b": mask.bit_count(),
                    "scaled_mean": mean,
                    "catalog_classes": list(classes),
                    "directions": sorted(use["directions"]),
                    "orbit_indices": sorted(use["orbit_indices"]),
                    "occurrences": int(use["occurrences"]),
                    "formula_in_canonical_fibre_coordinates": formula,
                    "anchor_minimum": int(anchor.min()),
                    "anchor_maximum": int(anchor.max()),
                    "anchor_sha256_int64": matrix_sha256(anchor[None, :]),
                    "exact_degree_two_kernel_audit": True,
                    "exact_scaled_mean_audit": True,
                    "exact_parity_audit": True,
                    "complete_catalog_checked": exact_catalog_checked,
                    "complete_catalog_size": catalog_size,
                    "anchor_catalog_index": anchor_catalog_index,
                }
            )

        require(sum(row["occurrences"] for row in audit_rows) == EXPECTED_LEAVES * 8, "anchor-use census changed")
        return {
            "unique_mask_mean_anchors": len(audit_rows),
            "direction_uses_across_all_2160_leaves": EXPECTED_LEAVES * 8,
            "component_definitions": {
                "E8": "first exact b=7, mean=8 catalog row",
                "E4": "first exact b=7, mean=4 catalog row",
                "P1": "unique exact b=1, mean=8 parity floor",
            },
            "anchors_need_not_obey_catalog_box_bounds": True,
            "anchors_define_affine_cosets_not_candidate_slacks": True,
            "all_anchors_exact_degree_two_mean_and_parity": True,
            "all_complete_U_S_M_catalogs_contained_in_their_anchor_hulls_mod_3_and_7": True,
            "rows": audit_rows,
        }


def build_hull_audit() -> tuple[np.ndarray, dict[int, np.ndarray], dict]:
    """Prove the exact catalog-difference span is the full safe modular hull."""
    kernel_rows = np.asarray(_primitive_left_kernel_rows(), dtype=np.int64)
    require(kernel_rows.shape == (14, 35), "primitive Johnson left-kernel shape changed")
    source_catalog = canonical_catalog(7, 4).astype(np.int64)
    require(source_catalog.shape == (56, 35), "hull source catalog changed")
    differences = np.ascontiguousarray(source_catalog[1:] - source_catalog[0], dtype=np.int64)
    require(not np.any(differences.sum(axis=1)), "hull source differences are not exact zero mean")
    require(not np.any(differences % 2), "hull source differences changed parity")
    require(not np.any(kernel_rows @ differences.T), "hull source escaped exact degree two")

    constraints = np.vstack((np.ones((1, 35), dtype=np.int64), kernel_rows))
    bases: dict[int, np.ndarray] = {}
    prime_rows = []
    for modulus in MODULI:
        nullspace, constraint_rank = modular_right_nullspace(constraints, modulus)
        difference_rank = modular_rank(differences, modulus)
        basis, basis_indices = independent_exact_rows(differences, modulus)
        require(constraint_rank == 15, f"mod-{modulus} degree-two/mean constraints lost rank")
        require(len(nullspace) == 20, f"mod-{modulus} degree-two zero-mean space changed dimension")
        require(difference_rank == EXPECTED_HULL_DIMENSION, f"mod-{modulus} catalog hull changed rank")
        require(modular_rank(nullspace, modulus) == EXPECTED_HULL_DIMENSION, "nullspace basis lost rank")
        require(
            modular_rank(np.vstack((differences, nullspace)), modulus) == EXPECTED_HULL_DIMENSION,
            f"mod-{modulus} catalog hull is not the full constrained nullspace",
        )
        require(not np.any(constraints @ basis.T % modulus), "selected hull basis violates constraints")
        bases[modulus] = basis
        prime_rows.append(
            {
                "modulus": modulus,
                "constraint_rank": int(constraint_rank),
                "constraint_nullity": len(nullspace),
                "all_55_exact_differences_rank": int(difference_rank),
                "selected_exact_basis_rank": modular_rank(basis, modulus),
                "selected_source_difference_indices": list(basis_indices),
                "selected_exact_basis_sha256_int64": matrix_sha256(basis),
                "constraint_nullspace_sha256_uint8": matrix_sha256(nullspace.astype(np.uint8)),
                "catalog_span_equals_full_degree_two_zero_mean_space": True,
            }
        )

    return kernel_rows, bases, {
        "johnson_slice_points": 35,
        "degree_at_most_two_rank_over_Q": 21,
        "primitive_left_kernel_rows": 14,
        "exact_zero_mean_dimension": EXPECTED_HULL_DIMENSION,
        "source": "all differences from the first row of the exact b=7, mean=4 catalog",
        "source_catalog_rows": len(source_catalog),
        "source_catalog_sha256_int16": matrix_sha256(source_catalog.astype(np.int16)),
        "all_difference_rows": len(differences),
        "all_differences_sha256_int64": matrix_sha256(differences),
        "all_differences_exact_zero_mean_even_and_degree_two": True,
        "prime_audits": prime_rows,
        "rigorous_containment_reason": (
            "Any two exact slacks with the same mean and parity have an exact-zero-mean "
            "degree-two difference.  Reduction modulo 3 or 7 lies in the audited 20-dimensional "
            "constraint nullspace, which equals the span of the exact catalog differences."
        ),
    }


def build_pointed_systems(
    orbits: list[dict], normalizations: list[dict]
) -> tuple[np.ndarray, list[dict[str, dict]], dict, list[dict]]:
    """Build both branch matrices and independent left-null bases at both primes."""
    full_matrix = equation_matrix()
    require(full_matrix.shape == (282, 1_225), "full exact edge system shape changed")
    require(np.all(full_matrix[0] == 1), "edge-count row changed")
    translation_matrix = np.ascontiguousarray(
        np.concatenate((full_matrix[:1], full_matrix[2:]), axis=0), dtype=np.int16
    )
    require(translation_matrix.shape == (281, 1_225), "translation matrix shape changed")

    translation_prime_audits = []
    for modulus in MODULI:
        full_rank = modular_rank(full_matrix, modulus)
        translation_rank = modular_rank(translation_matrix, modulus)
        require(full_rank == EXPECTED_FULL_RANKS[modulus], f"mod-{modulus} full rank changed")
        require(
            translation_rank == EXPECTED_TRANSLATION_RANKS[modulus],
            f"mod-{modulus} translation rank changed",
        )
        translation_prime_audits.append(
            {
                "modulus": modulus,
                "full_282_row_rank": full_rank,
                "translation_281_row_rank": translation_rank,
                "deleted_distinguished_edge_row_increases_rank_by_one": full_rank == translation_rank + 1,
            }
        )

    data = geometry(P, "affine")
    edges = tuple(tuple(int(value) for value in edge) for edge in data["edges"])
    edge_to_index = {edge: index for index, edge in enumerate(edges)}
    require(len(edges) == len(edge_to_index) == 1_225, "affine edge geometry changed")
    require(
        tuple(edges[edge_to_index[(0, u + 1)]] for u in range(Q))
        == tuple((0, u + 1) for u in range(Q)),
        "infinity-star edge indexing changed",
    )

    systems_by_orbit: list[dict[str, dict]] = []
    system_audits = []
    for orbit_index, (orbit, normalization) in enumerate(zip(orbits, normalizations)):
        line = tuple(int(value) for value in normalization["line"])
        outside = int(normalization["outside_representative"])
        require(tuple(orbit["representative"]) == line, "pointed normalization line changed")
        specs = {
            "A": ((0,), (1,)),
            "B": ((*line, outside), (*(0 for _ in line), 1)),
        }
        orbit_systems: dict[str, dict] = {}
        orbit_audit_rows = []
        for branch in ("A", "B"):
            finite_points, tail_rhs_values = specs[branch]
            require(len(finite_points) == len(tail_rhs_values), "fixed-edge row/RHS mismatch")
            require(len(set(finite_points)) == len(finite_points), "pointed branch repeats an edge")
            appended = np.stack(
                [pointed.edge_row(edge_to_index[(0, point + 1)], len(edges)) for point in finite_points]
            )
            matrix = np.ascontiguousarray(np.vstack((translation_matrix, appended)), dtype=np.int16)
            require(matrix.shape == EXPECTED_BRANCH_SHAPES[branch], f"branch {branch} shape changed")
            if branch == "A":
                require(np.array_equal(appended[0], full_matrix[1]), "branch A is not edge (infinity,0)=1")
            else:
                require(set(finite_points[:-1]) == set(line), "branch B missed a line-star edge")
                require(outside not in line, "branch B outside representative lies on the line")
                require(tuple(tail_rhs_values[:-1]) == (0,) * P, "branch B line RHS is not all zero")
                require(tail_rhs_values[-1] == 1, "branch B outside representative is not present")

            base_rhs = np.zeros(matrix.shape[0], dtype=np.int64)
            base_rhs[0] = EDGE_COUNT
            base_rhs[len(translation_matrix) :] = np.asarray(tail_rhs_values, dtype=np.int64)
            fixed_edge_rows = [
                {
                    "finite_field_point": int(point),
                    "graph_edge": [0, int(point) + 1],
                    "edge_variable_index": int(edge_to_index[(0, int(point) + 1)]),
                    "rhs": int(rhs),
                }
                for point, rhs in zip(finite_points, tail_rhs_values)
            ]

            modulus_data: dict[int, dict] = {}
            prime_audits = []
            calibration = (17 * np.arange(matrix.shape[1], dtype=np.int64) + 3) % 2
            for modulus in MODULI:
                dependencies, rank_from_nullspace = modular_right_nullspace(matrix.T, modulus)
                dependencies = np.ascontiguousarray(dependencies, dtype=np.int64)
                rank = modular_rank(matrix, modulus)
                expected_rank = EXPECTED_BRANCH_RANKS[modulus][branch]
                expected_dependencies = matrix.shape[0] - expected_rank
                require(rank == rank_from_nullspace == expected_rank, f"mod-{modulus} branch {branch} rank changed")
                require(
                    dependencies.shape == (expected_dependencies, matrix.shape[0]),
                    f"mod-{modulus} branch {branch} dependency shape changed",
                )
                require(
                    not np.any(dependencies @ (matrix.astype(np.int64) % modulus) % modulus),
                    f"mod-{modulus} branch {branch} left-null audit failed",
                )
                require(
                    rank - EXPECTED_TRANSLATION_RANKS[modulus] == len(finite_points),
                    f"mod-{modulus} branch {branch} fixed rows are not independent",
                )
                manufactured_rhs = matrix.astype(np.int64) @ calibration % modulus
                manufactured_syndrome = dependencies @ manufactured_rhs % modulus
                require(not np.any(manufactured_syndrome), "manufactured consistent RHS was rejected")
                modulus_data[modulus] = {
                    "dependencies": dependencies,
                    "rank": rank,
                }
                prime_audits.append(
                    {
                        "modulus": modulus,
                        "rank": rank,
                        "left_dependency_dimension": len(dependencies),
                        "left_null_audit": True,
                        "rank_increment_from_appended_rows": rank - EXPECTED_TRANSLATION_RANKS[modulus],
                        "dependency_sha256_uint8": matrix_sha256(dependencies.astype(np.uint8)),
                        "manufactured_binary_edge_vector_sha256_uint8": matrix_sha256(calibration[None, :].astype(np.uint8)),
                        "manufactured_rhs_sha256_uint8": matrix_sha256(manufactured_rhs[None, :].astype(np.uint8)),
                        "manufactured_witness_syndrome_is_zero": True,
                    }
                )

            system = {
                "orbit_index": orbit_index,
                "branch": branch,
                "matrix": matrix,
                "base_rhs": base_rhs,
                "fixed_edge_rows": fixed_edge_rows,
                "moduli": modulus_data,
            }
            orbit_systems[branch] = system
            orbit_audit_rows.append(
                {
                    "pointed_star_branch": branch,
                    "equations": int(matrix.shape[0]),
                    "edge_variables": int(matrix.shape[1]),
                    "translation_equivariant_prefix_rows": len(translation_matrix),
                    "appended_exact_edge_rows": len(appended),
                    "direction_block_offset": 1,
                    "direction_block_width": 35,
                    "edge_count_rhs": EDGE_COUNT,
                    "fixed_edge_rows": fixed_edge_rows,
                    "matrix_sha256_int16": matrix_sha256(matrix),
                    "base_rhs_sha256_int64": matrix_sha256(base_rhs[None, :]),
                    "prime_audits": prime_audits,
                }
            )
        systems_by_orbit.append(orbit_systems)
        system_audits.append(
            {
                "branch_orbit_index": orbit_index,
                "source_orbit_index": int(orbit["source_orbit_index"]),
                "systems": orbit_audit_rows,
            }
        )

    require(len(systems_by_orbit) == 2, "did not reconstruct both z=7 line systems")
    require(all(set(rows) == {"A", "B"} for rows in systems_by_orbit), "pointed branch missing")
    return translation_matrix, systems_by_orbit, {
        "equations": len(translation_matrix),
        "edge_variables": translation_matrix.shape[1],
        "construction": "full 282-row exact system with only hardcoded edge (infinity,0) row deleted",
        "matrix_sha256_int16": matrix_sha256(translation_matrix),
        "full_matrix_sha256_int16": matrix_sha256(full_matrix),
        "direction_block_offset": 1,
        "direction_block_width": 35,
        "prime_audits": translation_prime_audits,
    }, system_audits


class ModulusProjectionFactory:
    """Condition one pointed system by exact degree-two omitted-block hulls."""

    def __init__(self, system: dict, modulus: int, hull_basis: np.ndarray):
        self.system = system
        self.modulus = int(modulus)
        self.dependencies = np.asarray(system["moduli"][modulus]["dependencies"], dtype=np.int64)
        self.hull_basis = np.asarray(hull_basis, dtype=np.int64)
        self.conditioners: dict[tuple[int, ...], tuple[np.ndarray, dict]] = {}

    def direction_block(self, direction: int) -> np.ndarray:
        require(0 <= direction < 8, "bad direction index")
        return self.dependencies[:, 1 + 35 * direction : 1 + 35 * (direction + 1)]

    def conditioner(self, omitted: tuple[int, ...]) -> tuple[np.ndarray, dict]:
        omitted = tuple(sorted(int(value) for value in omitted))
        require(len(set(omitted)) == len(omitted), "omitted direction repeated")
        require(all(0 <= value < 8 for value in omitted), "omitted direction out of range")
        if omitted not in self.conditioners:
            dependency_dimension = len(self.dependencies)
            if omitted:
                images = [
                    self.direction_block(direction) @ (self.hull_basis.T % self.modulus)
                    % self.modulus
                    for direction in omitted
                ]
                hull_image = np.ascontiguousarray(np.concatenate(images, axis=1), dtype=np.int64)
                coefficients, image_rank = modular_right_nullspace(hull_image.T, self.modulus)
            else:
                hull_image = np.empty((dependency_dimension, 0), dtype=np.int64)
                coefficients = np.eye(dependency_dimension, dtype=np.int64)
                image_rank = 0
            coefficients = np.ascontiguousarray(coefficients, dtype=np.int64)
            dimension = len(coefficients)
            require(dimension == dependency_dimension - image_rank, "hull conditioner rank-nullity failed")
            expected = EXPECTED_HULL_CONDITIONED_DIMENSIONS[self.modulus].get(len(omitted))
            require(expected is not None and dimension in expected, "conditioned hull dimension changed")
            require(modular_rank(coefficients, self.modulus) == dimension, "conditioner lost row rank")
            if omitted:
                require(not np.any(coefficients @ hull_image % self.modulus), "conditioner missed omitted hull")
            conditioned_dependencies = coefficients @ self.dependencies % self.modulus
            require(
                modular_rank(conditioned_dependencies, self.modulus) == dimension,
                "conditioned left dependencies lost rank",
            )
            require(
                not np.any(
                    conditioned_dependencies
                    @ (self.system["matrix"].astype(np.int64) % self.modulus)
                    % self.modulus
                ),
                "conditioned rows left the pointed left nullspace",
            )
            metadata = {
                "omitted_directions": list(omitted),
                "omitted_direction_count": len(omitted),
                "exact_hull_basis_rows_per_direction": len(self.hull_basis),
                "concatenated_hull_columns": int(hull_image.shape[1]),
                "concatenated_hull_image_rank": int(image_rank),
                "conditioned_dependency_dimension": dimension,
                "allowed_dimensions_for_this_omitted_count": sorted(expected),
                "coefficient_sha256_int64": matrix_sha256(coefficients),
                "hull_image_sha256_int64": matrix_sha256(hull_image),
                "conditioned_dependencies_sha256_uint8": matrix_sha256(
                    conditioned_dependencies.astype(np.uint8)
                ),
                "rank_nullity_audit": True,
                "omitted_hull_annihilation_audit": True,
                "conditioned_left_null_audit": True,
            }
            self.conditioners[omitted] = coefficients, metadata
        return self.conditioners[omitted]

    def conditioned_direction_block(self, omitted: tuple[int, ...], direction: int) -> np.ndarray:
        coefficients, _metadata = self.conditioner(omitted)
        return np.ascontiguousarray(
            coefficients @ self.direction_block(direction) % self.modulus,
            dtype=np.int64,
        )

    def audit(self) -> dict:
        rows = [self.conditioners[key][1] for key in sorted(self.conditioners)]
        histogram = Counter(
            (row["omitted_direction_count"], row["conditioned_dependency_dimension"])
            for row in rows
        )
        return {
            "modulus": self.modulus,
            "unconditioned_dependency_dimension": len(self.dependencies),
            "conditioner_count": len(rows),
            "observed_dimension_histogram": {
                f"omit{count}_dim{dimension}": multiplicity
                for (count, dimension), multiplicity in sorted(histogram.items())
            },
            "allowed_dimensions_by_omitted_direction_count": {
                str(count): sorted(values)
                for count, values in EXPECTED_HULL_CONDITIONED_DIMENSIONS[self.modulus].items()
            },
            "all_conditioners_rank_nullity_annihilation_and_left_null_audited": True,
            "conditioners": rows,
        }


def signature_rows_key(rows: np.ndarray) -> np.ndarray:
    rows = np.ascontiguousarray(rows, dtype=np.uint8)
    require(rows.ndim == 2 and rows.shape[1] > 0, "joint signature rows have bad shape")
    return rows.view(np.dtype((np.void, rows.shape[1]))).reshape(-1)


def count_matching_rows(available: np.ndarray, needed: np.ndarray) -> int:
    available_keys, multiplicities = np.unique(signature_rows_key(available), return_counts=True)
    needed_keys = signature_rows_key(needed)
    positions = np.searchsorted(available_keys, needed_keys)
    valid_indices = np.flatnonzero(positions < len(available_keys))
    if not len(valid_indices):
        return 0
    equal = available_keys[positions[valid_indices]] == needed_keys[valid_indices]
    hits = valid_indices[equal]
    return int(np.sum(multiplicities[positions[hits]], dtype=np.int64))


def joint_projection_join(
    bases: dict[int, np.ndarray], contributions: tuple[np.ndarray, ...]
) -> tuple[int, dict]:
    """Join zero, one, or two catalogs in F_3^d3 x F_7^d7."""
    require(set(bases) == set(MODULI), "joint base is missing a modulus")
    dimensions = {modulus: len(np.asarray(bases[modulus])) for modulus in MODULI}
    require(all(value > 0 for value in dimensions.values()), "joint component has zero dimension")
    total_dimension = sum(dimensions.values())
    for contribution in contributions:
        require(
            contribution.ndim == 2 and contribution.shape[1] == total_dimension,
            "joint catalog signature shape changed",
        )
    require(len(contributions) <= 2, "joint projection retained more than two catalogs")

    d3 = dimensions[3]
    sizes = tuple(int(row.shape[0]) for row in contributions)
    if not contributions:
        count = int(all(not np.any(bases[modulus] % modulus) for modulus in MODULI))
    elif len(contributions) == 1:
        needed = np.concatenate(
            (
                (-bases[3].astype(np.int64) % 3),
                (-bases[7].astype(np.int64) % 7),
            )
        )[None, :]
        count = count_matching_rows(contributions[0], np.ascontiguousarray(needed, dtype=np.uint8))
    else:
        first, second = contributions
        if len(first) > len(second):
            first, second = second, first
        needed3 = (-bases[3][None, :].astype(np.int64) - second[:, :d3].astype(np.int64)) % 3
        needed7 = (-bases[7][None, :].astype(np.int64) - second[:, d3:].astype(np.int64)) % 7
        needed = np.ascontiguousarray(np.concatenate((needed3, needed7), axis=1), dtype=np.uint8)
        count = count_matching_rows(first, needed)

    combined_base = np.concatenate(
        (bases[3].astype(np.uint8), bases[7].astype(np.uint8))
    )[None, :]
    return count, {
        "retained_catalog_count": len(contributions),
        "catalog_sizes": list(sizes),
        "cartesian_catalog_tuples": math.prod(sizes) if sizes else 1,
        "matching_joint_projected_catalog_tuples": count,
        "mod3_conditioned_dimension": dimensions[3],
        "mod7_conditioned_dimension": dimensions[7],
        "concatenated_signature_dimension": total_dimension,
        "concatenated_base_sha256_uint8": matrix_sha256(combined_base),
        "signature_encoding": (
            f"{dimensions[3]} raw base-three bytes followed by "
            f"{dimensions[7]} raw base-seven bytes"
        ),
        "same_catalog_indices_used_in_both_moduli": True,
    }


def joint_join_self_audit() -> dict:
    """Exercise multiplicity, both join arities, and the cross-prime index trap."""

    def brute(bases: dict[int, np.ndarray], matrices: tuple[np.ndarray, ...]) -> int:
        d3 = len(bases[3])
        sizes = [len(matrix) for matrix in matrices]
        total = 0
        choices = itertools.product(*(range(size) for size in sizes)) if sizes else [()]
        for indices in choices:
            syndrome3 = bases[3].astype(np.int64).copy()
            syndrome7 = bases[7].astype(np.int64).copy()
            for matrix, index in zip(matrices, indices):
                syndrome3 += matrix[index, :d3]
                syndrome7 += matrix[index, d3:]
            total += int(not np.any(syndrome3 % 3) and not np.any(syndrome7 % 7))
        return total

    positive_cases = (
        (
            {3: np.asarray([1], dtype=np.uint8), 7: np.asarray([2], dtype=np.uint8)},
            (np.asarray([[2, 5], [2, 5], [1, 5]], dtype=np.uint8),),
        ),
        (
            {3: np.asarray([0], dtype=np.uint8), 7: np.asarray([0], dtype=np.uint8)},
            (
                np.asarray([[0, 0], [0, 0], [1, 2]], dtype=np.uint8),
                np.asarray([[0, 0], [2, 5]], dtype=np.uint8),
            ),
        ),
    )
    rows = []
    for bases, matrices in positive_cases:
        observed, metadata = joint_projection_join(bases, matrices)
        expected = brute(bases, matrices)
        require(observed == expected and observed > 0, "joint join failed positive brute-force audit")
        rows.append({"brute_force_count": expected, **metadata})
    require(rows[0]["matching_joint_projected_catalog_tuples"] == 2, "duplicate multiplicity audit changed")

    trap_bases = {3: np.asarray([0], dtype=np.uint8), 7: np.asarray([0], dtype=np.uint8)}
    trap_catalog = np.asarray([[0, 1], [1, 0]], dtype=np.uint8)
    trap_count, trap_metadata = joint_projection_join(trap_bases, (trap_catalog,))
    independent_mod3_hits = int(np.count_nonzero(trap_catalog[:, 0] == 0))
    independent_mod7_hits = int(np.count_nonzero(trap_catalog[:, 1] == 0))
    require(independent_mod3_hits > 0 and independent_mod7_hits > 0, "index trap lacks marginal hits")
    require(trap_count == brute(trap_bases, (trap_catalog,)) == 0, "cross-prime index trap false-positive")
    return {
        "passed": True,
        "positive_join_arities_exercised": [1, 2],
        "duplicate_signature_multiplicity_exercised": True,
        "positive_cases": rows,
        "same_index_false_positive_trap": {
            "independent_mod3_matching_indices": independent_mod3_hits,
            "independent_mod7_matching_indices": independent_mod7_hits,
            "joint_same_index_matches": trap_count,
            "independent_prime_search_would_be_unsound": True,
            **trap_metadata,
        },
    }


class JointProjectionFactory:
    """Pair mod-3/mod-7 projections while preserving exact catalog row identity."""

    def __init__(
        self,
        system: dict,
        hull_bases: dict[int, np.ndarray],
        anchors: AnchorFactory,
    ):
        self.system = system
        self.anchors = anchors
        self.primes = {
            modulus: ModulusProjectionFactory(system, modulus, hull_bases[modulus])
            for modulus in MODULI
        }
        self.signature_cache: OrderedDict[tuple, tuple[np.ndarray, str]] = OrderedDict()
        self.signature_audit_records: dict[tuple, dict] = {}

    def projected_bases(self, raw_syndromes: dict[int, np.ndarray], omitted: tuple[int, ...]) -> dict[int, np.ndarray]:
        rows = {}
        for modulus in MODULI:
            coefficients, _metadata = self.primes[modulus].conditioner(omitted)
            rows[modulus] = np.ascontiguousarray(
                coefficients @ raw_syndromes[modulus] % modulus,
                dtype=np.uint8,
            )
        return rows

    def catalog_signature(
        self, omitted: tuple[int, ...], direction: int, mask: int, mean: int
    ) -> tuple[np.ndarray, str]:
        key = (tuple(omitted), int(direction), int(mask), int(mean))
        if key in self.signature_cache:
            value = self.signature_cache.pop(key)
            self.signature_cache[key] = value
            return value

        # This single catalog matrix, and only this matrix, supplies row index i
        # to both modular components before they are concatenated.
        catalog = mapped_catalog(int(mask), int(mean)).astype(np.int64)
        anchor = self.anchors.get(int(mask), int(mean))
        delta = np.ascontiguousarray(anchor[None, :] - catalog, dtype=np.int64)
        require(not np.any(delta.sum(axis=1)), "retained catalog delta changed exact mean")
        require(not np.any(delta % 2), "retained catalog delta changed parity")

        component_rows = []
        component_dimensions = {}
        component_hashes = {}
        for modulus in MODULI:
            conditioned_block = self.primes[modulus].conditioned_direction_block(omitted, direction)
            signatures = conditioned_block @ (delta.T % modulus) % modulus
            signatures = np.ascontiguousarray(signatures.T, dtype=np.uint8)
            require(len(signatures) == len(catalog), "modular signature lost a catalog row")
            component_rows.append(signatures)
            component_dimensions[modulus] = signatures.shape[1]
            component_hashes[modulus] = matrix_sha256(signatures)
        combined = np.ascontiguousarray(np.concatenate(component_rows, axis=1), dtype=np.uint8)
        require(len(combined) == len(catalog), "joint signature lost same-index alignment")

        identifier = (
            f"omit-{','.join(map(str, omitted)) or 'none'}_d{direction}_mask{mask}_mean{mean}"
        )
        record = {
            "identifier": identifier,
            "omitted_directions": list(omitted),
            "direction": int(direction),
            "mask": int(mask),
            "scaled_mean": int(mean),
            "catalog_rows": len(catalog),
            "exact_catalog_sha256_int16": matrix_sha256(catalog.astype(np.int16)),
            "anchor_sha256_int64": matrix_sha256(anchor[None, :]),
            "delta_sha256_int64": matrix_sha256(delta),
            "component_dimensions": {str(key): value for key, value in component_dimensions.items()},
            "component_signature_sha256_uint8": {
                str(key): value for key, value in component_hashes.items()
            },
            "concatenated_signature_sha256_uint8": matrix_sha256(combined),
            "same_exact_catalog_matrix_and_row_indices_used_for_mod3_and_mod7": True,
        }
        prior = self.signature_audit_records.setdefault(key, record)
        require(prior == record, "recomputed joint signature audit changed")
        value = combined, identifier
        self.signature_cache[key] = value
        if len(self.signature_cache) > CATALOG_SIGNATURE_CACHE_LIMIT:
            self.signature_cache.popitem(last=False)
        return value

    def audit(self) -> dict:
        signature_rows = [self.signature_audit_records[key] for key in sorted(self.signature_audit_records)]
        return {
            "pointed_star_branch": self.system["branch"],
            "modulus_conditioners": [self.primes[modulus].audit() for modulus in MODULI],
            "catalog_signature_cache_limit": CATALOG_SIGNATURE_CACHE_LIMIT,
            "catalog_signature_cache_resident_entries": len(self.signature_cache),
            "unique_catalog_signatures_computed": len(signature_rows),
            "catalog_size_histogram": dict(
                sorted(Counter(row["catalog_rows"] for row in signature_rows).items())
            ),
            "all_signature_records_sha256": json_sha256(signature_rows),
            "all_signatures_use_one_shared_catalog_index_order_across_both_moduli": True,
        }


def anchor_rhs_and_raw_syndromes(
    orbit: dict, leaf: dict, system: dict, anchors: AnchorFactory
) -> tuple[np.ndarray, dict[int, np.ndarray]]:
    rhs = np.asarray(system["base_rhs"], dtype=np.int64).copy()
    for direction, (mask, mean) in enumerate(zip(orbit["masks"], leaf["scaled_means"])):
        anchor = anchors.get(int(mask), int(mean))
        block = slice(1 + 35 * direction, 1 + 35 * (direction + 1))
        rhs[block] = 13 - anchor
    raw = {}
    for modulus in MODULI:
        dependencies = system["moduli"][modulus]["dependencies"]
        raw[modulus] = np.ascontiguousarray(dependencies @ rhs % modulus, dtype=np.int64)
    return rhs, raw


def evaluate_case(
    orbit: dict,
    leaf: dict,
    system: dict,
    factory: JointProjectionFactory,
    anchors: AnchorFactory,
) -> dict:
    classes = tuple(leaf["catalog_classes"])
    high = tuple(int(value) for value in leaf["high_directions"])
    enumerated = tuple(int(value) for value in leaf["enumerated_directions"])
    require(all(classes[value] == "H" for value in high), "high direction classification changed")
    require(all(classes[value] in ("S", "M") for value in enumerated), "enumerated class changed")
    require(set(high).isdisjoint(enumerated), "high/enumerated directions overlap")

    anchor_rhs, raw_syndromes = anchor_rhs_and_raw_syndromes(orbit, leaf, system, anchors)
    plans = []
    for retained in parent.retained_sets(enumerated):
        retained = tuple(int(value) for value in retained)
        omitted = tuple(sorted(set(high) | (set(enumerated) - set(retained))))
        require(set(retained).isdisjoint(omitted), "retained and omitted directions overlap")
        require(
            set(high) | set(enumerated) == set(retained) | set(omitted),
            "variable direction coverage gap",
        )
        plans.append((retained, omitted))
    require(plans, "leaf generated no retained-pair plan")
    require(len(set(plans)) == len(plans), "retained-pair plan repeated")
    if len(enumerated) > 2:
        require(
            {retained for retained, _omitted in plans} == set(itertools.combinations(enumerated, 2)),
            "not every retained pair was planned",
        )
    else:
        require(len(plans) == 1 and plans[0][0] == enumerated, "small leaf did not retain every catalog")

    projection_rows = []
    for retained, omitted in plans:
        bases = factory.projected_bases(raw_syndromes, omitted)
        signed_catalogs = []
        signature_identifiers = []
        for direction in retained:
            signature, identifier = factory.catalog_signature(
                omitted,
                direction,
                int(orbit["masks"][direction]),
                int(leaf["scaled_means"][direction]),
            )
            signed_catalogs.append(signature)
            signature_identifiers.append(identifier)
        expected_sizes = tuple(56 if classes[direction] == "S" else 1_764 for direction in retained)
        require(
            tuple(len(row) for row in signed_catalogs) == expected_sizes,
            "retained complete catalog size changed",
        )
        count, join = joint_projection_join(bases, tuple(signed_catalogs))
        projection_rows.append(
            {
                "retained_directions": list(retained),
                "retained_catalog_classes": [classes[direction] for direction in retained],
                "omitted_directions": list(omitted),
                "omitted_catalog_classes": [classes[direction] for direction in omitted],
                "catalog_signature_identifiers": signature_identifiers,
                "zero_hit_rigorous_exclusion": count == 0,
                **join,
            }
        )

    require(len(projection_rows) == len(plans), "not all retained pairs were tested")
    failed_indices = [
        index
        for index, row in enumerate(projection_rows)
        if row["matching_joint_projected_catalog_tuples"] == 0
    ]
    return {
        "passes_all_necessary_projections": not failed_indices,
        "planned_projection_count": len(plans),
        "tested_projection_count": len(projection_rows),
        "all_planned_retained_pairs_tested": True,
        "failed_projection_indices": failed_indices,
        "first_failed_projection_index": failed_indices[0] if failed_indices else None,
        "anchor_rhs_sha256_int64": matrix_sha256(anchor_rhs[None, :]),
        "projections": projection_rows,
    }


def bounded_smoke_selection(leaves_by_orbit: list[list[dict]]) -> list[tuple[int, int]]:
    """Select one leaf per orbit/residue/join arity, never more than 24 leaves."""
    selected = []
    seen = set()
    for orbit_index, leaves in enumerate(leaves_by_orbit):
        for leaf_index, leaf in enumerate(leaves):
            arity = min(2, len(leaf["enumerated_directions"]))
            key = (orbit_index, leaf["residue_pair"], arity)
            if key not in seen:
                seen.add(key)
                selected.append((orbit_index, leaf_index))
    require(len(selected) <= 24, "smoke selection bound changed")
    require({orbit for orbit, _leaf in selected} == {0, 1}, "smoke selection misses an orbit")
    require(
        {min(2, len(leaves_by_orbit[orbit][leaf]["enumerated_directions"])) for orbit, leaf in selected}
        == {0, 1, 2},
        "smoke selection misses a join arity",
    )
    require(
        {leaves_by_orbit[orbit][leaf]["residue_pair"] for orbit, leaf in selected}
        == set(parent.EXPECTED_RESIDUES),
        "smoke selection misses a residue pair",
    )
    return selected


def render_case(
    orbit_index: int,
    leaf_index: int,
    branch: str,
    orbit: dict,
    leaf: dict,
    system: dict,
    decision: dict,
) -> dict:
    return {
        "case_key": f"orbit{orbit_index}_leaf{leaf_index}_branch{branch}",
        "branch_orbit_index": orbit_index,
        "source_orbit_index": int(orbit["source_orbit_index"]),
        "orbit_leaf_index": leaf_index,
        "orbit_size": int(orbit["size"]),
        "pointed_star_branch": branch,
        "representative_finite_field": list(orbit["representative"]),
        "fixed_edge_rows": system["fixed_edge_rows"],
        "residue_pair_minus_plus": leaf["residue_pair"],
        "q_values": list(leaf["q_values"]),
        "scaled_means": list(leaf["scaled_means"]),
        "catalog_levels": list(leaf["catalog_levels"]),
        "catalog_classes": list(leaf["catalog_classes"]),
        "catalog_pattern_H_S_M": list(leaf["pattern"]),
        "high_directions_relaxed_to_exact_affine_hulls": list(leaf["high_directions"]),
        "enumerated_directions": list(leaf["enumerated_directions"]),
        **decision,
    }


def run(smoke_test: bool = False) -> dict:
    started = time.time()
    require(Counter(DIRECTION_TYPES) == Counter({-1: 4, 1: 4}), "direction type census changed")

    orbits, orbit_source = parent.load_z7_orbits()
    leaves_by_orbit, leaf_audit = parent.exact_mean_leaves(orbits)
    require(len(orbits) == 2, "z=7 orbit count changed")
    require(sum(len(rows) for rows in leaves_by_orbit) == EXPECTED_LEAVES, "2,160-leaf reconstruction failed")
    require([len(rows) for rows in leaves_by_orbit] == [1_080, 1_080], "per-orbit leaf count changed")

    kernel_rows, hull_bases, hull_audit = build_hull_audit()
    anchors = AnchorFactory(kernel_rows, canonical_catalog(7, 4)[1:] - canonical_catalog(7, 4)[0])
    anchor_audit = anchors.audit_universe(orbits, leaves_by_orbit)
    catalog_audit = parent.catalog_audit()
    join_audit = joint_join_self_audit()

    normalizations, star_split_audit = pointed.stabilizer_and_star_audit(orbits, leaves_by_orbit)
    _translation_matrix, systems_by_orbit, translation_audit, system_audits = build_pointed_systems(
        orbits, normalizations
    )
    factories = [
        {
            branch: JointProjectionFactory(systems_by_orbit[orbit_index][branch], hull_bases, anchors)
            for branch in ("A", "B")
        }
        for orbit_index in range(2)
    ]

    selected = (
        bounded_smoke_selection(leaves_by_orbit)
        if smoke_test
        else [
            (orbit_index, leaf_index)
            for orbit_index, leaves in enumerate(leaves_by_orbit)
            for leaf_index in range(len(leaves))
        ]
    )
    require(len(set(selected)) == len(selected), "selected source leaf repeated")

    case_results = []
    case_keys = set()
    decision_digest = hashlib.sha256()
    source_residues: Counter[str] = Counter()
    pointed_residues: Counter[str] = Counter()
    source_patterns: Counter[tuple[int, int, int]] = Counter()
    branch_totals = {branch: Counter() for branch in ("A", "B")}
    per_orbit_branch = [
        {branch: Counter() for branch in ("A", "B")} for _orbit in range(2)
    ]
    projection_totals: Counter[str] = Counter()
    dimension_histogram: Counter[tuple[int, int, int]] = Counter()

    for orbit_index, leaf_index in selected:
        orbit = orbits[orbit_index]
        leaf = leaves_by_orbit[orbit_index][leaf_index]
        source_residues[leaf["residue_pair"]] += 1
        source_patterns[tuple(leaf["pattern"])] += 1
        for branch in ("A", "B"):
            case_key = (orbit_index, leaf_index, branch)
            require(case_key not in case_keys, "pointed case repeated")
            case_keys.add(case_key)
            system = systems_by_orbit[orbit_index][branch]
            decision = evaluate_case(
                orbit,
                leaf,
                system,
                factories[orbit_index][branch],
                anchors,
            )
            row = render_case(orbit_index, leaf_index, branch, orbit, leaf, system, decision)
            case_results.append(row)
            decision_digest.update(
                json.dumps(row, sort_keys=True, separators=(",", ":")).encode("utf-8")
            )
            decision_digest.update(b"\n")

            pointed_residues[leaf["residue_pair"]] += 1
            branch_totals[branch]["processed"] += 1
            per_orbit_branch[orbit_index][branch]["processed"] += 1
            outcome = "surviving" if decision["passes_all_necessary_projections"] else "rejected"
            branch_totals[branch][outcome] += 1
            per_orbit_branch[orbit_index][branch][outcome] += 1
            for projection in decision["projections"]:
                projection_totals["tested"] += 1
                projection_totals[
                    "zero_hit" if projection["zero_hit_rigorous_exclusion"] else "positive_hit"
                ] += 1
                dimension_histogram[
                    (
                        len(projection["omitted_directions"]),
                        int(projection["mod3_conditioned_dimension"]),
                        int(projection["mod7_conditioned_dimension"]),
                    )
                ] += 1

    source_processed = len(selected)
    pointed_processed = len(case_results)
    survivors = [row for row in case_results if row["passes_all_necessary_projections"]]
    rejected = pointed_processed - len(survivors)
    require(pointed_processed == 2 * source_processed, "A/B case coverage changed")
    require(pointed_processed == rejected + len(survivors), "decision census mismatch")
    require(projection_totals["tested"] == sum(row["tested_projection_count"] for row in case_results), "projection census mismatch")
    require(
        all(rows["processed"] == rows["rejected"] + rows["surviving"] for rows in branch_totals.values()),
        "per-branch decision census mismatch",
    )

    full_run = not smoke_test
    if full_run:
        require(source_processed == EXPECTED_LEAVES, "full run did not test all 2,160 leaves")
        require(pointed_processed == EXPECTED_POINTED_CASES, "full run did not test both pointed branches")
        require(dict(sorted(source_residues.items())) == parent.EXPECTED_RESIDUES, "full residue census changed")
        require(
            dict(sorted(pointed_residues.items()))
            == {key: 2 * value for key, value in parent.EXPECTED_RESIDUES.items()},
            "full pointed residue census changed",
        )
        require(
            all(per_orbit_branch[orbit][branch]["processed"] == 1_080 for orbit in range(2) for branch in ("A", "B")),
            "full run missed an orbit/branch leaf",
        )
        require(len(case_keys) == EXPECTED_POINTED_CASES, "full case-key census changed")

    excluded = full_run and not survivors
    factory_audits = [
        {
            "branch_orbit_index": orbit_index,
            "source_orbit_index": int(orbits[orbit_index]["source_orbit_index"]),
            "branches": [factories[orbit_index][branch].audit() for branch in ("A", "B")],
        }
        for orbit_index in range(2)
    ]
    survivor_keys = [row["case_key"] for row in survivors]

    return {
        "experiment": "p7_infinity7_positive_z7_pointed_affine_hull_multimod",
        "status": (
            "complete_rigorous_pointed_mod3_mod7_affine_hull_exclusion"
            if excluded
            else "complete_rigorous_pointed_mod3_mod7_affine_hull_necessary_sieve_with_survivors"
            if full_run
            else "bounded_smoke_test_only"
        ),
        "p": P,
        "c_H": 1,
        "infinity_in_boundary": True,
        "finite_boundary_points": P,
        "z": 7,
        "phase": 0,
        "moduli": list(MODULI),
        "orbit_source": orbit_source,
        "mean_leaf_coverage": leaf_audit,
        "catalog_row_counts": catalog_audit,
        "degree_two_zero_mean_hull_audit": hull_audit,
        "exact_anchor_audit": anchor_audit,
        "joint_join_self_audit": join_audit,
        "translation_equivariant_linear_system": translation_audit,
        "pointed_linear_systems": system_audits,
        "pointed_star_split_audit": star_split_audit,
        "projection_factory_audits": factory_audits,
        "method": {
            "branch_A": "append exact edge x_(infinity,0)=1 after stabilizer normalization",
            "branch_B": "append seven exact line-star zeros and one normalized outside-star one",
            "anchor": "exact degree-two vector with the leaf's exact mean and parity; it defines an affine coset and need not be an admissible catalog row",
            "omitted_catalog": "relax to anchor plus the full degree-two exact-zero-mean space modulo each prime",
            "retained_catalog": "enumerate one complete U/S/M catalog matrix and project every row at both primes",
            "cross_prime_consistency": "concatenate mod-3 then mod-7 signatures for the same retained catalog row index before joining",
            "more_than_two_enumerated_directions": "test every retained pair; relax every other variable direction to its affine hull",
            "at_most_two_enumerated_directions": "retain all enumerable directions; relax only high directions",
            "rejection": "one zero-hit necessary projection rigorously excludes that pointed leaf",
            "passing": "passed every planned relaxation; necessary only and not a binary edge lift",
        },
        "logical_semantics": {
            "all_2160_exact_mean_leaves_reconstructed_before_selection": True,
            "both_pointed_branches_are_disjoint_and_exhaustive_for_nonempty_stars": True,
            "all_planned_retained_pairs_are_tested_even_after_an_earlier_zero_hit": True,
            "same_retained_catalog_indices_are_used_modulo_3_and_7": True,
            "zero_hit_affine_hull_projection_is_rigorous_exclusion": True,
            "affine_hull_passing_is_exact_catalog_tuple_feasibility": False,
            "all_pair_tests_share_one_global_catalog_assignment": False,
            "modular_passing_is_binary_edge_feasibility": False,
            "exact_edge_lift_claimed": False,
            "smoke_run_can_claim_z7_exclusion": False,
        },
        "smoke_test": smoke_test,
        "smoke_selection_bound": 24 if smoke_test else None,
        "smoke_limitations": (
            "Reconstructs and audits all 2,160 leaves, then evaluates one deterministic leaf per available orbit/residue/join-arity class in both branches. It cannot close z=7."
            if smoke_test
            else None
        ),
        "full_run": full_run,
        "full_source_exact_mean_leaves": EXPECTED_LEAVES,
        "processed_source_exact_mean_leaves": source_processed,
        "full_pointed_branch_cases": EXPECTED_POINTED_CASES,
        "processed_pointed_branch_cases": pointed_processed,
        "rejected_pointed_branch_cases": rejected,
        "surviving_pointed_branch_cases": len(survivors),
        "processed_source_residue_pair_histogram": dict(sorted(source_residues.items())),
        "processed_pointed_residue_pair_histogram": dict(sorted(pointed_residues.items())),
        "processed_source_pattern_histogram": {
            f"H{h}_S{s}_M{m}": count for (h, s, m), count in sorted(source_patterns.items())
        },
        "projection_test_census": dict(sorted(projection_totals.items())),
        "conditioned_dimension_histogram": {
            f"omit{omitted}_mod3dim{d3}_mod7dim{d7}": count
            for (omitted, d3, d7), count in sorted(dimension_histogram.items())
        },
        "per_branch_summary": [
            {
                "pointed_star_branch": branch,
                "processed_cases": rows["processed"],
                "rejected_cases": rows["rejected"],
                "surviving_cases": rows["surviving"],
            }
            for branch, rows in branch_totals.items()
        ],
        "per_orbit_branch_summary": [
            {
                "branch_orbit_index": orbit_index,
                "source_orbit_index": int(orbits[orbit_index]["source_orbit_index"]),
                "orbit_size": int(orbits[orbit_index]["size"]),
                "branches": [
                    {
                        "pointed_star_branch": branch,
                        "processed_cases": per_orbit_branch[orbit_index][branch]["processed"],
                        "rejected_cases": per_orbit_branch[orbit_index][branch]["rejected"],
                        "surviving_cases": per_orbit_branch[orbit_index][branch]["surviving"],
                    }
                    for branch in ("A", "B")
                ],
            }
            for orbit_index in range(2)
        ],
        "all_case_results_sha256": decision_digest.hexdigest(),
        "survivor_case_keys_sha256": json_sha256(survivor_keys),
        "survivor_case_keys": survivor_keys,
        "case_results": case_results,
        "z7_branch_excluded": excluded,
        "elapsed_seconds": time.time() - started,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--smoke",
        "--smoke-test",
        dest="smoke_test",
        action="store_true",
        help="evaluate a bounded representative subset after reconstructing all leaves",
    )
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()
    result = run(smoke_test=args.smoke_test)
    pointed.atomic_write(args.output, result)
    if not args.quiet:
        summary = {
            "experiment": result["experiment"],
            "status": result["status"],
            "processed_source_exact_mean_leaves": result["processed_source_exact_mean_leaves"],
            "processed_pointed_branch_cases": result["processed_pointed_branch_cases"],
            "rejected_pointed_branch_cases": result["rejected_pointed_branch_cases"],
            "surviving_pointed_branch_cases": result["surviving_pointed_branch_cases"],
            "projection_test_census": result["projection_test_census"],
            "z7_branch_excluded": result["z7_branch_excluded"],
            "output": str(args.output),
            "elapsed_seconds": result["elapsed_seconds"],
        }
        print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
