\\ Restrict the half-cusp scalar space by the remaining geometric cusp gaps.
default(parisize, 8G);
scalar_cache = getenv("P11_SCALAR_CACHE");
multicusp_cache = getenv("P11_MULTICUSP_CACHE");
output_directory = getenv("P11_MULTICUSP_REDUCED_OUTPUT_DIRECTORY");
if(type(scalar_cache) != "t_STR", error("missing P11_SCALAR_CACHE"));
if(type(multicusp_cache) != "t_STR", error("missing P11_MULTICUSP_CACHE"));
if(type(output_directory) != "t_STR", error("missing P11_MULTICUSP_REDUCED_OUTPUT_DIRECTORY"));
X = read(scalar_cache);
mf = X[1];
K0 = X[2];
Ctarget0 = X[5];
Y = read(multicusp_cache);
G = Y[7];
if(matsize(G)[2] != matsize(K0)[2], error("multicusp gap width mismatch"));
gap_rank = matrank(G);
J = matker(G);
Kgap = K0 * J;

S = mfsturm(mf);
E = 400;
gettime();
Qgap = mfcoefs(mf, E) * Kgap;
print("COEFFICIENT_MS=", gettime());
Qsturm = vecextract(Qgap, Str("1..", S + 1), Str("1..", matsize(Qgap)[2]));
idx = matindexrank(Qsturm);
RI = idx[1];
CJ = idx[2];
D = matsize(J)[2];
if(#RI != D || #CJ != D, error("multicusp scalar space lacks full Sturm rank"));
R = vecextract(Qsturm, RI, CJ);
T = vecextract(J, Str("1..", matsize(J)[1]), CJ) * R^-1;
K = K0 * T;
Q = mfcoefs(mf, E) * K;
if(G * T != matrix(matsize(G)[1], D), error("multicusp kernel reduction failed"));
if(vecextract(Q, RI, Str("1..", D)) != matid(D), error("multicusp pivot normalization failed"));
Ctarget = Ctarget0 * T;

cache = Str(output_directory, "/p11_scalar_multicusp_support400_mf_k_reduced_v1_20260828.gpbin");
system(Str("rm -f -- ", cache));
writebin(cache, [mf, K, RI, E, Ctarget]);
path = Str(output_directory, "/p11_scalar_multicusp_support400_qrows_exact400_v1_20260828.txt");
system(Str("rm -f -- ", path));
for(i = 1, E + 1, write(path, Q[i,]));
target_path = Str(output_directory, "/p11_scalar_multicusp_target_exact_v1_20260828.txt");
system(Str("rm -f -- ", target_path));
for(i = 1, matsize(Ctarget)[1], write(target_path, Ctarget[i,]));
print("MULTICUSP_GAP_RANK=", gap_rank);
print("REDUCED_DIMENSION=", D);
print("PIVOT_INDICES=", RI);
print("CACHE_WRITTEN=", cache);
print("QROWS_WRITTEN=", path);
print("TARGET_ROWS_WRITTEN=", target_path);
quit;
