#!/usr/bin/env python3
"""Exact finite probes for the residual-(ii) affine/Johnson obstruction.

This differs from ``leftover_minus_slice_milp.py`` in one essential way:
it imposes the full freeness condition on the distinguished edge e=(0,1).
For even scores this is

    Max+: f_e=-1 => S_G >= 4,  f_e=+1 => S_G >= 2,
    Max-: f_e=-1 => S_G <=-2,  f_e=+1 => S_G <=-4.

The ``affine`` mode uses only the explicit one-dimensional affine
halfspaces.  Their restrictions are degree-two Johnson polynomials.  The
``full`` mode uses the complete cached Max+ and Max- shells.  These are
finite diagnostics, not an all-prime proof.
"""
from __future__ import annotations

import argparse
import itertools
import json
import sys
import time
from pathlib import Path

import numpy as np
from scipy.optimize import Bounds, LinearConstraint, milp
from scipy.sparse import csr_matrix, vstack

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from e1_gmin_m4_prop15598 import field_ctx  # noqa: E402
from minmax_quadratic import paley_conference_prime_power  # noqa: E402


DEFAULT_PLUS = {5: Path("/tmp/maxplus_p5.npy"), 7: Path("/tmp/maxplus_p7.npy")}
DEFAULT_MINUS = {5: Path("/tmp/maxminus_p5.npy"), 7: Path("/tmp/maxminus_p7.npy")}


def feature_rows(
    Y: np.ndarray, C: np.ndarray
) -> tuple[list[tuple[int, int]], np.ndarray]:
    n = C.shape[0]
    edges = [(a, b) for a in range(n) for b in range(a + 1, n)]
    left = np.fromiter((a for a, _b in edges), dtype=np.int32)
    right = np.fromiter((b for _a, b in edges), dtype=np.int32)
    signs = C[left, right].astype(np.int8)
    F = (Y[:, left] * Y[:, right] * signs).astype(np.int8)
    return edges, F


def unique_rows(F: np.ndarray) -> np.ndarray:
    return np.unique(np.ascontiguousarray(F), axis=0)


def affine_shell(p: int, eigen_sign: int, C: np.ndarray) -> np.ndarray:
    """All 1D affine halfspaces in the requested +/- Paley eigenshell."""
    if eigen_sign not in (-1, 1):
        raise ValueError("eigen_sign must be +/-1")
    q = p * p
    m = (p + 1) // 2
    _q, _mul, _add, chi, _frob, _norm, _ia, _ib = field_ctx(p)
    functionals = [(1, t) for t in range(p)] + [(0, 1)]
    rows: list[np.ndarray] = []
    for r, s in functionals:
        # Kernel of r*a+s*b is generated by (a,b)=(s,-r).
        kernel_generator = (s % p) + ((-r) % p) * p
        if chi(kernel_generator) != eigen_sign:
            continue
        values = np.fromiter(
            ((r * (x % p) + s * (x // p)) % p for x in range(q)),
            dtype=np.int16,
            count=q,
        )
        for chosen in itertools.combinations(range(p), m):
            selected = np.zeros(p, dtype=np.int8)
            selected[list(chosen)] = 1
            y = np.empty(q + 1, dtype=np.int8)
            y[0] = eigen_sign
            y[1:] = 2 * selected[values] - 1
            rows.append(y)
    Y = np.unique(np.stack(rows), axis=0)
    target = eigen_sign * p * Y.astype(np.int16)
    if not np.array_equal(Y.astype(np.int16) @ C.astype(np.int16), target):
        raise RuntimeError("affine family failed the exact eigenspace check")
    return Y


def add_score_rows(
    blocks: list[csr_matrix],
    lower: list[float],
    upper: list[float],
    F: np.ndarray,
    fe: np.ndarray,
    shell: str,
) -> None:
    """Add the exact two-sided freeness thresholds, grouped by f_e."""
    for sign in (-1, 1):
        part = unique_rows(F[fe == sign])
        blocks.append(csr_matrix(part.astype(np.float64)))
        if shell == "plus":
            bound = 4.0 if sign == -1 else 2.0
            lower.extend([bound] * len(part))
            upper.extend([np.inf] * len(part))
        elif shell == "minus":
            bound = -2.0 if sign == -1 else -4.0
            lower.extend([-np.inf] * len(part))
            upper.extend([bound] * len(part))
        else:
            raise ValueError(shell)


def solve_cpsat(
    p: int,
    mode: str,
    Yp: np.ndarray,
    Ym: np.ndarray,
    C: np.ndarray,
    time_limit: float,
    workers: int,
) -> dict:
    """CP-SAT form using cardinality cuts instead of dense +/-1 rows."""
    from ortools.sat.python import cp_model

    t0 = time.time()
    edges, Fp = feature_rows(Yp, C)
    edges_m, Fm = feature_rows(Ym, C)
    if edges_m != edges:
        raise RuntimeError("edge orders differ")
    ei = edges.index((0, 1))
    k = 4 * p

    model = cp_model.CpModel()
    x = [model.new_bool_var(f"e_{a}_{b}") for a, b in edges]
    model.add(sum(x) == k)
    model.add(x[ei] == 0)

    n_score_constraints = 0
    for F, shell in ((Fp, "plus"), (Fm, "minus")):
        fe = F[:, ei]
        for sign in (-1, 1):
            part = unique_rows(F[fe == sign])
            for row in part:
                if shell == "plus":
                    bound = 4 if sign == -1 else 2
                    # S=k-2*n_negative >= bound.
                    indices = np.flatnonzero(row < 0).tolist()
                    model.add(sum(x[j] for j in indices) <= (k - bound) // 2)
                else:
                    bound = -2 if sign == -1 else -4
                    # S=2*n_positive-k <= bound.
                    indices = np.flatnonzero(row > 0).tolist()
                    model.add(sum(x[j] for j in indices) <= (k + bound) // 2)
                n_score_constraints += 1

    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = float(time_limit)
    solver.parameters.num_search_workers = int(workers)
    solver.parameters.random_seed = 628
    solver.parameters.cp_model_presolve = True
    solver.parameters.symmetry_level = 2
    status = solver.solve(model)
    status_name = solver.status_name(status)
    out = {
        "p": p,
        "mode": mode,
        "backend": "cp-sat",
        "relaxation": False,
        "workers": workers,
        "n_plus_points": int(len(Yp)),
        "n_minus_points": int(len(Ym)),
        "n_variables": len(edges),
        "n_constraints": n_score_constraints + 2,
        "status": int(status),
        "status_name": status_name,
        "success": status in (cp_model.OPTIMAL, cp_model.FEASIBLE),
        "conflicts": int(solver.num_conflicts),
        "branches": int(solver.num_branches),
        "wall_time": float(solver.wall_time),
        "seconds": round(time.time() - t0, 3),
    }
    if status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        xi = np.fromiter((solver.value(v) for v in x), dtype=np.int8)
        out["chosen_edges"] = [list(edge) for edge, bit in zip(edges, xi) if bit]
        out["plus_scores"] = sorted({int(v) for v in (Fp @ xi).tolist()})
        out["minus_scores"] = sorted({int(v) for v in (Fm @ xi).tolist()})
    return out


def solve_cpsat_cutting_plane(
    p: int,
    mode: str,
    Yp: np.ndarray,
    Ym: np.ndarray,
    C: np.ndarray,
    time_limit: float,
    workers: int,
    cut_batch: int,
    round_limit: float,
) -> dict:
    """Exact CP-SAT separation loop seeded by the affine Johnson family.

    Every added row is a genuine full-shell constraint.  Consequently an
    INFEASIBLE status in any round certifies the complete finite model, even
    though most redundant shell rows were never materialized in CP-SAT.
    """
    from ortools.sat.python import cp_model

    t0 = time.time()
    if mode != "full":
        raise ValueError("cp-sat-cut is intended for --mode full")
    edges, Fp = feature_rows(Yp, C)
    edges_m, Fm = feature_rows(Ym, C)
    if edges_m != edges:
        raise RuntimeError("edge orders differ")
    ei = edges.index((0, 1))
    k = 4 * p

    model = cp_model.CpModel()
    x = [model.new_bool_var(f"e_{a}_{b}") for a, b in edges]
    model.add(sum(x) == k)
    model.add(x[ei] == 0)
    added: set[tuple[str, bytes]] = set()

    def add_cut(shell: str, row: np.ndarray) -> bool:
        key = (shell, row.tobytes())
        if key in added:
            return False
        sign = int(row[ei])
        if shell == "plus":
            bound = 4 if sign == -1 else 2
            indices = np.flatnonzero(row < 0).tolist()
            model.add(sum(x[j] for j in indices) <= (k - bound) // 2)
        elif shell == "minus":
            bound = -2 if sign == -1 else -4
            indices = np.flatnonzero(row > 0).tolist()
            model.add(sum(x[j] for j in indices) <= (k + bound) // 2)
        else:
            raise ValueError(shell)
        added.add(key)
        return True

    # The exact degree-two Johnson core.
    for shell, eigen_sign in (("plus", 1), ("minus", -1)):
        Ya = affine_shell(p, eigen_sign, C)
        edges_a, Fa = feature_rows(Ya, C)
        if edges_a != edges:
            raise RuntimeError("affine/full edge orders differ")
        for row in unique_rows(Fa):
            add_cut(shell, row)

    fep = Fp[:, ei]
    fem = Fm[:, ei]
    plus_bound = np.where(fep == -1, 4, 2).astype(np.int16)
    minus_bound = np.where(fem == -1, -2, -4).astype(np.int16)
    rounds: list[dict] = []
    final_status = "UNKNOWN"
    final_x: np.ndarray | None = None

    while time.time() - t0 < time_limit:
        remaining = time_limit - (time.time() - t0)
        solver = cp_model.CpSolver()
        solver.parameters.max_time_in_seconds = min(float(round_limit), remaining)
        solver.parameters.num_search_workers = int(workers)
        solver.parameters.random_seed = 628 + len(rounds)
        solver.parameters.cp_model_presolve = True
        solver.parameters.symmetry_level = 2
        status = solver.solve(model)
        status_name = solver.status_name(status)
        rec = {
            "round": len(rounds) + 1,
            "status": status_name,
            "cuts_before": len(added),
            "conflicts": int(solver.num_conflicts),
            "branches": int(solver.num_branches),
            "wall_time": float(solver.wall_time),
        }
        rounds.append(rec)
        if status == cp_model.INFEASIBLE:
            final_status = "INFEASIBLE"
            break
        if status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
            final_status = status_name
            break

        xi = np.fromiter((solver.value(v) for v in x), dtype=np.int8)
        Sp = Fp.astype(np.int16) @ xi.astype(np.int16)
        Sm = Fm.astype(np.int16) @ xi.astype(np.int16)
        vp = np.flatnonzero(Sp < plus_bound)
        vm = np.flatnonzero(Sm > minus_bound)
        rec["violated_plus_points"] = int(len(vp))
        rec["violated_minus_points"] = int(len(vm))
        rec["min_plus_margin"] = int(np.min(Sp - plus_bound))
        rec["min_minus_margin"] = int(np.min(minus_bound - Sm))
        if len(vp) == 0 and len(vm) == 0:
            final_status = "FEASIBLE_FULL"
            final_x = xi
            break

        candidates: list[tuple[int, str, np.ndarray]] = []
        candidates.extend(
            (int(plus_bound[i] - Sp[i]), "plus", Fp[i]) for i in vp
        )
        candidates.extend(
            (int(Sm[i] - minus_bound[i]), "minus", Fm[i]) for i in vm
        )
        candidates.sort(key=lambda item: item[0], reverse=True)
        n_new = 0
        for _severity, shell, row in candidates:
            if add_cut(shell, row):
                n_new += 1
                if n_new >= cut_batch:
                    break
        rec["cuts_added"] = n_new
        if n_new == 0:
            final_status = "SEPARATION_STALLED"
            break

    out = {
        "p": p,
        "mode": mode,
        "backend": "cp-sat-cut",
        "relaxation": False,
        "workers": workers,
        "cut_batch": cut_batch,
        "round_limit": round_limit,
        "n_plus_points": int(len(Yp)),
        "n_minus_points": int(len(Ym)),
        "n_variables": len(edges),
        "n_cuts_final": len(added),
        "status_name": final_status,
        "success": final_status == "FEASIBLE_FULL",
        "finite_infeasibility_certificate": final_status == "INFEASIBLE",
        "rounds": rounds,
        "seconds": round(time.time() - t0, 3),
    }
    if final_x is not None:
        out["chosen_edges"] = [
            list(edge) for edge, bit in zip(edges, final_x) if bit
        ]
        out["plus_scores"] = sorted({int(v) for v in (Fp @ final_x).tolist()})
        out["minus_scores"] = sorted({int(v) for v in (Fm @ final_x).tolist()})
    return out


def solve_scip(
    p: int,
    mode: str,
    Yp: np.ndarray,
    Ym: np.ndarray,
    C: np.ndarray,
    time_limit: float,
    workers: int,
) -> dict:
    """SCIP feasibility model in sparse cardinality-cut form."""
    from pyscipopt import Model, SCIP_PARAMSETTING, quicksum

    t0 = time.time()
    edges, Fp = feature_rows(Yp, C)
    edges_m, Fm = feature_rows(Ym, C)
    if edges_m != edges:
        raise RuntimeError("edge orders differ")
    ei = edges.index((0, 1))
    k = 4 * p
    model = Model(f"residual_affine_p{p}_{mode}")
    model.hideOutput(True)
    model.setRealParam("limits/time", float(time_limit))
    model.setIntParam("parallel/maxnthreads", int(max(1, workers)))
    model.setHeuristics(SCIP_PARAMSETTING.AGGRESSIVE)
    x = [model.addVar(vtype="B", name=f"e_{a}_{b}") for a, b in edges]
    model.addCons(quicksum(x) == k)
    model.addCons(x[ei] == 0)
    n_score_constraints = 0
    for F, shell in ((Fp, "plus"), (Fm, "minus")):
        fe = F[:, ei]
        for sign in (-1, 1):
            part = unique_rows(F[fe == sign])
            for row in part:
                if shell == "plus":
                    bound = 4 if sign == -1 else 2
                    indices = np.flatnonzero(row < 0).tolist()
                    cap = (k - bound) // 2
                else:
                    bound = -2 if sign == -1 else -4
                    indices = np.flatnonzero(row > 0).tolist()
                    cap = (k + bound) // 2
                model.addCons(quicksum(x[j] for j in indices) <= cap)
                n_score_constraints += 1
    model.setObjective(0.0)
    model.optimize()
    status = str(model.getStatus())
    sol = model.getBestSol()
    out = {
        "p": p,
        "mode": mode,
        "backend": "scip",
        "relaxation": False,
        "workers": workers,
        "n_plus_points": int(len(Yp)),
        "n_minus_points": int(len(Ym)),
        "n_variables": len(edges),
        "n_constraints": n_score_constraints + 2,
        "status_name": status,
        "success": sol is not None,
        "nodes": int(model.getNNodes()),
        "gap": float(model.getGap()),
        "seconds": round(time.time() - t0, 3),
    }
    if sol is not None:
        xi = np.fromiter((round(model.getSolVal(sol, v)) for v in x), dtype=np.int8)
        out["chosen_edges"] = [list(edge) for edge, bit in zip(edges, xi) if bit]
        out["plus_scores"] = sorted({int(v) for v in (Fp @ xi).tolist()})
        out["minus_scores"] = sorted({int(v) for v in (Fm @ xi).tolist()})
    return out


def solve(
    p: int,
    mode: str,
    plus_path: Path,
    minus_path: Path,
    time_limit: float,
    relax: bool,
    backend: str = "highs",
    workers: int = 1,
    cut_batch: int = 256,
    round_limit: float = 120.0,
) -> dict:
    t0 = time.time()
    C = np.rint(paley_conference_prime_power(p)).astype(np.int8)
    if mode == "affine":
        Yp = affine_shell(p, 1, C)
        Ym = affine_shell(p, -1, C)
    elif mode == "full":
        Yp = np.sign(np.load(plus_path, mmap_mode="r")).astype(np.int8)
        Ym = np.sign(np.load(minus_path, mmap_mode="r")).astype(np.int8)
    else:
        raise ValueError(mode)

    if backend == "cp-sat":
        if relax:
            raise ValueError("CP-SAT has no relaxation mode")
        return solve_cpsat(p, mode, Yp, Ym, C, time_limit, workers)
    if backend == "cp-sat-cut":
        if relax:
            raise ValueError("CP-SAT has no relaxation mode")
        return solve_cpsat_cutting_plane(
            p,
            mode,
            Yp,
            Ym,
            C,
            time_limit,
            workers,
            cut_batch,
            round_limit,
        )
    if backend == "scip":
        if relax:
            raise ValueError("use the HiGHS backend for the LP relaxation")
        return solve_scip(p, mode, Yp, Ym, C, time_limit, workers)
    if backend != "highs":
        raise ValueError(backend)

    edges, Fp = feature_rows(Yp, C)
    edges_m, Fm = feature_rows(Ym, C)
    if edges_m != edges:
        raise RuntimeError("edge orders differ")
    ei = edges.index((0, 1))
    nvar = len(edges)

    blocks: list[csr_matrix] = []
    lower: list[float] = []
    upper: list[float] = []

    blocks.append(csr_matrix(np.ones((1, nvar), dtype=np.float64)))
    lower.append(float(4 * p))
    upper.append(float(4 * p))
    erow = np.zeros((1, nvar), dtype=np.float64)
    erow[0, ei] = 1.0
    blocks.append(csr_matrix(erow))
    lower.append(0.0)
    upper.append(0.0)

    fep = Fp[:, ei]
    fem = Fm[:, ei]
    add_score_rows(blocks, lower, upper, Fp, fep, "plus")
    add_score_rows(blocks, lower, upper, Fm, fem, "minus")

    A = vstack(blocks, format="csr")
    result = milp(
        np.zeros(nvar, dtype=np.float64),
        integrality=(
            np.zeros(nvar, dtype=np.uint8)
            if relax
            else np.ones(nvar, dtype=np.uint8)
        ),
        bounds=Bounds(np.zeros(nvar), np.ones(nvar)),
        constraints=LinearConstraint(A, np.asarray(lower), np.asarray(upper)),
        options={
            "time_limit": float(time_limit),
            "mip_rel_gap": 0.0,
            "presolve": True,
        },
    )

    out = {
        "p": p,
        "mode": mode,
        "backend": "highs",
        "relaxation": bool(relax),
        "n_plus_points": int(len(Yp)),
        "n_minus_points": int(len(Ym)),
        "n_variables": nvar,
        "n_constraints": int(A.shape[0]),
        "status": int(result.status),
        "success": bool(result.success),
        "message": str(result.message),
        "mip_node_count": getattr(result, "mip_node_count", None),
        "mip_gap": getattr(result, "mip_gap", None),
        "seconds": round(time.time() - t0, 3),
    }
    if result.x is not None:
        x = np.asarray(result.x)
        out.update(
            {
                "sum_x": float(x.sum()),
                "min_x": float(x.min()),
                "max_x": float(x.max()),
                "n_fractional": int(
                    np.count_nonzero((x > 1e-8) & (x < 1.0 - 1e-8))
                ),
            }
        )
        if not relax:
            xi = np.rint(x).astype(np.int8)
            out["chosen_edges"] = [
                list(edge) for edge, bit in zip(edges, xi) if bit
            ]
            out["plus_scores"] = sorted({int(v) for v in (Fp @ xi).tolist()})
            out["minus_scores"] = sorted({int(v) for v in (Fm @ xi).tolist()})
        else:
            out["fractional_edges"] = [
                [int(a), int(b), float(value)]
                for (a, b), value in zip(edges, x)
                if value > 1e-10
            ]
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--p", type=int, default=7)
    ap.add_argument("--mode", choices=("affine", "full"), default="affine")
    ap.add_argument("--plus", type=Path)
    ap.add_argument("--minus", type=Path)
    ap.add_argument("--time-limit", type=float, default=600.0)
    ap.add_argument("--relax", action="store_true")
    ap.add_argument(
        "--backend",
        choices=("highs", "cp-sat", "cp-sat-cut", "scip"),
        default="highs",
    )
    ap.add_argument("--workers", type=int, default=1)
    ap.add_argument("--cut-batch", type=int, default=256)
    ap.add_argument("--round-limit", type=float, default=120.0)
    ap.add_argument("--output", type=Path)
    args = ap.parse_args()
    out = solve(
        args.p,
        args.mode,
        args.plus if args.plus is not None else DEFAULT_PLUS[args.p],
        args.minus if args.minus is not None else DEFAULT_MINUS[args.p],
        args.time_limit,
        args.relax,
        backend=args.backend,
        workers=args.workers,
        cut_batch=args.cut_batch,
        round_limit=args.round_limit,
    )
    print(json.dumps(out, indent=2), flush=True)
    if args.output:
        args.output.write_text(json.dumps(out, indent=2) + "\n")


if __name__ == "__main__":
    main()
