#!/usr/bin/env python3
"""Sparse atomic GPU scan of low-order scalar W2 obstructions.

This avoids the full odd-order FFT and polynomial gcd.  For each requested
order d dividing oddpart(p-1), a GPU kernel accumulates only the parity of the
square/nonsquare endpoint sequences in exponent classes modulo d.  Block-local
atomic XOR bins are merged into a tiny device result.  The host reconstructs
the oriented content with the equally tiny Bose-generator residues and tests

    gcd(Phi_d, c(X), c(X^-1)).

Only exceptional (p, endpoint, order) records are retained.  The field orbit
and inverse-log table are generated by the compiled native helper rather than
Python.  This is the W2 analogue of the Wieferich engine's persistent buffers,
grid-stride loop, and atomic sparse-hit path.
"""
from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

import numpy as np
import sympy as sp

ROOT = Path(
    os.environ.get("QML_REPO_ROOT", Path(__file__).resolve().parents[1])
)
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from e1_gmin_m4_prop15598 import field_ctx  # noqa: E402
from e1_gmin_m4_prop15604 import _primitive  # noqa: E402
from e1_gmin_m4_prop15613 import _finv  # noqa: E402
from gf2x_ntl import field_orbits  # noqa: E402
from io_atomic import write_json_atomic  # noqa: E402
from w2_translated_antipodal_norm_scan import (  # noqa: E402
    f2_gcd_bits,
    is_prime,
)


KERNEL_SOURCE = r"""
extern "C" __global__
void endpoint_residue_bins(
    const unsigned int* points,
    unsigned long long orbit_length,
    unsigned int component,
    unsigned int p,
    unsigned int ia,
    unsigned int ib,
    unsigned int sinv_a,
    unsigned int sinv_b,
    const unsigned int* inverse,
    const signed char* legendre,
    const unsigned int* pole_t,
    const unsigned char* global_flip,
    unsigned int n_endpoints,
    const unsigned int* orders,
    const unsigned int* order_offsets,
    unsigned int n_orders,
    unsigned int total_order,
    unsigned int* output) {
    extern __shared__ unsigned int local_bins[];
    const unsigned int thread = threadIdx.x;
    const unsigned int local_size = n_endpoints * total_order;
    for (unsigned int slot = thread; slot < local_size; slot += blockDim.x) {
        local_bins[slot] = 0U;
    }
    __syncthreads();

    const unsigned long long stride =
        (unsigned long long)gridDim.x * blockDim.x;
    for (unsigned long long j =
             (unsigned long long)blockIdx.x * blockDim.x + thread;
         j < orbit_length;
         j += stride) {
        const unsigned int point = points[j];
        const unsigned long long a = point % p;
        const unsigned long long b = point / p;
        const unsigned int level = (unsigned int)(
            (sinv_a * b + sinv_b * a +
             (unsigned long long)sinv_b * b * ia) % p);
        const unsigned int base_bit = level > (p - 1U) / 2U;

        for (unsigned int endpoint = 0; endpoint < n_endpoints; ++endpoint) {
            const unsigned long long t = pole_t[endpoint];
            const unsigned long long e = (t * a + p - 1U) % p;
            const unsigned long long f = (t * b) % p;
            const unsigned int norm_positive = (unsigned int)(
                (e * e + (unsigned long long)ia * e * f) % p);
            const unsigned int norm_negative = (unsigned int)(
                ((unsigned long long)ib * f % p) * f % p);
            const unsigned int norm =
                (norm_positive + p - norm_negative) % p;

            unsigned int source_bit;
            unsigned int switch_bit;
            if (norm == 0U) {
                source_bit = 1U;
                switch_bit = 0U;
            } else {
                const unsigned long long inv_norm = inverse[norm];
                const unsigned long long inv_a =
                    ((e + (unsigned long long)ia * f) * inv_norm) % p;
                const unsigned long long inv_b =
                    ((p - f) * inv_norm) % p;
                const unsigned int image_a = (unsigned int)(
                    (a * inv_a + (unsigned long long)ib * b * inv_b) % p);
                const unsigned int image_b = (unsigned int)(
                    (a * inv_b + b * inv_a +
                     (unsigned long long)ia * b * inv_b) % p);
                const unsigned int image_level = (unsigned int)(
                    ((unsigned long long)sinv_a * image_b +
                     (unsigned long long)sinv_b * image_a +
                     (unsigned long long)sinv_b * image_b * ia) % p);
                source_bit = image_level > (p - 1U) / 2U;
                switch_bit = legendre[norm] < 0;
            }
            const unsigned int w =
                base_bit ^ source_bit ^ switch_bit ^ global_flip[endpoint];
            if (!w) continue;
            const unsigned int endpoint_base = endpoint * total_order;
            for (unsigned int order_index = 0;
                 order_index < n_orders;
                 ++order_index) {
                const unsigned int d = orders[order_index];
                const unsigned int slot = endpoint_base +
                    order_offsets[order_index] + (unsigned int)(j % d);
                atomicXor(&local_bins[slot], 1U);
            }
        }
    }
    __syncthreads();
    const unsigned int output_base = component * local_size;
    for (unsigned int slot = thread; slot < local_size; slot += blockDim.x) {
        if (local_bins[slot] & 1U) {
            atomicXor(&output[output_base + slot], 1U);
        }
    }
}
"""


def oddpart(value: int) -> int:
    while value % 2 == 0:
        value //= 2
    return value


def inverse_and_legendre_tables(p: int) -> tuple[np.ndarray, np.ndarray]:
    inverse = np.zeros(p, dtype=np.uint32)
    inverse[1] = 1
    for value in range(2, p):
        inverse[value] = (
            p - (p // value) * int(inverse[p % value]) % p
        )
    legendre = np.full(p, -1, dtype=np.int8)
    legendre[0] = 0
    values = np.arange(1, (p + 1) // 2, dtype=np.uint64)
    legendre[(values * values % p).astype(np.int64)] = 1
    return inverse, legendre


def gamma_bins(
    p: int,
    sig: int,
    mul,
    add,
    logarithm: np.ndarray,
    orders: list[int],
    offsets: list[int],
    total_order: int,
) -> np.ndarray:
    bins = np.zeros((2, total_order), dtype=np.uint8)

    def include(point: int) -> None:
        if point == 0:
            return
        code = int(logarithm[point])
        component = code >> 31
        exponent = code & 0x7FFFFFFF
        for d, offset in zip(orders, offsets):
            bins[component, offset + exponent % d] ^= 1

    for t in range(p):
        line_point = mul(t, sig)
        include(add(1, line_point))
        include(line_point)
    return bins


def cyclic_crosscorrelation(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    d = len(left)
    result = np.zeros(d, dtype=np.uint8)
    left_indices = np.flatnonzero(left)
    for shift in range(d):
        result[shift] = np.bitwise_xor.reduce(
            right[(left_indices - shift) % d], initial=np.uint8(0)
        )
    return result


def polynomial_bits(coefficients: np.ndarray) -> int:
    packed = np.packbits(coefficients, bitorder="little")
    return int.from_bytes(packed.tobytes(), "little")


def reciprocal_bits(coefficients: np.ndarray) -> int:
    return polynomial_bits(
        np.concatenate((coefficients[:1], coefficients[:0:-1]))
    )


def cyclotomic_bits(order: int) -> int:
    x = sp.symbols("x")
    polynomial = sp.Poly(sp.cyclotomic_poly(order, x), x, modulus=2)
    coefficients = np.asarray(
        list(reversed([int(value) & 1 for value in polynomial.all_coeffs()])),
        dtype=np.uint8,
    )
    return polynomial_bits(coefficients)


def record(
    p: int,
    requested_orders: list[int],
    offsets_requested: list[int],
    kernel,
) -> dict:
    import cupy as cp

    started = time.perf_counter()
    q, mul, add, chi, _frob, _norm, ia, ib = field_ctx(p)
    sig = next(value for value in range(1, q) if chi(value) == -1)
    sinv = _finv(mul, q, sig)
    sinv_a, sinv_b = sinv % p, sinv // p
    omega = _primitive(mul, q)
    generator = mul(omega, omega)
    square, nonsquare, logarithm = field_orbits(
        p, ia, ib, generator, omega
    )
    orbit_seconds = time.perf_counter() - started

    scalar_order = oddpart(p - 1)
    projective_order = (p + 1) // 2
    ambient_order = projective_order * scalar_order
    orders = [d for d in requested_orders if ambient_order % d == 0]
    order_offsets = []
    total_order = 0
    for d in orders:
        order_offsets.append(total_order)
        total_order += d
    if not orders:
        return {
            "p": p,
            "scalar_order": scalar_order,
            "orders_tested": [],
            "exceptions": [],
            "timing_seconds": {
                "orbit": orbit_seconds,
                "total": time.perf_counter() - started,
            },
        }

    endpoint_offsets = [
        value
        for value in offsets_requested
        if projective_order + value < p
    ]
    inverse, legendre = inverse_and_legendre_tables(p)
    pole_parameters = []
    global_flips = []
    lam = sinv_b
    half = (p - 1) // 2
    for endpoint_offset in endpoint_offsets:
        u = projective_order + endpoint_offset
        pole_t = lam * pow(u, p - 2, p) % p
        pole_parameters.append(pole_t)
        inverse_t = int(inverse[pole_t])
        infinity_image_level = sinv_b * inverse_t % p
        infinity_image_bit = infinity_image_level > half
        global_flips.append(1 ^ infinity_image_bit)

    gamma_started = time.perf_counter()
    generator_bins = gamma_bins(
        p,
        sig,
        mul,
        add,
        logarithm,
        orders,
        order_offsets,
        total_order,
    )
    gamma_seconds = time.perf_counter() - gamma_started

    gpu_started = time.perf_counter()
    memory_pool = cp.get_default_memory_pool()
    if memory_pool.get_limit() == 0:
        memory_pool.set_limit(fraction=0.75)
    d_inverse = cp.asarray(inverse)
    d_legendre = cp.asarray(legendre)
    d_poles = cp.asarray(pole_parameters, dtype=cp.uint32)
    d_flips = cp.asarray(global_flips, dtype=cp.uint8)
    d_orders = cp.asarray(orders, dtype=cp.uint32)
    d_offsets = cp.asarray(order_offsets, dtype=cp.uint32)
    output = cp.zeros(
        (2, len(endpoint_offsets), total_order), dtype=cp.uint32
    )
    threads = 256
    blocks = min(2048, (len(square) + threads - 1) // threads)
    shared_bytes = len(endpoint_offsets) * total_order * 4
    if shared_bytes > 48 * 1024:
        raise RuntimeError(
            f"shared residue bins need {shared_bytes} bytes; reduce --max-order"
        )
    for component, points in enumerate((square, nonsquare)):
        d_points = cp.asarray(points)
        kernel(
            (blocks,),
            (threads,),
            (
                d_points,
                np.uint64(len(points)),
                np.uint32(component),
                np.uint32(p),
                np.uint32(ia),
                np.uint32(ib),
                np.uint32(sinv_a),
                np.uint32(sinv_b),
                d_inverse,
                d_legendre,
                d_poles,
                d_flips,
                np.uint32(len(endpoint_offsets)),
                d_orders,
                d_offsets,
                np.uint32(len(orders)),
                np.uint32(total_order),
                output,
            ),
            shared_mem=shared_bytes,
        )
        del d_points
    cp.cuda.runtime.deviceSynchronize()
    endpoint_bins = (cp.asnumpy(output) & 1).astype(np.uint8)
    gpu_seconds = time.perf_counter() - gpu_started

    classify_started = time.perf_counter()
    exceptions = []
    for d, order_offset in zip(orders, order_offsets):
        cyclotomic = cyclotomic_bits(d)
        gamma_components = generator_bins[
            :, order_offset : order_offset + d
        ]
        for endpoint_index, endpoint_offset in enumerate(endpoint_offsets):
            content = np.zeros(d, dtype=np.uint8)
            for component in range(2):
                endpoint_component = endpoint_bins[
                    component,
                    endpoint_index,
                    order_offset : order_offset + d,
                ]
                content ^= cyclic_crosscorrelation(
                    endpoint_component, gamma_components[component]
                )
            content_value = polynomial_bits(content)
            aut_bad = f2_gcd_bits(cyclotomic, content_value)
            aut_bad = f2_gcd_bits(aut_bad, reciprocal_bits(content))
            if aut_bad != 1:
                exceptions.append(
                    {
                        "endpoint_offset": endpoint_offset,
                        "order": d,
                        "layer": (
                            "projective"
                            if projective_order % d == 0
                            else "nonprojective"
                        ),
                        "aut_bad_degree": aut_bad.bit_length() - 1,
                        "aut_bad_hex": hex(aut_bad),
                    }
                )
    classify_seconds = time.perf_counter() - classify_started
    return {
        "p": p,
        "scalar_order": scalar_order,
        "projective_order": projective_order,
        "ambient_order": ambient_order,
        "orders_tested": orders,
        "endpoint_offsets": endpoint_offsets,
        "exceptions": exceptions,
        "timing_seconds": {
            "orbit": orbit_seconds,
            "gamma_residues": gamma_seconds,
            "atomic_gpu": gpu_seconds,
            "classification": classify_seconds,
            "total": time.perf_counter() - started,
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", type=int, default=5)
    parser.add_argument("--stop", type=int, required=True)
    parser.add_argument("--offsets", default="0,1")
    parser.add_argument("--orders")
    parser.add_argument("--max-order", type=int, default=63)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    endpoint_offsets = [int(value) for value in args.offsets.split(",")]
    if args.orders:
        requested_orders = sorted(
            set(int(value) for value in args.orders.split(","))
        )
    else:
        requested_orders = list(range(3, args.max_order + 1, 2))
    if any(d < 3 or d % 2 == 0 for d in requested_orders):
        raise ValueError("orders must be odd and at least 3")

    import cupy as cp

    kernel = cp.RawKernel(KERNEL_SOURCE, "endpoint_residue_bins")
    primes = [
        p
        for p in range(max(5, args.start), args.stop + 1)
        if p % 12 == 5 and is_prime(p)
    ]
    started = time.perf_counter()
    rows = []
    all_exceptions = []
    for index, p in enumerate(primes, 1):
        row = record(p, requested_orders, endpoint_offsets, kernel)
        rows.append(row)
        for exception in row["exceptions"]:
            all_exceptions.append({"p": p, **exception})
        print(
            f"[{index}/{len(primes)}] p={p} orders={len(row['orders_tested'])} "
            f"exceptions={row['exceptions']} "
            f"seconds={row['timing_seconds']['total']:.3f}",
            flush=True,
        )
    result = {
        "range": [args.start, args.stop],
        "congruence_class": "p == 5 (mod 12)",
        "requested_orders": requested_orders,
        "endpoint_offsets": endpoint_offsets,
        "n_primes": len(rows),
        "exceptions": all_exceptions,
        "rows": rows,
        "elapsed_seconds": time.perf_counter() - started,
    }
    write_json_atomic(args.output, result)
    print(
        f"done primes={len(rows)} exceptions={len(all_exceptions)} "
        f"elapsed={result['elapsed_seconds']:.3f}s",
        flush=True,
    )


if __name__ == "__main__":
    main()
