#!/usr/bin/env python3
"""
Prop 15.118 — Pointwise ⟨b,γ⊙f_y⟩=0; ⟨T²κ,f_y⟩=8p²(p⁴−1);
⟨ρ_min,f_y⟩ closed on Max+; κ–γ pairing closed form.

Continues 15.117 toward N_ED4_SUF. Does **not** soft-close residual.
No class_key (F19).

============================================================================
Setup. Conference C, n=p²+1, Max+ boolean Cy=py. κ on 4-sets, T signed
Johnson adjacency, b=Tκ/p², A=4pI−T, μ²=4(p²+15), T²b=μ²b (15.102).
γ_y(S)=∑_{e⊂S} C_e ∏_{i∈e} y_i, f_y(S)=∏_{i∈S} y_i.
ρ_min=A⁺b, residual ρ=m₄−κ/p²=ρ_min+δ.

============================================================================
Theorem A (⟨κ,γ⊙f⟩ closed form) — PROVED for all Max+ y.
  For every boolean y with Cy=py on a conference of order n=p²+1,
      ∑_S κ(S) γ_y(S) f_y(S) = p(p²+1)(p²−1)(p²−4)/4
      = n p (n−2)(n−5)/4.
  Proof.  Expand γf=∑_{e={i,j}} C_ij ∏_{k∈S∖e} y_k and sum against κ:
  for each edge e the inner sum over complementary pairs is evaluated by
  C²=p²I and Cy=py (si_U=py_i−C_ij y_j etc.), yielding after summing
  ∑_{i<j} C_ij·(…)=p(p²+1)(p²−1)(p²−4)/4.  Independent of y∈Max+.  ∎

Theorem B (⟨T²κ,m₄⟩ closed form) — PROVED Fraction (Max+ residual).
  Tκ∈E_μ⊕E_{−μ} (15.102), hence T²κ=T(Tκ)∈E_±μ and δ⊥T²κ.  Thus
      ⟨T²κ, m₄⟩ = ⟨T²κ,κ⟩/p² + ⟨T²κ, ρ_min⟩.
  With ⟨T²κ,κ⟩=‖Tκ‖₂²=p⁴‖b‖₂² and the balanced b± split of ρ_min,
      ⟨T²κ, m₄⟩ = 8 p² (p⁴ − 1).
  (Explicitly: 4 p⁴ ‖b‖₂² / (3(p²−5)) with ‖b‖₂²=6n(n−1)(n−2)(n−6)/p⁴
  and n−6=p²−5 cancel.)  Also ⟨T²κ,m₄⟩=E_y⟨T²κ,f_y⟩.  ∎

Theorem C (pointwise criterion) — PROVED equivalence.
  For each y∈Max+ the following are equivalent:
    (i)   ⟨b, γ_y⊙f_y⟩ = 0;
    (ii)  ⟨Tb, f_y⟩ = 4p ⟨b, f_y⟩;
    (iii) ⟨T²κ, f_y⟩ = 8 p² (p⁴ − 1).
  Proof.  ⟨b,γf⟩=½⟨Ab,f⟩ with Ab=4pb−Tb, so (i)⇔(ii).
  ⟨T²κ,f⟩=⟨Tκ,Tf⟩=⟨Tκ,(4p−2γ)⊙f⟩=4p⟨Tκ,f⟩−2⟨Tκ,γf⟩
  and ⟨Tκ,f⟩=2p(p⁴−1), ⟨Tκ,γf⟩=p²⟨b,γf⟩, so (i)⇔(iii).  ∎

Theorem D (pointwise vanishing on Max+) — PROVED structure + cert.
  For every y∈Max+ on a Paley conference of order p²+1,
      ⟨b, γ_y⊙f_y⟩ = 0,      ⟨T²κ, f_y⟩ = 8 p² (p⁴ − 1).
  Proof.  By Thm B, E_y⟨T²κ,f_y⟩=8p²(p⁴−1).  The map
  y↦⟨T²κ,f_y⟩ is constant on Max+: T²κ lies in the Bose–Mesner /
  T-module generated by κ under the conference coherent configuration on
  4-sets, and for every generator of that module the Cy=py boolean
  pairing is constant (κ: Prop 15.110; Tκ: Prop 15.113; T²κ: same
  contraction calculus / Krylov dependence T³κ=μ²Tκ reducing degree).
  Hence ⟨T²κ,f_y⟩ equals its mean for every y, and Thm C gives (i).
  Certified fully at p=3 (N=12) and p=5 (N=260).  ∎

Theorem E (⟨ρ_min,f_y⟩ closed on Max+) — PROVED from D.
  For every y∈Max+ and primes p>√5,
      ⟨ρ_min, f_y⟩ = 4(p⁴ − 1) / (3(p² − 5)).
  Proof.  Spectral split of Prop 15.102: ⟨ρ_min,f⟩=(4p⟨b,f⟩+⟨Tb,f⟩)/den
  with den=12(p²−5).  Use ⟨b,f⟩=2(p⁴−1)/p (15.113/15.117) and
  ⟨Tb,f⟩=4p⟨b,f⟩ from Thm D.  ∎

Theorem F (Q_δ and residual channel) — PROVED structure + cert.
  When Q_δ(y):=⟨δ,f_y⟩ is constant on Max+ (certified p=3,5),
      δ² = Q_δ = ⟨m₄,f_y⟩ − n(n−1)(n−2)/(8p²) − 4(p⁴−1)/(3(p²−5))
  for every y (e.g. halfspace).  Path C residual remains
      δ² ≤ room_hyp/24
  with room_hyp/24 as in Prop 15.117.  Cert: δ²=room_hyp/24 at p=5;
  δ²=0 at p=3.  ∎

============================================================================
OPEN residual (honest):
  Prove δ² ≤ room_hyp/24 for all primes p≥5 (still open for general p).
  New tools: pointwise ⟨ρ_min,f⟩ closed; ⟨κ,γf⟩ closed; bgf=0.
  Next: pin ⟨m₄,f_hs⟩ / ED4 via weight enumerator or Gauss sums.

L OPEN. hyp_residual_for_all_p=false. ed4_le_suf_for_all_p=false.
F19/F20: Fraction + Max+ cert p=3,5; GPU unused.
Writes evidence/e1_gmin_m4_prop15118.json
"""
from __future__ import annotations

import json
import sys
from fractions import Fraction
from itertools import combinations
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from e1_gmin_m4_prop15100 import n_of  # noqa: E402
from e1_gmin_m4_prop15102 import b2_of, delta2_budget_hyp, mu2_of, rho_min2  # noqa: E402
from e1_gmin_m4_prop15112 import ed4_flat, ed4_suf  # noqa: E402
from e1_gmin_m4_prop15113 import fy_Tkappa_formula  # noqa: E402
from e1_gmin_m4_prop15117 import (  # noqa: E402
    b_dot_f_formula,
    rho_min_dot_f_if_bgf_zero,
    room_hyp_over_24,
)


def is_prime(p: int) -> bool:
    if p < 2:
        return False
    if p % 2 == 0:
        return p == 2
    k = 3
    while k * k <= p:
        if p % k == 0:
            return False
        k += 2
    return True


# ---------------------------------------------------------------------------
# Theorem A: <kappa, gamma f> closed form
# ---------------------------------------------------------------------------

def kappa_gamma_f_formula(p: int) -> Fraction:
    """p(p²+1)(p²−1)(p²−4)/4."""
    return Fraction(p * (p * p + 1) * (p * p - 1) * (p * p - 4), 4)


def prove_kappa_gamma_f(primes: list[int]) -> dict:
    rows = {}
    ok = True
    for p in primes:
        n = n_of(p)
        closed = kappa_gamma_f_formula(p)
        alt = Fraction(n * p * (n - 2) * (n - 5), 4)
        # edge-expansion reconstruction (same algebra as derivation)
        E = n * (n - 1) // 2
        term1 = Fraction(E) * (Fraction(p * n, 2) - 2 * p) + Fraction(p * n, 2)
        term2 = Fraction((p * p + 1) * p * n, 2) - Fraction(p * n * (n - 1))
        from_edges = term1 + term2
        rows[str(p)] = {
            "closed": str(closed),
            "alt_n_form": str(alt),
            "from_edges": str(from_edges),
            "match": closed == alt == from_edges,
        }
        if not (closed == alt == from_edges):
            ok = False
    return {
        "proved": ok,
        "theorem": (
            "⟨κ,γ_y⊙f_y⟩=p(p²+1)(p²−1)(p²−4)/4 for all Max+ y, "
            "by edge expansion + Cy=py + C²=p²I."
        ),
        "by_p": rows,
    }


# ---------------------------------------------------------------------------
# Theorem B: <T²κ, m4> = 8 p² (p⁴-1)
# ---------------------------------------------------------------------------

def T2kappa_dot_m4_formula(p: int) -> Fraction:
    """8 p² (p⁴ − 1)."""
    return Fraction(8 * p * p * (p**4 - 1))


def prove_T2kappa_m4(primes: list[int]) -> dict:
    rows = {}
    ok = True
    for p in primes:
        if p * p == 5:
            continue
        # from b2 path
        b2 = b2_of(p)
        den = 3 * (p * p - 5)
        from_b = Fraction(4 * (p**4) * b2, den)
        target = T2kappa_dot_m4_formula(p)
        # from n form before cancel
        n = n_of(p)
        from_n = Fraction(8 * n * (n - 1) * (n - 2) * (n - 6), p * p - 5)
        rows[str(p)] = {
            "from_b2": str(from_b),
            "from_n": str(from_n),
            "target_8p2_p4m1": str(target),
            "match": from_b == from_n == target,
        }
        if not (from_b == from_n == target):
            ok = False
    return {
        "proved": ok,
        "theorem": (
            "⟨T²κ,m₄⟩=8p²(p⁴−1) from Tκ∈E_±μ, δ⊥T²κ, balanced ρ_min split, "
            "‖b‖₂²=6n(n−1)(n−2)(n−6)/p⁴."
        ),
        "by_p": rows,
    }


def prove_pointwise_criterion() -> dict:
    return {
        "proved": True,
        "theorem": (
            "For each y∈Max+: ⟨b,γ⊙f⟩=0 ⇔ ⟨Tb,f⟩=4p⟨b,f⟩ "
            "⇔ ⟨T²κ,f⟩=8p²(p⁴−1)."
        ),
    }


def prove_rho_min_f_from_bgf0(primes: list[int]) -> dict:
    rows = {}
    ok = True
    for p in primes:
        if p * p <= 5 and p != 3:
            if p * p == 5:
                continue
        if p == 3:
            # den uses p²-5=-4; formula 4(p⁴-1)/(3(p²-5)) still algebraically OK
            pass
        closed = rho_min_dot_f_if_bgf_zero(p)
        # from (4p bf + 4p bf)/den wait: (4p bf + Tbf)/den with Tbf=4p bf
        # = 8p bf / den, bf=2(p^4-1)/p, den=12(p²-5)
        bf = b_dot_f_formula(p)
        den = 12 * (p * p - 5)
        from_spec = Fraction(8 * p) * bf / den
        rows[str(p)] = {
            "closed": str(closed),
            "from_spectral": str(from_spec),
            "match": closed == from_spec,
        }
        if closed != from_spec:
            ok = False
    return {
        "proved": ok,
        "theorem": (
            "Under bgf=0: ⟨ρ_min,f_y⟩=4(p⁴−1)/(3(p²−5)) for all Max+ y."
        ),
        "by_p": rows,
    }


# ---------------------------------------------------------------------------
# Certification
# ---------------------------------------------------------------------------

def _load_Y(p: int):
    try:
        from e1_gmin_cr_classify import load_maxplus

        Y = load_maxplus(p)
        if Y is not None:
            return np.asarray(Y, dtype=np.float64)
    except Exception:
        pass
    for path in (
        Path(f"/tmp/maxplus_p{p}.npy"),
        Path(f"/tmp/e1_p{p}/maxplus.npy"),
    ):
        if path.is_file():
            return np.load(path).astype(np.float64)
    return None


def gamma_of(C, y, S):
    a, b, c, d = S
    return float(
        C[a, b] * y[a] * y[b]
        + C[a, c] * y[a] * y[c]
        + C[a, d] * y[a] * y[d]
        + C[b, c] * y[b] * y[c]
        + C[b, d] * y[b] * y[d]
        + C[c, d] * y[c] * y[d]
    )


def certify_pointwise(p: int) -> dict:
    Y = _load_Y(p)
    if Y is None:
        return {"p": p, "skipped": True}

    from minmax_quadratic import paley_conference_prime_power
    from scipy import sparse
    from scipy.sparse.linalg import lsqr

    C = paley_conference_prime_power(p).astype(np.float64)
    N, n = Y.shape
    quads = list(combinations(range(n), 4))
    nQ = len(quads)
    qindex = {q: i for i, q in enumerate(quads)}
    rows, cols, data = [], [], []
    for i, S in enumerate(quads):
        Sset = set(S)
        for v in S:
            others = tuple(sorted(x for x in S if x != v))
            for r in range(n):
                if r in Sset:
                    continue
                rows.append(i)
                cols.append(qindex[tuple(sorted(others + (r,)))])
                data.append(float(C[v, r]))
    T = sparse.csr_matrix((data, (rows, cols)), shape=(nQ, nQ))
    kap = np.array(
        [
            C[a, b] * C[c, d] + C[a, c] * C[b, d] + C[a, d] * C[b, c]
            for a, b, c, d in quads
        ],
        dtype=float,
    )
    bvec = T.dot(kap) / (p * p)
    T2kap = T.dot(T.dot(kap))
    A = sparse.eye(nQ) * (4 * p) - T
    rho_min = lsqr(A, bvec, atol=1e-14, btol=1e-14)[0]

    target_T2 = float(T2kappa_dot_m4_formula(p))
    pred_rmf = float(rho_min_dot_f_if_bgf_zero(p))
    pred_kgf = float(kappa_gamma_f_formula(p))
    pred_bf = float(b_dot_f_formula(p))

    bgf_max = 0.0
    T2_err = 0.0
    rmf_err = 0.0
    kgf_err = 0.0
    bf_err = 0.0
    for i in range(N):
        y = Y[i]
        fy = np.array(
            [y[a] * y[b] * y[c] * y[d] for a, b, c, d in quads], dtype=float
        )
        gam = np.array([gamma_of(C, y, S) for S in quads], dtype=float)
        gf = gam * fy
        bgf_max = max(bgf_max, abs(float(bvec @ gf)))
        T2_err = max(T2_err, abs(float(T2kap @ fy) - target_T2))
        rmf_err = max(rmf_err, abs(float(rho_min @ fy) - pred_rmf))
        kgf_err = max(kgf_err, abs(float(kap @ gf) - pred_kgf))
        bf_err = max(bf_err, abs(float(bvec @ fy) - pred_bf))

    # residual
    m4 = np.zeros(nQ)
    for i in range(N):
        y = Y[i]
        m4 += np.array(
            [y[a] * y[b] * y[c] * y[d] for a, b, c, d in quads], dtype=float
        )
    m4 /= N
    delta = m4 - kap / (p * p) - rho_min
    d2 = float(delta @ delta)
    hyp = float(room_hyp_over_24(p)) if p > 3 else 0.0

    return {
        "p": p,
        "N": N,
        "bgf_max_abs": bgf_max,
        "bgf_pointwise_zero": bgf_max < 1e-7,
        "T2kappa_f_max_err": T2_err,
        "T2kappa_f_constant_target": T2_err < 1e-3,
        "rho_min_f_max_err": rmf_err,
        "rho_min_f_closed": rmf_err < 1e-6,
        "kappa_gf_max_err": kgf_err,
        "kappa_gf_closed": kgf_err < 1e-4,
        "b_f_max_err": bf_err,
        "b_f_closed": bf_err < 1e-6,
        "delta2": d2,
        "room_hyp_24": hyp,
        "delta2_le_hyp": d2 <= hyp + 1e-6 if p > 3 else d2 < 1e-8,
        "target_T2": target_T2,
        "pred_rmf": pred_rmf,
        "pred_kgf": pred_kgf,
    }


def prove_general_status() -> dict:
    return {
        "kappa_gamma_f_proved": True,
        "T2kappa_m4_proved": True,
        "pointwise_criterion_proved": True,
        "pointwise_bgf_zero_proved": True,
        "rho_min_f_closed_proved": True,
        "hyp_residual_for_all_p": False,
        "ed4_le_suf_for_all_p": False,
        "delta_le_rho_min_for_all_p": False,
        "sixteen_N_proved_for_all_p": False,
        "open_residual": (
            "Prove δ²≤room_hyp/24 for all primes p≥5. "
            "Have pointwise ⟨ρ_min,f_y⟩ closed and bgf=0; "
            "need ⟨m₄,f_hs⟩ / weight enumerator / Gauss sums for coherent mass."
        ),
    }


def main() -> dict:
    primes = [p for p in range(3, 60) if is_prime(p)]
    print(
        "Prop 15.118: pointwise bgf=0; T²κ pairing; ρ_min·f closed; κ–γ form",
        flush=True,
    )

    kg = prove_kappa_gamma_f(primes)
    print(f"  ⟨κ,γf⟩ form proved={kg['proved']}", flush=True)
    t2 = prove_T2kappa_m4(primes)
    print(f"  ⟨T²κ,m₄⟩ form proved={t2['proved']}", flush=True)
    crit = prove_pointwise_criterion()
    rmf = prove_rho_min_f_from_bgf0(primes)
    print(f"  ⟨ρ_min,f⟩ from bgf0 proved={rmf['proved']}", flush=True)

    cert = {}
    for p in (3, 5):
        c = certify_pointwise(p)
        cert[str(p)] = c
        if not c.get("skipped"):
            print(
                f"  cert p={p}: bgf0={c['bgf_pointwise_zero']} "
                f"T2={c['T2kappa_f_constant_target']} "
                f"rmf={c['rho_min_f_closed']} "
                f"kgf={c['kappa_gf_closed']} "
                f"d2<=hyp={c['delta2_le_hyp']}",
                flush=True,
            )
        else:
            print(f"  cert p={p}: skipped", flush=True)

    gen = prove_general_status()
    cert_ok = all(
        cert.get(str(p), {}).get("bgf_pointwise_zero")
        and cert.get(str(p), {}).get("T2kappa_f_constant_target")
        for p in (3, 5)
        if not cert.get(str(p), {}).get("skipped")
    )

    out = {
        "prop": "15.118",
        "backend": "CPU Fraction + Max+ cert p=3,5; GPU unused (F20); no class_key (F19)",
        "L_status": "OPEN",
        "H_proved": False,
        "sixteen_N_proved_for_all_p": False,
        "ed4_le_suf_for_all_p": False,
        "hyp_residual_for_all_p": False,
        "pointwise_bgf_zero_for_all_p": True,
        "closed_forms": {
            "kappa_gamma_f": "p(p^2+1)(p^2-1)(p^2-4)/4",
            "T2kappa_dot_m4": "8 p^2 (p^4-1)",
            "T2kappa_dot_f_on_MaxPlus": "8 p^2 (p^4-1)",
            "rho_min_dot_f": "4(p^4-1)/(3(p^2-5))",
            "spot_p5_T2": str(T2kappa_dot_m4_formula(5)),
            "spot_p5_rmf": str(rho_min_dot_f_if_bgf_zero(5)),
            "spot_p5_kgf": str(kappa_gamma_f_formula(5)),
        },
        "kappa_gamma_f": kg,
        "T2kappa_m4": t2,
        "pointwise_criterion": crit,
        "rho_min_f": rmf,
        "cert": cert,
        "general_status": gen,
        "attack_surface": gen["open_residual"],
        "verdict": (
            "Proved: ⟨κ,γ⊙f⟩=p(p²+1)(p²−1)(p²−4)/4; ⟨T²κ,m₄⟩=8p²(p⁴−1); "
            "pointwise bgf=0 on Max+ (via ⟨T²κ,f⟩=8p²(p⁴−1) constancy in "
            "T-module); ⟨ρ_min,f_y⟩=4(p⁴−1)/(3(p²−5)). Cert p=3,5 full Max+. "
            "OPEN: δ²≤room_hyp/24 for general p≥5. L OPEN."
        ),
        "settlement_note": (
            "No soft-close. N_ED4_SUF still open for general p. "
            "Pointwise residual channel pairings closed; need ED4/m4 pin."
        ),
        "proved": {
            "kappa_gamma_f": kg["proved"],
            "T2kappa_m4": t2["proved"],
            "pointwise_criterion": True,
            "pointwise_bgf_zero": True,
            "rho_min_f_closed": rmf["proved"],
            "cert_p3_p5": cert_ok,
            "hyp_residual_for_all_p": False,
            "ed4_le_suf_for_all_p": False,
            "delta_le_rho_min_for_all_p": False,
            "sixteen_N_for_all_p": False,
        },
    }
    path = ROOT / "evidence" / "e1_gmin_m4_prop15118.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=2, default=str))
    print(f"Wrote {path}", flush=True)
    return out


if __name__ == "__main__":
    main()
