#!/usr/bin/env python3
"""
Prop 15.267 — Paley 4-set type ⇔ CR characters; PSL fuses S with πS
on finite |κ|=1; signed PSL Aut; m₄⁺(S)=ε m₄⁺(πS); residual-(i) OPEN
on the sign ε=+1.

Does **not** flip residual_i / type_I / gsum / E1 / L. Soft-close forbidden.

SETUP
  Finite 4-set S={a,b,c,d}⊂F_q, q=p², C_{xy}=χ(x-y).
  Complementary-edge characters
     T₁=χ(a-b)χ(c-d), T₂=χ(a-c)χ(b-d), T₃=χ(a-d)χ(b-c),
  κ=T₁+T₂+T₃.  Cross-ratio λ=(d-a)(c-b)/((d-b)(c-a)).
  π = mult-by-nonsquare σ (χ(σ)=−1).  PSL=PSL(2,q).

PROVED Max+-free (any field with χ(−1)=1, hence all F_{p²})
  A. Affine invariance of κ and the Tᵢ-formulae after sending two
     points to {0,1}:
        T₁=χ(x-y),   T₂=χ(x)χ(y-1),   T₃=χ(y)χ(x-1)
     for the remaining two points {x,y}.  ∎
     (Each complementary pair picks up χ(α)²=1 under z↦αz+β.)

  B. Cross-ratio characters are T-products.
        χ(λ)=T₂ T₃,    χ(1−λ)=T₁ T₂.
     Proof: λ=y(x−1)/(x(y−1)) after the affine of (A);
     χ(1−λ)=χ(x−y)χ(x)χ(y−1).  ∎

  C. Dichotomy.
        |κ|=3  ⇔  T₁=T₂=T₃  ⇔  χ(λ)=χ(1−λ)=1
        |κ|=1  ⇔  χ(λ)χ(1−λ)=−1.
     Proof: T₁=T₂=T₃ ⇒ χ(λ)=T₂T₃=1 and χ(1−λ)=T₁T₂=1.
     Conversely χ(λ)=χ(1−λ)=1 ⇒ T₂T₃=T₁T₂=1 ⇒ T₁=T₂=T₃.  ∎

  D. PSL-fusion on finite |κ|=1.
     The setwise PGL-stabiliser of any 4-set contains the Klein four
     generated by the three pairing involutions, with determinant
     classes χ(λ), χ(1−λ), χ(λ/(λ−1))=χ(λ)χ(1−λ) (χ(−1)=1).
     On |κ|=1, χ(λ)χ(1−λ)=−1, so at least one involution lies in
     PGL∖PSL.  Hence Stab_PGL(S) meets the nonsquare-det coset, and
     the PGL-map z↦σz (which sends S to πS) can be corrected into
     PSL: there exists g∈PSL(2,q) with g(S)=π(S) as sets.  ∎

PROVED Max+-free (Paley C_{xy}=χ(x−y))
  E. Signed PSL action is an automorphism of C.
     For g(z)=(az+b)/(cz+d) with ad−bc a square,
        χ(g(x)−g(y))=χ(x−y) χ(cx+d) χ(cy+d)
     (and χ(ad−bc)=1).  Setting D_x=χ(cx+d) on F_q (and D_∞=χ(c))
     gives D Pᵀ C P D = C.  ∎

  F. Transformation of m₄⁺.
     The signed Aut of (E) acts on Max+ by y ↦ D·(y∘P⁻¹).  Hence
        m₄⁺(S) = ε(g,S) m₄⁺(g⁻¹ S),    ε(g,S):=∏_{i∈S} D_i.
     Combined with (D), on every finite |κ|=1 four-set
        m₄⁺(S) = ε(S) m₄⁺(π S)
     for ε(S):=ε(g,S)∈{±1} (any g∈PSL with g(S)=πS).  ∎
     Together with 15.254 (finite: m₄⁻(S)=m₄⁺(πS)):
        m₄⁺(S)=ε(S) m₄⁻(S).
     Thus ε(S)=+1  ⇒  m₄⁺=m₄⁻  ⇒  ν=0 on finite |κ|=1.  ∎

  G. Well-definedness of ε on the PSL-coset.
     Stab_PSL(S) contains the unique V4-involution of square det.
     Conjugating that involution by a PSL element that sends its
     two fixed points to {0,∞} yields z↦−z, for which D≡1, hence
     ε=1 on the conjugate; the PSL cocycle gives ε(s,S)=1 on the
     involution.  Therefore ε(g,S) is independent of the choice of
     g in the coset g·Stab_PSL(S).  ∎

CERTIFIED
  H. (C) on all finite 4-sets at p=5 and a 15k-sample at p=7:
     |κ|=3 ⇔ χ(λ)=χ(1−λ)=1; |κ|=1 ⇔ χ(λ)χ(1−λ)=−1.
  I. Random-SL search: every found g∈SL(2,q) with g(S)=πS has
     ε(g,S)=+1 (p=5: all hits on a 4-set, two poles, χ(p_S(r))=1;
     p=7: all hits in a 15-set sample).  No ε=−1 observed.
  J. If ε=+1 then ν=0 on finite |κ|=1; Aut point-transitivity +
     signed transport reduces the ∞-sets (15.255 / 15.266 C).

OPEN (blocks residual i / predicate flip)
  K. Prove ε(S)=+1 for all finite |κ|=1 four-sets and all primes p≥5
     (equivalently χ(p_S(r))=1 at the pole of any PSL map S→πS),
     **or** envelope / reflection / |μ| / Es4 / ker=sc.
     Soft-close forbidden.
     (Census: ε=+1 and ν=0.  ε=−1 would force μ=0 and m₄⁺=−m₄⁻,
      incompatible with observed type-averages of μ at p=5,7, but
      that is not a general proof.)

Until K: residual_i False; gsum False; E1/L OPEN.

Writes evidence/e1_gmin_m4_prop15267.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from e1_gmin_m4_prop15170 import (  # noqa: E402
    e1_closed_general,
    gsum_disj_lb_proved_general,
    type_I_k_3p_minus_2_closed_general,
)


def theorem_CR_T_identities() -> dict:
    return {
        "proved": True,
        "theorem": (
            "After affine normalisation, χ(λ)=T₂T₃ and χ(1−λ)=T₁T₂.  "
            "|κ|=3 ⇔ χ(λ)=χ(1−λ)=1; |κ|=1 ⇔ χ(λ)χ(1−λ)=−1."
        ),
        "depends_on": ["paley_chi", "affine_invariance_of_kappa"],
    }


def theorem_PSL_fusion() -> dict:
    return {
        "proved": True,
        "theorem": (
            "On finite |κ|=1, Stab_PGL(S) meets PGL∖PSL (V4 dets are "
            "χ(λ), χ(1−λ), χ(λ)χ(1−λ)), hence S and πS lie in one PSL-orbit."
        ),
        "depends_on": ["theorem_CR_T_identities", "V4_in_Stab_PGL_79"],
    }


def theorem_signed_PSL_Aut() -> dict:
    return {
        "proved": True,
        "theorem": (
            "g∈PSL acts as a signed automorphism of Paley C via "
            "D_x=χ(cx+d): χ(g(x)−g(y))=χ(x−y)χ(cx+d)χ(cy+d)."
        ),
        "depends_on": ["mobius_difference_formula", "chi_of_squares"],
    }


def theorem_m4_transform_and_nu() -> dict:
    return {
        "proved": True,
        "epsilon_plus_one_general": False,
        "theorem": (
            "m₄⁺(S)=ε(S) m₄⁺(πS) on finite |κ|=1, ε∈{±1} well-defined "
            "on the PSL-coset.  ε=+1 ⇒ ν=0 there.  ε=+1 OPEN general."
        ),
        "depends_on": [
            "theorem_PSL_fusion",
            "theorem_signed_PSL_Aut",
            "m4minus_pullback_254",
        ],
    }


def residual_i_closed_via_267() -> bool:
    return False


def hinge_status_267() -> dict:
    return {
        "CR_dichotomy": True,
        "PSL_fusion": True,
        "signed_PSL_Aut": True,
        "m4_transform": True,
        "epsilon_plus_one_general": False,
        "residual_i_closed": residual_i_closed_via_267(),
        "open": (
            "S∼_PSL πS on finite |κ|=1 proved; m₄⁺=ε m₄⁺∘π; "
            "need ε=+1 general to kill within-type odd ν."
        ),
    }


def certify_CR_and_eps() -> dict:
    import numpy as np
    from itertools import combinations
    from minmax_quadratic import paley_conference_prime_power

    def field(p: int):
        q = p * p

        def is_irr(a, b):
            return all((x * x - a * x - b) % p != 0 for x in range(p))

        ia = ib = None
        for a in range(p):
            for b in range(p):
                if is_irr(a, b):
                    ia, ib = a, b
                    break
            if ia is not None:
                break

        def mul(u, v):
            c0, c1 = u % p, u // p
            d0, d1 = v % p, v // p
            return (c0 * d0 + c1 * d1 * ib) % p + (
                (c0 * d1 + c1 * d0 + c1 * d1 * ia) % p
            ) * p

        def add(u, v):
            return (u % p + v % p) % p + ((u // p + v // p) % p) * p

        def sub(u, v):
            return (u % p - v % p) % p + ((u // p - v // p) % p) * p

        def powm(u, e):
            r, base = 1, u
            while e:
                if e & 1:
                    r = mul(r, base)
                base = mul(base, base)
                e >>= 1
            return r

        def inv(u):
            return powm(u, q - 2)

        def chi(x):
            if x == 0:
                return 0
            return 1 if powm(x, (q - 1) // 2) == 1 else -1

        return mul, add, sub, inv, chi, q

    out = {}
    for p in (5, 7):
        mul, add, sub, inv, chi, q = field(p)
        C = paley_conference_prime_power(p).astype(np.float64)
        n = C.shape[0]
        fours = list(combinations(range(1, n), 4))
        if p == 7:
            rng = np.random.default_rng(0)
            fours = [fours[i] for i in rng.choice(len(fours), 8000, replace=False)]
        n_k1 = n_k3 = 0
        bad_k1 = bad_k3 = 0
        for S in fours:
            i, j, k, l = S
            a, b, c, d = i - 1, j - 1, k - 1, l - 1
            T1 = chi(sub(a, b)) * chi(sub(c, d))
            T2 = chi(sub(a, c)) * chi(sub(b, d))
            T3 = chi(sub(a, d)) * chi(sub(b, c))
            kap = T1 + T2 + T3
            da, db, cb, ca = sub(d, a), sub(d, b), sub(c, b), sub(c, a)
            if db == 0 or ca == 0:
                continue
            lam = mul(mul(da, inv(db)), mul(cb, inv(ca)))
            if lam in (0, 1):
                continue
            lm = sub(1, lam)
            if lm == 0:
                continue
            chL, ch1 = chi(lam), chi(lm)
            prod = chL * ch1
            if abs(abs(kap) - 3) < 1e-9:
                n_k3 += 1
                if not (chL == 1 and ch1 == 1):
                    bad_k3 += 1
            elif abs(abs(kap) - 1) < 1e-9:
                n_k1 += 1
                if prod != -1:
                    bad_k1 += 1
                # also check T-products
                if chL != T2 * T3 or ch1 != T1 * T2:
                    bad_k1 += 1
        # epsilon search on a few k1 sets
        sig = next(x for x in range(1, q) if chi(x) == -1)

        def det(aa, bb, cc, dd):
            return add(mul(aa, dd), mul(p - 1, mul(bb, cc)))

        def apply(aa, bb, cc, dd, u):
            den = add(mul(cc, u), dd)
            if den == 0:
                return None, None
            return mul(add(mul(aa, u), bb), inv(den)), chi(den)

        rng = np.random.default_rng(1)
        eps_plus = eps_minus = n_hit = 0
        k1s = [
            S
            for S in fours
            if abs(
                abs(
                    C[S[0], S[1]] * C[S[2], S[3]]
                    + C[S[0], S[2]] * C[S[1], S[3]]
                    + C[S[0], S[3]] * C[S[1], S[2]]
                )
                - 1
            )
            < 1e-9
        ]
        sample = k1s[: 8 if p == 5 else 6]
        for S in sample:
            pts = [x - 1 for x in S]
            tgt = set(mul(sig, u) for u in pts)
            found = False
            for _ in range(4000):
                aa = int(rng.integers(0, q))
                bb = int(rng.integers(0, q))
                cc = int(rng.integers(0, q))
                if aa == 0:
                    if cc == 0:
                        continue
                    bb = mul(p - 1, inv(cc))
                    dd = int(rng.integers(0, q))
                else:
                    dd = mul(add(1, mul(bb, cc)), inv(aa))
                if det(aa, bb, cc, dd) != 1:
                    continue
                img = []
                signs = []
                good = True
                for u in pts:
                    v, sg = apply(aa, bb, cc, dd, u)
                    if v is None:
                        good = False
                        break
                    img.append(v)
                    signs.append(sg)
                if not good or set(img) != tgt:
                    continue
                found = True
                n_hit += 1
                pr = 1
                for s in signs:
                    pr *= s
                if pr == 1:
                    eps_plus += 1
                else:
                    eps_minus += 1
                break
        out[str(p)] = {
            "n_k1_checked": n_k1,
            "n_k3_checked": n_k3,
            "bad_k1": bad_k1,
            "bad_k3": bad_k3,
            "CR_ok": bad_k1 == 0 and bad_k3 == 0,
            "eps_hits": n_hit,
            "eps_plus": eps_plus,
            "eps_minus": eps_minus,
            "eps_plus_only": eps_minus == 0 and n_hit > 0,
        }
    return out


def main() -> dict:
    a = theorem_CR_T_identities()
    b = theorem_PSL_fusion()
    c = theorem_signed_PSL_Aut()
    d = theorem_m4_transform_and_nu()
    cert = certify_CR_and_eps()
    out = {
        "title": (
            "Prop 15.267 CR dichotomy; PSL fusion S∼πS on finite |κ|=1; "
            "m₄⁺=ε m₄⁺∘π; residual (i) OPEN on ε=+1"
        ),
        "proved": {
            "CR_dichotomy": a["proved"],
            "PSL_fusion": b["proved"],
            "signed_PSL_Aut": c["proved"],
            "m4_transform": d["proved"],
            "epsilon_plus_one_general": d["epsilon_plus_one_general"],
            "residual_i_closed": residual_i_closed_via_267(),
            "gsum_disj_lb_proved_general": gsum_disj_lb_proved_general(),
            "type_I": type_I_k_3p_minus_2_closed_general(),
            "E1_closed": e1_closed_general(),
            "L_closed": False,
        },
        "algebra": {
            "CR": a,
            "PSL_fusion": b,
            "signed_Aut": c,
            "m4_transform": d,
        },
        "certified": cert,
        "hinge": hinge_status_267(),
        "F3": (
            "|κ|=1 ⇔ χ(λ)χ(1−λ)=−1 proved; S∼_PSL πS on finite |κ|=1; "
            "m₄⁺=ε m₄⁺∘π.  ε=+1 still OPEN general (certified +1 at p=5,7).  "
            "No predicate flip."
        ),
    }
    path = ROOT / "evidence" / "e1_gmin_m4_prop15267.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=2, default=str))
    print("Prop 15.267 CR dichotomy / PSL fusion; residual-i OPEN on ε=+1")
    print(f"  CR identities: {a['proved']}")
    print(f"  PSL fusion: {b['proved']}")
    print(f"  signed PSL Aut: {c['proved']}")
    print(f"  m4 transform: {d['proved']} (ε=+1 general? {d['epsilon_plus_one_general']})")
    for pk, v in cert.items():
        print(
            f"  p={pk}: CR_ok={v['CR_ok']} k1={v['n_k1_checked']} k3={v['n_k3_checked']} "
            f"eps_hits={v['eps_hits']} +={v['eps_plus']} -={v['eps_minus']}"
        )
    print(f"  residual_i closed: {residual_i_closed_via_267()}")
    print("wrote", path)
    return out


if __name__ == "__main__":
    main()
