#!/usr/bin/env python3
"""
Prop 15.602 — square-affine PΓL^+ on H0=ker S: unique 1-dimensional
invariant subspace ⟨1⟩; inversion preserves the 0-pencil.  H0/⟨1⟩
irreducible (hence dir(affine_span(Max−))=H0) is OPEN.

Does **not** flip residual_ii / multilevel_ND / phi_F / type_I / e1 / L.
Walsh 15.406 E stays OPEN.

============================================================================
Setup.  S is square-direction {∞}∪L incidence (15.598–15.600).
H0=ker S, dim n/2, radical ⟨1⟩ (15.600).  G_aff^□ is generated by
z↦z+τ (τ∈F_q), z↦α²z (α∈F_q^×), z↦z^p, all fixing ∞.

============================================================================
Theorem A — PROVED (Max-free; all odd p).
  G_aff^□ permutes the rows of S:
    (i)  z↦z+τ sends a+F_p b to (a+τ)+F_p b, same χ(b).
    (ii) z↦α²z sends a+F_p b to α²a+F_p(α²b), χ(α²b)=χ(b).
    (iii) Frobenius is F_p-linear, sends b to b^p, χ(b^p)=χ(b).
  Hence H0 is a G_aff^□-module.  Fail: claim a nonsquare dilation
  z↦αz, χ(α)=−1, permutes the rows (it swaps square/nonsquare
  directions; the image of a row is not a row).  ∎

Theorem B — PROVED (Max-free; all odd p).
  The unique 1-dimensional G_aff^□-invariant subspace of H0 is ⟨1⟩.
  A 1-dim F2-subspace is invariant iff its nonzero vector is
  G-fixed.  Translations act freely on F_q and fix ∞, so a fixed
  vector is constant on F_q.  Even weight (⟨1,x⟩=0 on H0) forces
  the value at ∞ to match, i.e. a multiple of 1.  Fail: a
  translation-invariant vector in H0 supported on a proper subset
  of F_q.  ∎

  If H0/⟨1⟩ is irreducible as a G-module then any Max−-difference
  outside ⟨1⟩ (non-antipodal pair) has G-span all of H0, so
  dir(affine_span(Max−))=H0.  15.603: H0 ∩ H0'=⟨1⟩ and
  H0+H0'=even-weight, so the heart splits as two (q−1)/2 pieces.
  Irreducibility of H0/⟨1⟩ is OPEN.

Theorem C — PROVED for the 0-pencil; H0-invariance CERTIFIED p=3,5,7,11.
  Inversion I(z)=1/z (I(∞)=0, I(0)=∞) sends {∞}∪F_p b to
  {∞}∪F_p b^{−1}, χ(b^{−1})=χ(b), so permutes the square-pencil
  through 0.  Fail: claim I permutes every row of S (a line with
  0∉L maps to a (p+1)-set not containing ∞).  Full H0-invariance
  (column-space residual 0) holds at p=3,5,7,11; 15.609 proves it
  for every odd p.

Theorem D — OPEN.  Walsh 15.406 E is dir(U)=ker S ∩ ker ℓ.
  Spanning of H0 is not Walsh.  residual_ii stays False.

============================================================================
Backend: identities serial; rref invariance p=3,5,7,11. GPU unused.
Writes evidence/e1_gmin_m4_prop15602.json
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from e1_gmin_m4_prop15406 import gf2_nullspace, gf2_rref  # noqa: E402
from e1_gmin_m4_prop15598 import _is_prime, field_ctx  # noqa: E402
from walsh_linecode_rank import (  # noqa: E402
    _mobius_perm,
    square_line_matrix,
)


def _nonsquare(p: int) -> int:
    q, mul, add, chi, frob, norm, ia, ib = field_ctx(p)
    for e in range(2, q):
        if chi(e) == -1:
            return e
    raise RuntimeError("no nonsquare")


def theorem_A_affine_permutes(primes=None) -> dict:
    """G_aff^□ permutes rows of S; nonsquare dilation does not."""
    if primes is None:
        primes = (3, 5, 7, 11)
    ok = True
    rows = {}
    for p in primes:
        q, mul, add, chi, frob, norm, ia, ib = field_ctx(p)
        S = square_line_matrix(p)
        # square dilation z -> g2 z is a row permutation: image of each
        # row equals some row.
        g2 = None
        for e in range(2, q):
            if chi(e) == 1 and e != 1:
                g2 = e
                break
        pi = _mobius_perm(p, g2, 0, 0, 1)
        imgs = []
        for v in S:
            w = v[pi]
            hit = any(np.array_equal(w, r) for r in S)
            imgs.append(hit)
        square_ok = all(imgs)
        # translation z -> z+1
        pi_t = _mobius_perm(p, 1, 1, 0, 1)
        trans_ok = all(any(np.array_equal(v[pi_t], r) for r in S) for v in S)
        # Frobenius
        pi_f = np.zeros(q + 1, dtype=np.int64)
        pi_f[0] = 0

        def fpow(u, e, mul=mul):
            r, base = 1, u
            while e:
                if e & 1:
                    r = mul(r, base)
                base = mul(base, base)
                e >>= 1
            return r

        for e in range(q):
            pi_f[1 + e] = 1 + fpow(e, p)
        frob_ok = all(any(np.array_equal(v[pi_f], r) for r in S) for v in S)
        # FAIL: nonsquare dilation
        ns = _nonsquare(p)
        pi_ns = _mobius_perm(p, ns, 0, 0, 1)
        # the image of one square-line under nonsquare dil should NOT be a row
        v0 = S[0]
        w0 = v0[pi_ns]
        ns_row = any(np.array_equal(w0, r) for r in S)
        ok = ok and square_ok and trans_ok and frob_ok and (not ns_row)
        rows[str(p)] = {
            "square_dil_permutes": square_ok,
            "trans_permutes": trans_ok,
            "frob_permutes": frob_ok,
            "nonsquare_image_is_row": ns_row,
        }
    return {
        "proved": bool(ok),
        "rows": rows,
        "theorem": (
            "Translations, square dilations, and Frobenius permute the "
            "rows of S.  Fail: nonsquare dilation permutes rows."
        ),
    }


def theorem_B_unique_line(primes=None) -> dict:
    """Unique 1-dim G_aff-invariant subspace of H0 is ⟨1⟩."""
    if primes is None:
        primes = (3, 5, 7, 11)
    ok = True
    rows = {}
    for p in primes:
        q, mul, add, chi, frob, norm, ia, ib = field_ctx(p)
        S = square_line_matrix(p)
        H0, _ = gf2_nullspace(S)
        n, k = H0.shape
        one = np.ones(n, dtype=np.uint8)
        # 1 in H0
        in_H0 = bool(((S.astype(np.int32) @ one.astype(np.int32)) % 2).max() == 0)
        # translation-invariant vectors in F2^n, ∞ fixed: constant on F_q
        # even weight ⇒ equal values ⇒ multiple of 1
        p2_odd = (q % 2 == 1)
        # computational: ker(T-I) on H0 for z->z+1 and z->z+ω
        pi_t1 = _mobius_perm(p, 1, 1, 0, 1)
        pi_tw = _mobius_perm(p, 1, p, 0, 1)
        inv_dim = 0
        # for each H0 basis vector, average over a generating set of translations
        # is expensive; instead solve (H0 t)[pi] = H0 t for both trans.
        # (M-I)t=0 on F2^k with H0 M = H0[pi,:].
        from walsh_ptgl_meataxe import action_matrices

        mats = action_matrices(H0, [pi_t1, pi_tw])
        # intersect ker(M-I)
        kers = []
        for M in mats:
            A = (M.astype(np.int32) + np.eye(k, dtype=np.int32)) % 2
            K, _ = gf2_nullspace(A.astype(np.uint8))
            kers.append(K)
        # intersect two kernels in F2^k
        if kers[0].size == 0 or kers[1].size == 0:
            dim_inv = 0
        else:
            # vectors in both column spaces
            A = np.concatenate([kers[0], kers[1]], axis=1)
            # better: each col of K0, test in colspan K1
            cols = []
            for j in range(kers[0].shape[1]):
                v = kers[0][:, j]
                aug = np.concatenate([kers[1], v[:, None]], axis=1)
                if gf2_rref(aug)[2] == gf2_rref(kers[1])[2]:
                    cols.append(v)
            if not cols:
                dim_inv = 0
            else:
                dim_inv = int(gf2_rref(np.stack(cols, axis=1))[2])
        ok = ok and in_H0 and p2_odd and dim_inv == 1
        rows[str(p)] = {
            "one_in_H0": in_H0,
            "dim_translation_invariants": dim_inv,
        }
    return {
        "proved": bool(ok),
        "rows": rows,
        "theorem": (
            "Unique 1-dim G_aff^□-invariant subspace of H0 is ⟨1⟩.  "
            "Fail: extra translation-invariant vector in H0."
        ),
    }


def theorem_C_inversion(primes=None) -> dict:
    """0-pencil permuted; H0 invariance certified at listed primes."""
    if primes is None:
        primes = (3, 5, 7, 11)
    ok = True
    rows = {}
    for p in primes:
        q, mul, add, chi, frob, norm, ia, ib = field_ctx(p)
        S = square_line_matrix(p)
        I = _mobius_perm(p, 0, 1, 1, 0)
        # 0-pencil: rows with field-0 (index 1) set
        pencil = [v for v in S if v[1] == 1]
        pencil_ok = all(
            any(np.array_equal(v[I], r) for r in S) for v in pencil
        )
        # a non-pencil row's image is NOT a row
        non = next(v for v in S if v[1] == 0)
        non_is_row = any(np.array_equal(non[I], r) for r in S)
        H0, _ = gf2_nullspace(S)
        Hg = H0[I, :]
        rH = gf2_rref(H0)[2]
        rAug = gf2_rref(np.concatenate([H0, Hg], axis=1))[2]
        preserve = rAug == rH
        Sv = (S.astype(np.int32) @ Hg.astype(np.int32)) % 2
        ker_ok = bool(Sv.max() == 0)
        ok = ok and pencil_ok and (not non_is_row) and preserve and ker_ok
        rows[str(p)] = {
            "pencil_permutes": pencil_ok,
            "nonpencil_image_is_row": non_is_row,
            "H0_preserved": preserve and ker_ok,
            "n_pencil": len(pencil),
            "half": (p + 1) // 2,
        }
        ok = ok and len(pencil) == (p + 1) // 2
    return {
        "proved": bool(ok),
        "H0_invariance_p_law": False,
        "rows": rows,
        "theorem": (
            "Inversion permutes the square-pencil through 0.  Fail: "
            "it permutes every row of S.  H0-invariance certified "
            "p=3,5,7,11, not a p-law."
        ),
    }


def theorem_D_open() -> dict:
    from e1_gmin_m4_prop15274 import residual_ii_k_eq_4p_empty
    from e1_gmin_m4_prop15278 import phi_F_ge_6_proved_general

    return {
        "proved": False,
        "walsh_general_p": False,
        "H0_quotient_irreducible": False,
        "residual_ii_k_eq_4p_empty": bool(residual_ii_k_eq_4p_empty()),
        "phi_F_ge_6": bool(phi_F_ge_6_proved_general()),
        "note": (
            "H0/⟨1⟩ irreducible as G-module would give "
            "dir(affine_span(Max−))=H0.  That is not Walsh.  "
            "15.406 E stays OPEN.  residual_ii stays False."
        ),
    }


def main() -> dict:
    t0 = time.time()
    print("Prop 15.602  square-affine module of H0=ker S", flush=True)
    A = theorem_A_affine_permutes()
    print(f"  A affine permutes rows: {A['proved']}", flush=True)
    B = theorem_B_unique_line()
    print(f"  B unique 1-dim invariant ⟨1⟩: {B['proved']}", flush=True)
    C = theorem_C_inversion()
    print(f"  C inversion pencil + H0 cert: {C['proved']}", flush=True)
    D = theorem_D_open()
    print(f"  D Walsh/irred open: resii={D['residual_ii_k_eq_4p_empty']}", flush=True)
    out = {
        "prop": "15.602",
        "title": "G_aff^□-module H0 has unique 1-dim invariant ⟨1⟩",
        "proved": {
            "affine_permutes_rows": A["proved"],
            "unique_1dim_invariant": B["proved"],
            "inversion_pencil": C["proved"],
            "H0_quotient_irreducible": False,
            "walsh_general_p": False,
        },
        "A": A,
        "B": B,
        "C": C,
        "D": D,
        "flags_not_flipped": [
            "residual_ii_k_eq_4p_empty",
            "phi_F_ge_6_proved_general",
            "e1",
            "L",
        ],
        "L_status": "OPEN",
        "walsh_15_406_E": "OPEN",
        "backend": "serial F2 (inherently for identities); rref p=3,5,7,11; GPU unused",
        "seconds": round(time.time() - t0, 3),
    }
    dest = ROOT / "evidence" / "e1_gmin_m4_prop15602.json"
    dest.write_text(json.dumps(out, indent=2, default=str) + "\n")
    print(f"  wrote {dest}", flush=True)
    return out


if __name__ == "__main__":
    main()
