#!/usr/bin/env python3
"""
Character-sum evaluation of E[y_a y_b y_c y_d] for Max+ of Paley conference.

Strategy: if Max+ is the Aut-orbit of the halfspace vector (or a union of
few orbits), then m4 = average over group elements of product of halfspace
values at four points.

We use the group G generated by:
  - translations of F_{p^2}
  - multiplications by F_{p^2}^*
  - Frobenius x |-> x^p
  - global sign (already in ± halfspace)

Compare orbit-average m4/G to full Max+ when available; if they match,
the group generates all of Max+ for correlation purposes (or full Max+).

Then extract closed form for min G on disjoint pairs.

Writes evidence/e1_gmin_char_sum.json
"""
from __future__ import annotations

import json
import sys
from itertools import combinations
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from minmax_quadratic import (  # noqa: E402
    halfspace_boolean_vector,
    paley_conference_prime_power,
)


def field_setup(p: int):
    q = p * p

    def is_irr(a, b):
        return all((x * x - a * x - b) % p != 0 for x in range(p))

    ia = ib = None
    for a in range(p):
        for b in range(p):
            if is_irr(a, b):
                ia, ib = a, b
                break
        if ia is not None:
            break

    def mul(u, v):
        c0, c1 = u % p, u // p
        d0, d1 = v % p, v // p
        e0 = (c0 * d0 + c1 * d1 * ib) % p
        e1 = (c0 * d1 + c1 * d0 + c1 * d1 * ia) % p
        return e0 + e1 * p

    def fpow(u, e):
        if u == 0:
            return 0
        r, base = 1, u
        while e:
            if e & 1:
                r = mul(r, base)
            base = mul(base, base)
            e >>= 1
        return r

    def chi(x):
        if x == 0:
            return 0
        return 1 if fpow(x, (q - 1) // 2) == 1 else -1

    def add(u, t):
        return ((u % p + t % p) % p) + (((u // p) + (t // p)) % p) * p

    return mul, fpow, chi, add, q


def build_orbit(p: int, max_mult: int | None = None) -> np.ndarray:
    mul, fpow, chi, add, q = field_setup(p)
    x0 = halfspace_boolean_vector(p)
    n = q + 1
    vectors = []

    mults = list(range(1, q))
    if max_mult is not None and len(mults) > max_mult:
        rng = np.random.default_rng(0)
        mults = list(rng.choice(mults, size=max_mult, replace=False))

    for m in mults:
        for t in range(q):
            for fro in (0, 1):
                y = np.ones(n, dtype=np.float64)
                y[0] = x0[0]
                for u in range(q):
                    uu = fpow(u, p) if fro else u
                    v = mul(m, uu)
                    w = add(v, t)
                    y[1 + w] = x0[1 + u]
                vectors.append(y.copy())
                vectors.append((-y).copy())

    arr = np.unique(np.round(np.asarray(vectors)).astype(int), axis=0).astype(float)
    C = paley_conference_prime_power(p)
    good = [y for y in arr if np.allclose(C @ y, float(p) * y, atol=1e-5)]
    return np.unique(np.round(good).astype(int), axis=0).astype(float)


def gmin_of(C: np.ndarray, Mp: np.ndarray) -> float:
    n = C.shape[0]
    edges = [(i, j) for i in range(n) for j in range(i + 1, n)]
    Chip = np.array(
        [[C[a, b] * y[a] * y[b] for a, b in edges] for y in Mp], dtype=np.float64
    )
    G = (Chip.T @ Chip) / len(Mp)
    gmin = 1.0
    for ei, (i, j) in enumerate(edges):
        for ej in range(ei + 1, len(edges)):
            k, l = edges[ej]
            if len({i, j, k, l}) == 4:
                gmin = min(gmin, float(G[ei, ej]))
    return gmin


def main() -> None:
    out = {"orbits": [], "status": None}
    for p in (3, 5):
        print(f"building orbit p={p}", flush=True)
        orb = build_orbit(p, max_mult=None)
        C = paley_conference_prime_power(p)
        print(f"  orbit evecs: {len(orb)}", flush=True)
        g_orb = gmin_of(C, orb) if len(orb) else None
        g_full = None
        cache = Path(f"/tmp/maxplus_p{p}.npy") if p == 5 else None
        if p == 3:
            from e1_bitight_infeas import boolean_evecs

            full = boolean_evecs(C, float(p), 0)
            g_full = gmin_of(C, full)
            n_full = len(full)
        elif cache and cache.is_file():
            full = np.load(cache).astype(float)
            g_full = gmin_of(C, full)
            n_full = len(full)
        else:
            n_full = None
        row = {
            "p": p,
            "orbit_size": int(len(orb)),
            "full_size": n_full,
            "g_min_orbit": g_orb,
            "g_min_full": g_full,
            "orbit_matches_full_gmin": (
                g_orb is not None
                and g_full is not None
                and abs(g_orb - g_full) < 1e-9
            ),
            "orbit_complete": n_full is not None and len(orb) == n_full,
        }
        out["orbits"].append(row)
        print(row, flush=True)

    # p=5: if orbit complete, character sum = full average
    out["status"] = (
        "Affine+Frob orbit of halfspace vs full Max+. "
        "If orbit_complete and gmin matches, closed form via character sum is valid."
    )
    path = ROOT / "evidence" / "e1_gmin_char_sum.json"
    path.write_text(json.dumps(out, indent=2))
    print(json.dumps(out, indent=2))
    print("wrote", path)


if __name__ == "__main__":
    main()
