#!/usr/bin/env python3
"""Prop. 15.719 -- finite projected-semigroup stabilization for p7 z=7.

The Johnson-semigroup Hilbert basis certified in Proposition 15.718 has
maximum generator grade three.  Hence equality of four consecutive projected
layers proves permanent stabilization in the finite projected group.  The
exact k=3 and k=4 certificates have equal raw and anchor-relative supports on
grades three through six, and identify the resulting support subgroups.

Because every Hilbert generator is binary, these projected catalogs are
cap-exact through grade six.  Grade eight remains an outer support only, so
this proposition excludes no boundary: all 56 positive z=7 boundaries and the
quadratic-minmax-limit theorem remain open.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from e1_gmin_m4_prop15718 import (
    p7_positive_infinity_plus_seven_z7_global_semigroup_reduction,
)


ROOT = Path(__file__).resolve().parents[1]
SUMMARY = (
    ROOT
    / "evidence"
    / "p7_infinity7_positive_z7_projected_stabilization_summary.json"
)
SUMMARY_SHA256 = "94bb789345e8d8dbb945dd8c2c5d77cdf8b77c231ed0c360d2bdf196ea8c1b5b"


def _integer_keyed(row: dict[str, object]) -> dict[int, int]:
    return {int(key): int(value) for key, value in row.items()}


def p7_positive_infinity_plus_seven_z7_projected_stabilization() -> dict[str, object]:
    """Validate and expose the exact projected stabilization certificate."""
    previous = p7_positive_infinity_plus_seven_z7_global_semigroup_reduction()
    raw_summary = SUMMARY.read_bytes()
    if hashlib.sha256(raw_summary).hexdigest() != SUMMARY_SHA256:
        raise ArithmeticError("p7 positive z7 projected-stabilization summary changed")
    summary = json.loads(raw_summary)

    if (
        summary["experiment"]
        != "p7_infinity7_positive_z7_projected_semigroup_stabilization"
        or summary["status"]
        != "complete_exact_finite_projected_semigroup_stabilization_certificate"
        or int(summary["p"]) != 7
        or int(summary["z"]) != 7
        or int(summary["phase"]) != 0
        or summary["script"]
        != "scripts/p7_infinity7_positive_z7_high_semigroup_support.py"
        or summary["script_sha256"]
        != "718bc28c3f62395b0c581d9773ba42bcef1f2b05d8f6e10fdd11b254703ce256"
    ):
        raise ArithmeticError("p7 positive z7 projected certificate identity changed")

    hilbert = summary["hilbert_basis"]
    generator_histogram = _integer_keyed(hilbert["generator_grade_histogram"])
    if (
        int(hilbert["rows"]) != 896
        or generator_histogram != {1: 56, 2: 168, 3: 672}
        or sum(generator_histogram.values()) != int(hilbert["rows"])
        or max(generator_histogram) != 3
        or hilbert["generator_file_sha256"]
        != "3b582d6a0e7c83cb8ed41a421e4950be2645ce2d3aa18dab17432628b787b789"
    ):
        raise ArithmeticError("p7 positive z7 Hilbert-basis input changed")

    lemma = summary["finite_stabilization_lemma"]
    maximum_generator_grade = int(lemma["maximum_generator_grade"])
    equal_layers_required = int(lemma["required_consecutive_equal_layers"])
    if (
        maximum_generator_grade != max(generator_histogram)
        or maximum_generator_grade != 3
        or equal_layers_required != maximum_generator_grade + 1
        or equal_layers_required != 4
        or lemma["hypothesis"]
        != (
            "the projected Hilbert basis has maximum grade d and T_r through "
            "T_(r+d) are the same finite set S"
        )
        or lemma["conclusion"]
        != (
            "T_g equals S for every g at least r, and S is the subgroup "
            "generated by all projected Hilbert generators"
        )
        or lemma["proof_uses_finite_translation_injectivity"] is not True
    ):
        raise ArithmeticError("finite projected-semigroup stabilization lemma changed")

    expected_projections = {
        (0, 1, 2): {
            "projected_group": "F3^6 x F7^3",
            "projected_group_size": 250_047,
            "directions": {
                0: 147,
                1: 147,
                2: 147,
                3: 147,
                4: 147,
                5: 3,
                6: 3,
                7: 3,
            },
            "artifact_sha256": (
                "e9cd5f24a9ec6961404b95e1240abb44a21d0ef4e5d78c9fc0324f643edce079"
            ),
        },
        (0, 1, 2, 3): {
            "projected_group": "F3^6 x F7^4",
            "projected_group_size": 1_750_329,
            "directions": {
                0: 1_029,
                1: 1_029,
                2: 1_029,
                3: 1_029,
                4: 1_029,
                5: 21,
                6: 3,
                7: 3,
            },
            "artifact_sha256": (
                "8a3f58c2728421458821dc6207928836c085b49ea35018abd2c8587b7adacf53"
            ),
        },
    }
    observed_projections: dict[tuple[int, ...], dict[str, object]] = {}
    for certificate in summary["projection_certificates"]:
        coordinates = tuple(int(value) for value in certificate["retained_mod7_coordinates"])
        if coordinates in observed_projections:
            raise ArithmeticError("duplicate projected-semigroup certificate")
        observed_projections[coordinates] = {
            "projected_group": certificate["projected_group"],
            "projected_group_size": int(certificate["projected_group_size"]),
            "directions": _integer_keyed(certificate["directions"]),
            "artifact_sha256": certificate["artifact_sha256"],
        }
        if (
            certificate["all_raw_support_hashes_equal_grades_three_through_six"]
            is not True
            or certificate[
                "all_anchor_relative_support_hashes_equal_grades_three_through_six"
            ]
            is not True
        ):
            raise ArithmeticError("projected support failed four-layer stabilization")
    if observed_projections != expected_projections:
        raise ArithmeticError("projected support subgroup orders changed")

    caps = summary["cap_semantics"]
    if caps != {
        "binary_hilbert_generators_make_catalog_projection_exact_through_grade_six": True,
        "grade_eight_projection_is_outer_support_only": True,
        "projected_presence_proves_capped_grade_eight_feasibility": False,
    }:
        raise ArithmeticError("projected support cap semantics changed")

    semantics = summary["logical_semantics"]
    if semantics != {
        "all_grade_three_through_six_high_catalog_projections_identified_exactly": True,
        "finite_projected_stabilization_closes_binary_edge_feasibility": False,
        "positive_z7_closed": False,
        "target_presence_is_necessary_only": True,
    }:
        raise ArithmeticError("projected stabilization logical semantics changed")

    actual = summary["actual_boundary_status"]
    if actual != {
        "positive_p7_infinity_plus_seven_closed": False,
        "remaining_actual_line_boundaries": 56,
        "remaining_actual_line_orbits": 2,
        "top_level_gates_changed": False,
    }:
        raise ArithmeticError("projected stabilization boundary status changed")

    if (
        previous["proposition"] != "15.718"
        or previous["johnson_semigroup_hilbert_basis_rows"] != 896
        or previous["johnson_semigroup_generator_grade_histogram"]
        != generator_histogram
        or previous["actual_line_boundary_count_after"] != 56
        or previous["remaining_actual_undetermined_direction_histogram"] != {7: 56}
        or previous["remaining_actual_boundary_orbits"] != {7: 2}
        or previous["positive_z7_branch_closed"] is not False
        or previous["quadratic_minmax_limit_theorem_closed"] is not False
    ):
        raise ArithmeticError("pre-15.719 positive z7 remainder changed")

    return {
        "proposition": "15.719",
        "chains_from_proposition": previous["proposition"],
        "p": 7,
        "boundary": "infinity plus seven finite points",
        "product_sign": "positive",
        "undetermined_direction_count": 7,
        "summary_evidence": str(SUMMARY.relative_to(ROOT)),
        "summary_evidence_sha256": SUMMARY_SHA256,
        "maximum_hilbert_generator_grade": maximum_generator_grade,
        "required_consecutive_equal_layers": equal_layers_required,
        "stabilized_layer_interval": [3, 4, 5, 6],
        "finite_stabilization_proves_all_later_uncapped_layers": True,
        "stabilized_support_is_generated_subgroup": True,
        "projection_support_subgroup_orders": {
            coordinates: row["directions"]
            for coordinates, row in observed_projections.items()
        },
        "projection_group_sizes": {
            coordinates: row["projected_group_size"]
            for coordinates, row in observed_projections.items()
        },
        "raw_support_equal_grades_three_through_six": True,
        "anchor_relative_support_equal_grades_three_through_six": True,
        "high_catalog_projection_exact_through_grade_six": True,
        "grade_eight_projection_is_outer_support_only": True,
        "projected_presence_proves_capped_grade_eight_feasibility": False,
        "target_presence_is_necessary_only": True,
        "binary_edge_feasibility_closed": False,
        "actual_line_boundary_count_before": 56,
        "actual_line_boundaries_excluded_here": 0,
        "actual_line_boundary_count_after": 56,
        "remaining_actual_undetermined_direction_histogram": {7: 56},
        "remaining_actual_boundary_orbits": {7: 2},
        "positive_z7_branch_closed": False,
        "positive_p7_infinity_plus_seven_closed": False,
        "quadratic_minmax_limit_theorem_closed": False,
        "theorem_remains_open": True,
        "top_level_gates_changed": False,
        "proved_by_exact_finite_projected_semigroup_stabilization": True,
    }


def main() -> None:
    theorem = p7_positive_infinity_plus_seven_z7_projected_stabilization()
    print(
        "Prop. 15.719: p7 positive z=7 projected supports stabilize from "
        f"grade {theorem['stabilized_layer_interval'][0]}; z=7 remains open"
    )


if __name__ == "__main__":
    main()
