#!/usr/bin/env python3
r"""Prop. 15.760 -- the integral edge-Radon image is cut out by moments.

Fix an odd prime ``p=2m+1``, put ``V=F_p^2``, and choose one nonzero
functional in every projective direction ``L``.  The unsigned edge-Radon
map

    R : E=Z^{binom(V,2)} -> T

records, in direction ``L``, the number ``P_L`` of parallel edges and the
number ``K_L(s,t)`` of edges over every unordered off-diagonal fibre pair.
Write

    T_L=P_L+sum_(s<t) K_L(s,t).

The *ordinary compatibility lattice* is

    A={y in T : all T_L have one value h, and sum_L P_L=h}.       (1)

Then ``R(E)`` lies in ``A``.  Proposition 15.759 found ``S(p)`` independent
mod-``p`` moment equations on ``A/R(E)``, where

    S(p)=(m-1)(4m^2+7m+6)/6.                                   (2)

This proposition proves that those equations are also sufficient over the
integers:

    A/R(E) = (Z/pZ)^{S(p)}.                                    (3)

Consequently an integral target is in ``R(E)`` if and only if it satisfies
(1) and every moment congruence of Proposition 15.759.  In particular there
is no hidden ``p^2`` obstruction and no torsion at a prime other than ``p``.

Here is a self-contained lattice proof, including the primitivity and
quotient points which a rank computation alone would not establish.

Primitive ordinary lattice.
---------------------------
Let ``d=p+1`` and index the ``pm=binom(p,2)`` off-diagonal cells in each
direction by

    alpha=(s+t)/2 in F_p,
    beta=((s-t)/2)^2 in QR(F_p)^*.

Choose a base cell ``c_0`` in every direction.  Relative to one base
direction ``L_0``, define an integral constraint map

    F:T -> Z^d,
    F_L=T_L-T_(L_0)                       (L != L_0),
    F_*=sum_L P_L-T_(L_0).

It is split surjective.  A base off-diagonal cell in direction ``L != L_0``
maps to the corresponding first coordinate, and

    P_L-K_L(c_0)

maps to the last coordinate while all the first coordinates vanish.  Thus
``A=ker F`` is primitive in ``T``.  More explicitly it has the integral
basis

    K_L(c)-K_L(c_0)                         (c != c_0),
    g_M=P_M+sum_(L != M) K_L(c_0)           (all M).             (4)

Indeed the parallel coordinates recover the coefficients of the ``g_M``;
their sum is ``h``, and in direction ``L`` the ``g_M`` contribute
``h-P_L`` to the base cell, exactly the required off-diagonal total.
The basis has ``d(pm-1)+d=dpm`` elements, the rank of (1).

Difference quotient.
--------------------
Let ``pi:A->A_D`` sum the ``K_L(alpha,beta)`` coordinates over ``alpha``
for each ``(L,beta)`` and retain ``P_L``.  Its image is the ordinary lattice
with ``m`` value cells per direction.  It has the basis

    e_(L,beta)-e_(L,beta_0),
    g_M^D=P_M+sum_(L != M)e_(L,beta_0),                         (5)

and rank ``dm``.  The kernel ``M`` is freely generated by

    K_L(alpha,beta)-K_L(alpha_0,beta),                          (6)

so ``rank M=dm(p-1)`` and

    0 -> M -> A -> A_D -> 0                                   (7)

is exact over the integers, not merely over a field.

Every edge has a unique midpoint ``a`` and a nonzero half-difference class
``[delta]`` modulo sign.  Let ``D=Z^Delta`` for

    Delta=(V\{0})/{+1,-1},       |Delta|=(p^2-1)/2=dm,

and let ``sigma:E->D`` forget the midpoint.  It is split surjective and its
kernel ``E_0`` consists of the coefficient arrays having sum zero over the
midpoints for each ``[delta]``.  Hence

    0 -> E_0 -> E -> D -> 0                                    (8)

is exact.  The induced pure-difference map is

    S e_[delta]
      =P_(L_delta)+sum_(L != L_delta)e_(L,L(delta)^2),          (9)

where ``L_delta`` is the unique direction with ``L_delta(delta)=0``.
Equations (7)--(9) form a commutative diagram with vertical maps
``R_0,R,S``; commutativity is simply ``pi R=S sigma``.

Smith form of the difference quotient.
--------------------------------------
The row supports of (9) have the following exact intersections.  A value
row has size ``p`` and a parallel row size ``m``.  In distinct directions,
two value rows meet in two half-difference classes, a value and a parallel
row meet in one, and two parallel rows do not meet.  Different categories
in one direction are disjoint.  Therefore, with ``S`` also denoting its
incidence matrix,

    S S^t(e_(L,beta)-e_(L,beta_0))
      =p(e_(L,beta)-e_(L,beta_0)).                             (10)

This puts ``p`` times every difference generator in ``im S``.  For (5),
choose ``[delta]`` parallel to ``M``.  Its column (9) differs from ``g_M^D``
only by value-difference generators.  Multiplying this equality by ``p``
and applying (10) gives ``p g_M^D in im S``.  Hence

    p A_D subset im S.                                        (11)

Both ``D`` and ``A_D`` have rank ``dm``.  Thus (11) makes ``S`` full rank,
and equality of ranks makes it injective.

Modulo ``p``, the dual of one direction block has the even-function basis

    1, L(delta)^2, ..., L(delta)^(2m).

The constant contributes one common row.  For fixed ``1<=b<=m``, the
``p+1`` projective powers ``L(delta)^(2b)`` span the binary forms of degree
``2b`` and have rank ``2b+1``.  At ``b=m`` this is ``p``, not ``p+1``;
the constant is still disjoint from that block, as proved in 15.759 by the
finite-chart roots plus the infinity point.  Therefore

    rank_Fp S = 1+sum_(b=1)^m(2b+1)=(m+1)^2,
    dim_Fp coker(S mod p)=dm-(m+1)^2=m^2-1.                   (12)

Together (11)--(12) give

    coker S = (Z/pZ)^{m^2-1}.                                 (13)

Smith form of the midpoint kernel.
----------------------------------
The dual basis to (6), modulo functions constant in ``alpha``, is

    alpha^i beta^b,       1<=i<=p-1, 1<=b<=m.                 (14)

Its pullback is ``L(a)^i L(delta)^(2b)``.  Restriction to ``E_0`` loses no
positive-midpoint-degree block: if a combination is constant in ``a`` for
each ``delta``, evaluating at ``a=0`` says that constant is zero, and the
block independence proved in 15.759 then says the combination itself is
zero.  For fixed ``(i,b)``, the projective directional rank is therefore

    min(p+1,i+2b+1).

The mod-``p`` defect of ``R_0`` is exactly

    S_0=sum_(b=1)^(m-1) sum_(i=1)^(p-2b-1)(p-i-2b)
       =sum_(c=1)^(m-1)c(2c+1)
       =m(m-1)(4m+1)/6.                                      (15)

There is also an integral exponent certificate.  Fix ``L,beta`` and choose
``delta`` with ``L(delta)^2=beta``.  For ``alpha in F_p`` set

    X_alpha=sum_(a:L(a)=alpha) {a-delta,a+delta}.

Each sum has ``p`` edges with the same half-difference, so
``X_alpha-X_alpha'`` belongs to ``E_0``.  In direction ``L`` its image is

    p(K_L(alpha,beta)-K_L(alpha',beta)).                       (16)

In every other direction it cancels: if that direction is parallel to
``delta`` both sums contain ``p`` parallel edges; otherwise its midpoint
runs once through all of ``F_p`` at fixed projected difference.  Thus (16)
holds in the *full* target, and (6) shows

    pM subset im R_0.                                         (17)

Equations (15)--(17) yield

    coker R_0=(Z/pZ)^{S_0}.                                   (18)

Snake lemma and the exponent.
--------------------------------
Apply the snake lemma to (7)--(9).  Since ``ker S=0``, its relevant tail is

    0 -> coker R_0 -> coker R -> coker S -> 0.                 (19)

Thus ``G=A/R(E)`` is a finite ``p``-group and

    |G|=p^{S_0+m^2-1}=p^{S(p)},                               (20)

because

    S_0+m^2-1=(m-1)(4m^2+7m+6)/6.

Proposition 15.759 gives independently

    dim_Fp(G/pG)=S(p),                                        (21)

the number of its independent moment rows after the ordinary rows have
been removed.  If the invariant factors of ``G`` are ``p^{a_1},...,p^{a_r}``,
then (21) says ``r=S(p)``, while (20) says ``sum a_j=S(p)``.  Every
``a_j>=1``, hence every ``a_j=1``.  This proves (3).  The ``S(p)`` moment
rows induce an injective map from the group (3) to ``F_p^{S(p)}``; equal
orders make it an isomorphism and prove the stated if-and-only-if criterion.

The normalized residual map differs from ``R`` by diagonal signs on source
edges and direction blocks.  Those matrices are unimodular, so the theorem
transports verbatim after inserting the outer direction signs specified in
15.759.  Proposition 15.757's binary theorem is consistent with (3): since
``p`` is odd, this cokernel has no binary residue.

What this does *not* prove.
--------------------------
The theorem gives an unrestricted signed integral lift.  If ``tau_e`` is
the edge-column sign, a simple graph requires the normalized source
coordinate to lie in ``{0,tau_e}``, not merely in ``Z``.  Once one integral
lift ``z_0`` is found, the remaining problem is exactly

    (z_0+ker_Z R) intersect product_e {0,tau_e} != empty.      (22)

Thus all linear divisibility and Smith-form obstructions are now exhausted;
the live obstruction is a sign-compatible, nonnegative ``0/1`` affine-
lattice intersection.  In particular this proposition does not assert that
the compact aggregate rays of 15.758 pass every moment row.  Direct atom
substitution currently proves all rows only through degree four; degree five
and above remain live.  Nor does this proposition assert a simple lift.
Residual (ii) remains open.
"""
from __future__ import annotations

from fractions import Fraction


Polynomial = tuple[Fraction, ...]


def _trim(poly: Polynomial) -> Polynomial:
    values = list(poly)
    while len(values) > 1 and values[-1] == 0:
        values.pop()
    return tuple(values)


def _add(left: Polynomial, right: Polynomial) -> Polynomial:
    size = max(len(left), len(right))
    return _trim(
        tuple(
            (left[index] if index < len(left) else Fraction(0))
            + (right[index] if index < len(right) else Fraction(0))
            for index in range(size)
        )
    )


def _neg(poly: Polynomial) -> Polynomial:
    return tuple(-coefficient for coefficient in poly)


def _sub(left: Polynomial, right: Polynomial) -> Polynomial:
    return _add(left, _neg(right))


def _mul(left: Polynomial, right: Polynomial) -> Polynomial:
    out = [Fraction(0)] * (len(left) + len(right) - 1)
    for left_degree, left_coefficient in enumerate(left):
        for right_degree, right_coefficient in enumerate(right):
            out[left_degree + right_degree] += left_coefficient * right_coefficient
    return _trim(tuple(out))


def _scale(poly: Polynomial, scalar: Fraction | int) -> Polynomial:
    return _trim(tuple(Fraction(scalar) * coefficient for coefficient in poly))


def _serialise(poly: Polynomial) -> list[int | str]:
    return [
        int(coefficient)
        if coefficient.denominator == 1
        else f"{coefficient.numerator}/{coefficient.denominator}"
        for coefficient in poly
    ]


def symbolic_rank_identities() -> dict[str, object]:
    """Verify every rank and defect identity as a polynomial in ``m``.

    No prime is instantiated and no finite case is scanned.  Coefficients
    are listed in increasing degree order.
    """
    one: Polynomial = (Fraction(1),)
    m: Polynomial = (Fraction(0), Fraction(1))
    p = _add(one, _scale(m, 2))
    directions = _add(_scale(one, 2), _scale(m, 2))
    p_minus_one = _sub(p, one)
    difference_classes = _mul(directions, m)
    p_squared = _mul(p, p)

    ordinary_rank = _mul(_mul(directions, p), m)
    ordinary_target = _mul(directions, _add(_mul(p, m), one))
    ordinary_codimension = _sub(ordinary_target, ordinary_rank)
    ordinary_basis_count = _add(
        _mul(directions, _sub(_mul(p, m), one)), directions
    )

    midpoint_rank = _mul(difference_classes, p_minus_one)
    quotient_rank = difference_classes
    edge_rank_by_fibres = _mul(difference_classes, p_squared)
    edge_rank_by_pairs = _scale(_mul(p_squared, _sub(p_squared, one)), Fraction(1, 2))

    quotient_mod_p_rank = _mul(_add(m, one), _add(m, one))
    quotient_defect = _sub(quotient_rank, quotient_mod_p_rank)
    midpoint_defect = _scale(
        _mul(_mul(m, _sub(m, one)), _add(_scale(m, 4), one)),
        Fraction(1, 6),
    )
    total_defect = _add(midpoint_defect, quotient_defect)
    prop15759_defect = _scale(
        _mul(
            _sub(m, one),
            _add(_add(_scale(_mul(m, m), 4), _scale(m, 7)), _scale(one, 6)),
        ),
        Fraction(1, 6),
    )

    checks = {
        "ordinary_basis_has_full_lattice_rank": ordinary_basis_count == ordinary_rank,
        "ordinary_codimension_is_p_plus_one": ordinary_codimension == directions,
        "kernel_plus_quotient_rank_is_ordinary_rank": (
            _add(midpoint_rank, quotient_rank) == ordinary_rank
        ),
        "edge_midpoint_fibres_count_all_edges": edge_rank_by_fibres == edge_rank_by_pairs,
        "difference_quotient_defect_is_m_squared_minus_one": (
            quotient_defect == _sub(_mul(m, m), one)
        ),
        "snake_defects_equal_prop15759": total_defect == prop15759_defect,
    }
    if not all(checks.values()):
        raise ArithmeticError("an all-prime lattice polynomial identity changed")
    return {
        "coefficient_order": "constant_to_highest_degree_in_m",
        "p": _serialise(p),
        "directions_p_plus_one": _serialise(directions),
        "difference_class_count": _serialise(difference_classes),
        "ordinary_lattice_rank": _serialise(ordinary_rank),
        "midpoint_kernel_rank": _serialise(midpoint_rank),
        "difference_quotient_rank": _serialise(quotient_rank),
        "difference_quotient_mod_p_rank": _serialise(quotient_mod_p_rank),
        "difference_quotient_defect": _serialise(quotient_defect),
        "midpoint_kernel_defect": _serialise(midpoint_defect),
        "total_defect": _serialise(total_defect),
        "prop15759_defect": _serialise(prop15759_defect),
        "checks": checks,
        "proved": True,
    }


def ordinary_lattice_certificate() -> dict[str, object]:
    """Record the split constraint map and the integral basis (4)."""
    return {
        "constraint_map": (
            "F_L=T_L-T_L0 (L!=L0); F_*=sum_L P_L-T_L0"
        ),
        "kernel": "A, the ordinary equal-total/parallel-sum lattice",
        "surjection_witnesses": {
            "direction_coordinate_L": "K_L(c0)",
            "last_coordinate": "P_L-K_L(c0), for any L!=L0",
        },
        "integral_basis": [
            "K_L(c)-K_L(c0), for c!=c0",
            "g_M=P_M+sum_(L!=M)K_L(c0), for every M",
        ],
        "basis_count": "(p+1)(p*m-1)+(p+1)=(p+1)p*m",
        "split_surjective_constraint_map": True,
        "ordinary_lattice_is_primitive": True,
        "proved": True,
    }


def difference_quotient_certificate() -> dict[str, object]:
    """Record exactness, the Gram calculation, and the quotient Smith form."""
    return {
        "exact_sequence": "0 -> M -> A -> A_D -> 0",
        "quotient_map": "sum midpoint alpha at fixed (L,beta), retain P_L",
        "kernel_basis": "K_L(alpha,beta)-K_L(alpha0,beta)",
        "quotient_basis": [
            "e_(L,beta)-e_(L,beta0)",
            "g_M^D=P_M+sum_(L!=M)e_(L,beta0)",
        ],
        "row_support_intersections": {
            "value_size": "p",
            "parallel_size": "m",
            "distinct_direction_value_value": 2,
            "distinct_direction_value_parallel": 1,
            "distinct_direction_parallel_parallel": 0,
            "same_direction_distinct_categories": 0,
        },
        "gram_identity": "SS^t(e_L,beta-e_L,beta0)=p(e_L,beta-e_L,beta0)",
        "p_times_quotient_lattice_in_image": True,
        "source_and_target_rank": "(p+1)m",
        "S_is_injective": True,
        "rank_mod_p": "(m+1)^2",
        "cokernel": "(Z/pZ)^(m^2-1)",
        "proved": True,
    }


def midpoint_kernel_certificate() -> dict[str, object]:
    """Record the positive-midpoint blocks and exact matching (16)."""
    return {
        "source_exact_sequence": "0 -> E_0 -> E -> Z^Delta -> 0",
        "target_kernel_basis": "K_L(alpha,beta)-K_L(alpha0,beta)",
        "dual_blocks": "alpha^i beta^b, 1<=i<=p-1, 1<=b<=m",
        "directional_block_rank": "min(p+1,i+2b+1)",
        "mod_p_defect_double_sum": (
            "sum_(b=1)^(m-1)sum_(i=1)^(p-2b-1)(p-i-2b)"
        ),
        "mod_p_defect_closed": "m(m-1)(4m+1)/6",
        "matching_chain": (
            "X_alpha=sum_(a:L(a)=alpha){a-delta,a+delta}"
        ),
        "matching_image": (
            "R_0(X_alpha-X_alpha')=p(K_L(alpha,beta)-K_L(alpha',beta))"
        ),
        "other_directions_cancel_exactly": True,
        "p_times_midpoint_lattice_in_image": True,
        "cokernel": "(Z/pZ)^[m(m-1)(4m+1)/6]",
        "proved": True,
    }


def smith_extension_certificate() -> dict[str, object]:
    """Record the snake-lemma and invariant-factor conclusion."""
    return {
        "commutative_identity": "pi R=S sigma",
        "snake_tail": "0 -> coker R_0 -> coker R -> coker S -> 0",
        "snake_injection_reason": "S is injective over Z",
        "cokernel_order": "p^[(m-1)(4m^2+7m+6)/6]",
        "minimum_generator_count_from_prop15759": (
            "(m-1)(4m^2+7m+6)/6"
        ),
        "exponent_argument": (
            "if invariant factors are p^a_j, their count and sum a_j both "
            "equal S(p), so every a_j=1"
        ),
        "full_cokernel": "(Z/pZ)^[(m-1)(4m^2+7m+6)/6]",
        "no_other_prime_torsion": True,
        "no_p_squared_torsion": True,
        "proved": True,
    }


def integral_image_criterion() -> dict[str, object]:
    """State the exact integer criterion and the remaining box constraint."""
    return {
        "unsigned_integral_image_iff": [
            "all directional totals are one h",
            "sum of parallel coordinates is h",
            "every Proposition 15.759 moment congruence vanishes modulo p",
        ],
        "moment_map_on_cokernel": "isomorphism to F_p^S(p)",
        "signed_transport": (
            "unimodular edge-column and direction-row sign matrices"
        ),
        "binary_prop15757_consistency": (
            "the cokernel is p-primary with p odd, so it has no mod-2 residue"
        ),
        "simple_graph_normalized_domain": "z_e in {0,tau_e}",
        "simple_lift_iff": (
            "(z_0+ker_Z R) intersects product_e {0,tau_e}"
        ),
        "all_linear_congruence_obstructions_exhausted": True,
        "simple_nonnegative_lift_proved": False,
        "compact_prop15758_rays_pass_all_moments_proved": False,
        "proved": True,
    }


def theorem_record() -> dict[str, object]:
    symbolic = symbolic_rank_identities()
    ordinary = ordinary_lattice_certificate()
    quotient = difference_quotient_certificate()
    midpoint = midpoint_kernel_certificate()
    extension = smith_extension_certificate()
    criterion = integral_image_criterion()
    proved = bool(
        symbolic["proved"]
        and ordinary["proved"]
        and quotient["proved"]
        and midpoint["proved"]
        and extension["proved"]
        and criterion["proved"]
    )
    return {
        "prop": "15.760",
        "title": "Integral edge-Radon image cut out exactly by moments",
        "status": "PROVED INTEGRAL IMAGE THEOREM AND OPEN 0/1 REDUCTION",
        "cokernel": "(Z/pZ)^[(m-1)(4m^2+7m+6)/6]",
        "symbolic_rank_identities": symbolic,
        "ordinary_lattice": ordinary,
        "difference_quotient": quotient,
        "midpoint_kernel": midpoint,
        "snake_and_smith": extension,
        "integral_image": criterion,
        "proved": {
            "ordinary_lattice_primitive": proved,
            "integer_quotient_sequences_exact": proved,
            "difference_and_midpoint_cokernels_elementary_p": proved,
            "full_cokernel_elementary_p": proved,
            "prop15759_moments_are_integer_image_sufficient": proved,
            "signed_residual_transport": proved,
            "compact_aggregate_survivor_has_simple_lift": False,
            "residual_ii_closed": False,
            "e1_closed_general": False,
            "L": False,
        },
        "remaining_obstruction": (
            "First decide every Prop. 15.759 moment row for the 15.758 atom "
            "families; conditional on passing, decide the sign-compatible "
            "0/1 intersection (z_0+ker_Z R) cap product_e {0,tau_e}."
        ),
        "duplicate_work_guards": [
            "Do not search for another linear integer congruence after the complete moment list.",
            "Do not infer a 0/1 graph from an unrestricted signed integral lift.",
            "Do not claim the 15.758 rays pass the degree-five and higher moment gates.",
        ],
        "L_status": "OPEN",
    }


def main() -> dict[str, object]:
    out = theorem_record()
    print("Prop. 15.760 integral edge-Radon image: proved")
    print("  simple nonnegative 0/1 lift: OPEN")
    return out


if __name__ == "__main__":
    main()
