#!/usr/bin/env python3
"""Exact real-cone semimetric separation for one p=31 transverse row.

The compact atom ``K(a,b;c)=e_ab-e_ac-e_bc`` is the outward normal of a
semimetric triangle inequality.  Since ``-2e_ab`` is the sum of the two
compact atoms distinguished at ``a`` and ``b`` on any third label, the real
cone generated by compact atoms is exactly the polar of the semimetric cone.

Consequently a compact-only row ``x`` is fractionally atom-decomposable iff

    <x,d> <= 0

for every semimetric ``d`` (together with the fixed edge-sum identity that
pins the atom count).  For an opposite row with six all-positive triangles,
the exact real relaxation is

    <x,d> <= 6 max_{a<b<c}(d_ab+d_ac+d_bc).

The LP normalizes ``sum d=1``.  A positive optimum returns a reusable learned
GPU cut; after it is learned, a cell mutation changes its score by the single
multiply-add ``delta*d_uv``.  Integral atom normality is not asserted.
"""

from __future__ import annotations

from functools import lru_cache
import json
from itertools import combinations
from typing import Mapping

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import coo_matrix, csr_matrix

from e1_gmin_m4_p31_row_atom_incremental_bound import (
    AtomRowSpec,
    IncrementalAtomRowBound,
    LabelEdge,
)


P = 31
EDGES: tuple[LabelEdge, ...] = tuple(combinations(range(P), 2))
EDGE_INDEX = {edge: index for index, edge in enumerate(EDGES)}
TRIPLES: tuple[tuple[int, int, int], ...] = tuple(
    combinations(range(P), 3)
)


def _coefficient_vector(
    coefficients: Mapping[LabelEdge, int],
) -> np.ndarray:
    vector = np.zeros(len(EDGES), dtype=np.float64)
    for edge, value in coefficients.items():
        key = tuple(sorted((int(edge[0]), int(edge[1]))))
        if key not in EDGE_INDEX:
            raise ValueError("a row coefficient has an invalid label edge")
        if not isinstance(value, int) or isinstance(value, bool):
            raise ValueError("row coefficients must be integers")
        vector[EDGE_INDEX[key]] += value
    return vector


@lru_cache(maxsize=2)
def _semimetric_constraints(
    with_triangle_perimeter: bool,
) -> tuple[csr_matrix, np.ndarray, np.ndarray, list[tuple[float | None, float | None]]]:
    """Build the sparse normalized semimetric LP matrix once."""
    distance_variables = len(EDGES)
    variable_count = distance_variables + int(with_triangle_perimeter)
    row_indices: list[int] = []
    column_indices: list[int] = []
    data: list[float] = []
    row = 0
    for first, second, third in TRIPLES:
        ab = EDGE_INDEX[(first, second)]
        ac = EDGE_INDEX[(first, third)]
        bc = EDGE_INDEX[(second, third)]
        for positive, negative_first, negative_second in (
            (ab, ac, bc),
            (ac, ab, bc),
            (bc, ab, ac),
        ):
            row_indices.extend((row, row, row))
            column_indices.extend(
                (positive, negative_first, negative_second)
            )
            data.extend((1.0, -1.0, -1.0))
            row += 1

    if with_triangle_perimeter:
        perimeter_index = distance_variables
        for first, second, third in TRIPLES:
            row_indices.extend((row, row, row, row))
            column_indices.extend(
                (
                    EDGE_INDEX[(first, second)],
                    EDGE_INDEX[(first, third)],
                    EDGE_INDEX[(second, third)],
                    perimeter_index,
                )
            )
            data.extend((1.0, 1.0, 1.0, -1.0))
            row += 1

    inequalities = coo_matrix(
        (data, (row_indices, column_indices)),
        shape=(row, variable_count),
        dtype=np.float64,
    ).tocsr()
    rhs = np.zeros(row, dtype=np.float64)
    equality = np.zeros((1, variable_count), dtype=np.float64)
    equality[0, :distance_variables] = 1.0
    bounds: list[tuple[float | None, float | None]] = [
        (0.0, None)
    ] * variable_count
    return inequalities, rhs, equality, bounds


def _semimetric_diagnostics(weights: np.ndarray) -> dict[str, float]:
    max_triangle_excess = 0.0
    max_perimeter = 0.0
    for first, second, third in TRIPLES:
        ab = weights[EDGE_INDEX[(first, second)]]
        ac = weights[EDGE_INDEX[(first, third)]]
        bc = weights[EDGE_INDEX[(second, third)]]
        max_triangle_excess = max(
            max_triangle_excess,
            ab - ac - bc,
            ac - ab - bc,
            bc - ab - ac,
        )
        max_perimeter = max(max_perimeter, ab + ac + bc)
    return {
        "normalization": float(weights.sum()),
        "minimum_weight": float(weights.min(initial=0.0)),
        "maximum_triangle_excess": float(max_triangle_excess),
        "maximum_triangle_perimeter": float(max_perimeter),
    }


def separate_semimetric_cone(
    coefficients: Mapping[LabelEdge, int],
    spec: AtomRowSpec,
    tolerance: float = 1e-8,
) -> dict[str, object]:
    """Solve the normalized exact-real separation LP for one row."""
    if tolerance <= 0:
        raise ValueError("tolerance must be positive")
    if spec.positive_triangles not in (0, 6):
        raise ValueError("the exact oracle supports hard h=0 or opposite h=6")
    row = _coefficient_vector(coefficients)
    opposite = spec.positive_triangles == 6
    inequalities, rhs, equality, bounds = _semimetric_constraints(opposite)
    objective = np.zeros(len(EDGES) + int(opposite), dtype=np.float64)
    objective[: len(EDGES)] = -row
    if opposite:
        objective[-1] = float(spec.positive_triangles)
    result = linprog(
        objective,
        A_ub=inequalities,
        b_ub=rhs,
        A_eq=equality,
        b_eq=np.array([1.0]),
        bounds=bounds,
        method="highs-ds",
        options={"presolve": True},
    )
    if not result.success or result.x is None:
        raise ArithmeticError(
            f"semimetric separation LP failed: {result.message}"
        )
    weights = np.maximum(result.x[: len(EDGES)], 0.0)
    diagnostics = _semimetric_diagnostics(weights)
    max_perimeter = diagnostics["maximum_triangle_perimeter"]
    learned_rhs = spec.positive_triangles * max_perimeter
    lhs = float(np.dot(row, weights))
    margin = lhs - learned_rhs
    if (
        abs(diagnostics["normalization"] - 1.0) > 2e-7
        or diagnostics["minimum_weight"] < -tolerance
        or diagnostics["maximum_triangle_excess"] > 2e-7
        or abs(margin + float(result.fun)) > 2e-7
    ):
        raise ArithmeticError("the returned LP functional failed replay")

    sparse_weights = tuple(
        (edge, float(weights[index]))
        for index, edge in enumerate(EDGES)
        if weights[index] > tolerance
    )
    return {
        "p": P,
        "positive_triangles": spec.positive_triangles,
        "compact_atoms": spec.compact_atoms,
        "edge_sum": int(round(float(row.sum()))),
        "required_edge_sum": spec.target_edge_sum,
        "edge_sum_matches_atom_count": bool(
            round(float(row.sum())) == spec.target_edge_sum
        ),
        "lp_status": int(result.status),
        "lp_message": str(result.message),
        "normalized_semimetric_weights": tuple(float(value) for value in weights),
        "sparse_semimetric_weights": sparse_weights,
        "learned_cut_lhs": lhs,
        "learned_cut_rhs": learned_rhs,
        "separation_margin": margin,
        "strictly_separates_real_atom_relaxation": bool(margin > tolerance),
        "semimetric_diagnostics": diagnostics,
        "gpu_learned_cut": (
            "score=max(0,sum_e x_e*d_e-rhs); cell delta adds delta*d_uv"
        ),
        "integral_decomposition_certified": False,
        "proved_numeric": True,
    }


def normalized_cut_metric(
    subset: tuple[int, ...] | list[int],
) -> dict[LabelEdge, float]:
    """Return the sum-one cut semimetric of a proper nonempty subset."""
    chosen = set(subset)
    if not chosen or len(chosen) == P or any(
        not isinstance(value, int)
        or isinstance(value, bool)
        or not 0 <= value < P
        for value in chosen
    ):
        raise ValueError("subset must be a proper nonempty p31 label subset")
    denominator = len(chosen) * (P - len(chosen))
    return {
        edge: (1.0 / denominator if (edge[0] in chosen) != (edge[1] in chosen) else 0.0)
        for edge in EDGES
    }


def learned_cut_score(
    coefficients: Mapping[LabelEdge, int],
    weights: Mapping[LabelEdge, float],
    rhs: float,
) -> float:
    """Evaluate one frozen learned cut; GPU mutations update it in O(1)."""
    lhs = sum(coefficients.get(edge, 0) * weight for edge, weight in weights.items())
    return max(0.0, lhs - rhs)


def three_label_cut_strict_witness() -> dict[str, object]:
    """Pass the 496-cut bank but fail the exact semimetric oracle."""
    coefficients: dict[LabelEdge, int] = {}

    def add(first: int, second: int, value: int) -> None:
        edge = tuple(sorted((first, second)))
        coefficients[edge] = coefficients.get(edge, 0) + value

    # Two negative triangles on U={0,1,2} and V={3,4,5}, joined by
    # three coefficient-two positive edges.  Every singleton and pair cut
    # is nonpositive, while delta(U) has value six.
    for edge in ((0, 1), (0, 2), (1, 2), (3, 4), (3, 5), (4, 5)):
        add(*edge, -2)
    for edge in ((0, 3), (1, 4), (2, 5)):
        add(*edge, 2)
    # Five copies of K(6,7;8) pad the exact live count to b=11 without
    # meeting the displayed six-label block.
    add(6, 7, 5)
    add(6, 8, -5)
    add(7, 8, -5)

    spec = AtomRowSpec.hard(11)
    bank = IncrementalAtomRowBound(coefficients, spec).summary()
    cut_weights = normalized_cut_metric((0, 1, 2))
    denominator = 3 * (P - 3)
    cut_numerator = sum(
        value
        for edge, value in coefficients.items()
        if (edge[0] < 3) != (edge[1] < 3)
    )
    exact_cut_margin = cut_numerator / denominator
    explicit_score = learned_cut_score(coefficients, cut_weights, rhs=0.0)
    lp = separate_semimetric_cone(coefficients, spec)
    proved = bool(
        bank["incremental_search_cost"] == 0
        and bank["coefficient_l1_edit_lower_bound"] == 0
        and cut_numerator == 6
        and abs(exact_cut_margin - 1 / 14) < 1e-12
        and abs(explicit_score - exact_cut_margin) < 1e-12
        and lp["strictly_separates_real_atom_relaxation"]
        and float(lp["separation_margin"]) + 1e-9 >= exact_cut_margin
    )
    if not proved:
        raise ArithmeticError("the strict three-label metric witness changed")
    return {
        "p": P,
        "compact_atoms": 11,
        "singleton_two_label_bank_cost": bank["incremental_search_cost"],
        "singleton_two_label_edit_lower_bound": bank[
            "coefficient_l1_edit_lower_bound"
        ],
        "violated_cut_subset": [0, 1, 2],
        "cut_numerator": cut_numerator,
        "cut_metric_normalization_denominator": denominator,
        "exact_normalized_cut_margin": "1/14",
        "lp_separation_margin": lp["separation_margin"],
        "lp_sparse_weight_count": len(lp["sparse_semimetric_weights"]),
        "strictly_stronger_than_496_cut_bank": True,
        "coefficients": coefficients,
        "proved": proved,
    }


def generated_atom_row_validation() -> dict[str, object]:
    """Verify one generated hard row and one opposite row satisfy the LP."""
    hard: dict[LabelEdge, int] = {
        (0, 1): 11,
        (0, 2): -11,
        (1, 2): -11,
    }
    opposite: dict[LabelEdge, int] = {
        (0, 1): 6,
        (0, 2): 6,
        (1, 2): 6,
        (3, 4): 6,
        (3, 5): -6,
        (4, 5): -6,
    }
    hard_lp = separate_semimetric_cone(hard, AtomRowSpec.hard(11))
    opposite_lp = separate_semimetric_cone(
        opposite, AtomRowSpec.opposite(6)
    )
    proved = bool(
        hard_lp["edge_sum_matches_atom_count"]
        and opposite_lp["edge_sum_matches_atom_count"]
        and float(hard_lp["separation_margin"]) <= 1e-8
        and float(opposite_lp["separation_margin"]) <= 1e-8
        and not hard_lp["strictly_separates_real_atom_relaxation"]
        and not opposite_lp["strictly_separates_real_atom_relaxation"]
    )
    if not proved:
        raise ArithmeticError("a generated atom row failed the real-cone oracle")
    return {
        "hard_margin": hard_lp["separation_margin"],
        "opposite_margin": opposite_lp["separation_margin"],
        "hard_generated_from_eleven_identical_compact_atoms": True,
        "opposite_generated_from_six_triangles_and_six_compact_atoms": True,
        "proved": proved,
    }


def theorem_record() -> dict[str, object]:
    generated = generated_atom_row_validation()
    strict = three_label_cut_strict_witness()
    return {
        "title": "exact real compact-cone semimetric separator at p31",
        "hard_real_cone_criterion": (
            "edge sum=-b and <x,d><=0 for every semimetric d"
        ),
        "opposite_real_relaxation_criterion": (
            "edge sum=18-b and <x,d><=6 max_triangle perimeter(d)"
        ),
        "normalization": "sum_e d_e=1",
        "generated_atom_rows": generated,
        "strict_advance_over_incremental_cut_bank": strict,
        "learned_gpu_cut_cell_update": "lhs += delta*d_uv",
        "integral_normality_asserted": False,
        "residual_ii_closed": False,
        "proved": bool(generated["proved"] and strict["proved"]),
    }


def main() -> dict[str, object]:
    result = theorem_record()
    print(json.dumps(result, indent=2, sort_keys=True))
    return result


if __name__ == "__main__":
    main()
